// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/documenso/sdk-go/internal/utils"
	"github.com/documenso/sdk-go/models/components"
)

type DocumentUpdateVisibilityRequest string

const (
	DocumentUpdateVisibilityRequestEveryone        DocumentUpdateVisibilityRequest = "EVERYONE"
	DocumentUpdateVisibilityRequestManagerAndAbove DocumentUpdateVisibilityRequest = "MANAGER_AND_ABOVE"
	DocumentUpdateVisibilityRequestAdmin           DocumentUpdateVisibilityRequest = "ADMIN"
)

func (e DocumentUpdateVisibilityRequest) ToPointer() *DocumentUpdateVisibilityRequest {
	return &e
}
func (e *DocumentUpdateVisibilityRequest) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "EVERYONE":
		fallthrough
	case "MANAGER_AND_ABOVE":
		fallthrough
	case "ADMIN":
		*e = DocumentUpdateVisibilityRequest(v)
		return nil
	default:
		return fmt.Errorf("invalid value for DocumentUpdateVisibilityRequest: %v", v)
	}
}

type DocumentUpdateGlobalAccessAuthRequest string

const (
	DocumentUpdateGlobalAccessAuthRequestAccount       DocumentUpdateGlobalAccessAuthRequest = "ACCOUNT"
	DocumentUpdateGlobalAccessAuthRequestTwoFactorAuth DocumentUpdateGlobalAccessAuthRequest = "TWO_FACTOR_AUTH"
)

func (e DocumentUpdateGlobalAccessAuthRequest) ToPointer() *DocumentUpdateGlobalAccessAuthRequest {
	return &e
}
func (e *DocumentUpdateGlobalAccessAuthRequest) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "ACCOUNT":
		fallthrough
	case "TWO_FACTOR_AUTH":
		*e = DocumentUpdateGlobalAccessAuthRequest(v)
		return nil
	default:
		return fmt.Errorf("invalid value for DocumentUpdateGlobalAccessAuthRequest: %v", v)
	}
}

type DocumentUpdateGlobalActionAuthRequest string

const (
	DocumentUpdateGlobalActionAuthRequestAccount       DocumentUpdateGlobalActionAuthRequest = "ACCOUNT"
	DocumentUpdateGlobalActionAuthRequestPasskey       DocumentUpdateGlobalActionAuthRequest = "PASSKEY"
	DocumentUpdateGlobalActionAuthRequestTwoFactorAuth DocumentUpdateGlobalActionAuthRequest = "TWO_FACTOR_AUTH"
	DocumentUpdateGlobalActionAuthRequestPassword      DocumentUpdateGlobalActionAuthRequest = "PASSWORD"
)

func (e DocumentUpdateGlobalActionAuthRequest) ToPointer() *DocumentUpdateGlobalActionAuthRequest {
	return &e
}
func (e *DocumentUpdateGlobalActionAuthRequest) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "ACCOUNT":
		fallthrough
	case "PASSKEY":
		fallthrough
	case "TWO_FACTOR_AUTH":
		fallthrough
	case "PASSWORD":
		*e = DocumentUpdateGlobalActionAuthRequest(v)
		return nil
	default:
		return fmt.Errorf("invalid value for DocumentUpdateGlobalActionAuthRequest: %v", v)
	}
}

type DocumentUpdateData struct {
	Title                   *string                                 `json:"title,omitempty"`
	ExternalID              *string                                 `json:"externalId,omitempty"`
	Visibility              *DocumentUpdateVisibilityRequest        `json:"visibility,omitempty"`
	GlobalAccessAuth        []DocumentUpdateGlobalAccessAuthRequest `json:"globalAccessAuth,omitempty"`
	GlobalActionAuth        []DocumentUpdateGlobalActionAuthRequest `json:"globalActionAuth,omitempty"`
	UseLegacyFieldInsertion *bool                                   `json:"useLegacyFieldInsertion,omitempty"`
	FolderID                *string                                 `json:"folderId,omitempty"`
}

func (d *DocumentUpdateData) GetTitle() *string {
	if d == nil {
		return nil
	}
	return d.Title
}

func (d *DocumentUpdateData) GetExternalID() *string {
	if d == nil {
		return nil
	}
	return d.ExternalID
}

func (d *DocumentUpdateData) GetVisibility() *DocumentUpdateVisibilityRequest {
	if d == nil {
		return nil
	}
	return d.Visibility
}

func (d *DocumentUpdateData) GetGlobalAccessAuth() []DocumentUpdateGlobalAccessAuthRequest {
	if d == nil {
		return nil
	}
	return d.GlobalAccessAuth
}

func (d *DocumentUpdateData) GetGlobalActionAuth() []DocumentUpdateGlobalActionAuthRequest {
	if d == nil {
		return nil
	}
	return d.GlobalActionAuth
}

func (d *DocumentUpdateData) GetUseLegacyFieldInsertion() *bool {
	if d == nil {
		return nil
	}
	return d.UseLegacyFieldInsertion
}

func (d *DocumentUpdateData) GetFolderID() *string {
	if d == nil {
		return nil
	}
	return d.FolderID
}

type DocumentUpdateDateFormat string

const (
	DocumentUpdateDateFormatYyyyMMddHhMmA            DocumentUpdateDateFormat = "yyyy-MM-dd hh:mm a"
	DocumentUpdateDateFormatYyyyMMdd                 DocumentUpdateDateFormat = "yyyy-MM-dd"
	DocumentUpdateDateFormatDdMmSlashYyyy            DocumentUpdateDateFormat = "dd/MM/yyyy"
	DocumentUpdateDateFormatDdMmDashYyyy             DocumentUpdateDateFormat = "dd-MM-yyyy"
	DocumentUpdateDateFormatMmDdSlashYyyy            DocumentUpdateDateFormat = "MM/dd/yyyy"
	DocumentUpdateDateFormatYyMMdd                   DocumentUpdateDateFormat = "yy-MM-dd"
	DocumentUpdateDateFormatMmmmDdCommaYyyy          DocumentUpdateDateFormat = "MMMM dd, yyyy"
	DocumentUpdateDateFormatEeeeMmmmDdCommaYyyy      DocumentUpdateDateFormat = "EEEE, MMMM dd, yyyy"
	DocumentUpdateDateFormatDdMmSlashYyyyHhMmA       DocumentUpdateDateFormat = "dd/MM/yyyy hh:mm a"
	DocumentUpdateDateFormatDdMmSlashYyyyHHmm        DocumentUpdateDateFormat = "dd/MM/yyyy HH:mm"
	DocumentUpdateDateFormatDdMmDashYyyyHhMmA        DocumentUpdateDateFormat = "dd-MM-yyyy hh:mm a"
	DocumentUpdateDateFormatDdMmDashYyyyHHmm         DocumentUpdateDateFormat = "dd-MM-yyyy HH:mm"
	DocumentUpdateDateFormatMmDdSlashYyyyHhMmA       DocumentUpdateDateFormat = "MM/dd/yyyy hh:mm a"
	DocumentUpdateDateFormatMmDdSlashYyyyHHmm        DocumentUpdateDateFormat = "MM/dd/yyyy HH:mm"
	DocumentUpdateDateFormatDdDotMmDotYyyy           DocumentUpdateDateFormat = "dd.MM.yyyy"
	DocumentUpdateDateFormatDdDotMmDotYyyyHHmm       DocumentUpdateDateFormat = "dd.MM.yyyy HH:mm"
	DocumentUpdateDateFormatYyyyMMddHHmm             DocumentUpdateDateFormat = "yyyy-MM-dd HH:mm"
	DocumentUpdateDateFormatYyMMddHhMmA              DocumentUpdateDateFormat = "yy-MM-dd hh:mm a"
	DocumentUpdateDateFormatYyMMddHHmm               DocumentUpdateDateFormat = "yy-MM-dd HH:mm"
	DocumentUpdateDateFormatYyyyMMddHHmmss           DocumentUpdateDateFormat = "yyyy-MM-dd HH:mm:ss"
	DocumentUpdateDateFormatMmmmDdCommaYyyyHhMmA     DocumentUpdateDateFormat = "MMMM dd, yyyy hh:mm a"
	DocumentUpdateDateFormatMmmmDdCommaYyyyHHmm      DocumentUpdateDateFormat = "MMMM dd, yyyy HH:mm"
	DocumentUpdateDateFormatEeeeMmmmDdCommaYyyyHhMmA DocumentUpdateDateFormat = "EEEE, MMMM dd, yyyy hh:mm a"
	DocumentUpdateDateFormatEeeeMmmmDdCommaYyyyHHmm  DocumentUpdateDateFormat = "EEEE, MMMM dd, yyyy HH:mm"
	DocumentUpdateDateFormatIso8601Full              DocumentUpdateDateFormat = "yyyy-MM-dd'T'HH:mm:ss.SSSXXX"
)

func (e DocumentUpdateDateFormat) ToPointer() *DocumentUpdateDateFormat {
	return &e
}
func (e *DocumentUpdateDateFormat) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "yyyy-MM-dd hh:mm a":
		fallthrough
	case "yyyy-MM-dd":
		fallthrough
	case "dd/MM/yyyy":
		fallthrough
	case "dd-MM-yyyy":
		fallthrough
	case "MM/dd/yyyy":
		fallthrough
	case "yy-MM-dd":
		fallthrough
	case "MMMM dd, yyyy":
		fallthrough
	case "EEEE, MMMM dd, yyyy":
		fallthrough
	case "dd/MM/yyyy hh:mm a":
		fallthrough
	case "dd/MM/yyyy HH:mm":
		fallthrough
	case "dd-MM-yyyy hh:mm a":
		fallthrough
	case "dd-MM-yyyy HH:mm":
		fallthrough
	case "MM/dd/yyyy hh:mm a":
		fallthrough
	case "MM/dd/yyyy HH:mm":
		fallthrough
	case "dd.MM.yyyy":
		fallthrough
	case "dd.MM.yyyy HH:mm":
		fallthrough
	case "yyyy-MM-dd HH:mm":
		fallthrough
	case "yy-MM-dd hh:mm a":
		fallthrough
	case "yy-MM-dd HH:mm":
		fallthrough
	case "yyyy-MM-dd HH:mm:ss":
		fallthrough
	case "MMMM dd, yyyy hh:mm a":
		fallthrough
	case "MMMM dd, yyyy HH:mm":
		fallthrough
	case "EEEE, MMMM dd, yyyy hh:mm a":
		fallthrough
	case "EEEE, MMMM dd, yyyy HH:mm":
		fallthrough
	case "yyyy-MM-dd'T'HH:mm:ss.SSSXXX":
		*e = DocumentUpdateDateFormat(v)
		return nil
	default:
		return fmt.Errorf("invalid value for DocumentUpdateDateFormat: %v", v)
	}
}

type DocumentUpdateDistributionMethod string

const (
	DocumentUpdateDistributionMethodEmail DocumentUpdateDistributionMethod = "EMAIL"
	DocumentUpdateDistributionMethodNone  DocumentUpdateDistributionMethod = "NONE"
)

func (e DocumentUpdateDistributionMethod) ToPointer() *DocumentUpdateDistributionMethod {
	return &e
}
func (e *DocumentUpdateDistributionMethod) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "EMAIL":
		fallthrough
	case "NONE":
		*e = DocumentUpdateDistributionMethod(v)
		return nil
	default:
		return fmt.Errorf("invalid value for DocumentUpdateDistributionMethod: %v", v)
	}
}

type DocumentUpdateSigningOrder string

const (
	DocumentUpdateSigningOrderParallel   DocumentUpdateSigningOrder = "PARALLEL"
	DocumentUpdateSigningOrderSequential DocumentUpdateSigningOrder = "SEQUENTIAL"
)

func (e DocumentUpdateSigningOrder) ToPointer() *DocumentUpdateSigningOrder {
	return &e
}
func (e *DocumentUpdateSigningOrder) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "PARALLEL":
		fallthrough
	case "SEQUENTIAL":
		*e = DocumentUpdateSigningOrder(v)
		return nil
	default:
		return fmt.Errorf("invalid value for DocumentUpdateSigningOrder: %v", v)
	}
}

type DocumentUpdateLanguage string

const (
	DocumentUpdateLanguageDe   DocumentUpdateLanguage = "de"
	DocumentUpdateLanguageEn   DocumentUpdateLanguage = "en"
	DocumentUpdateLanguageFr   DocumentUpdateLanguage = "fr"
	DocumentUpdateLanguageEs   DocumentUpdateLanguage = "es"
	DocumentUpdateLanguageIt   DocumentUpdateLanguage = "it"
	DocumentUpdateLanguageNl   DocumentUpdateLanguage = "nl"
	DocumentUpdateLanguagePl   DocumentUpdateLanguage = "pl"
	DocumentUpdateLanguagePtBr DocumentUpdateLanguage = "pt-BR"
	DocumentUpdateLanguageJa   DocumentUpdateLanguage = "ja"
	DocumentUpdateLanguageKo   DocumentUpdateLanguage = "ko"
	DocumentUpdateLanguageZh   DocumentUpdateLanguage = "zh"
)

func (e DocumentUpdateLanguage) ToPointer() *DocumentUpdateLanguage {
	return &e
}
func (e *DocumentUpdateLanguage) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "de":
		fallthrough
	case "en":
		fallthrough
	case "fr":
		fallthrough
	case "es":
		fallthrough
	case "it":
		fallthrough
	case "nl":
		fallthrough
	case "pl":
		fallthrough
	case "pt-BR":
		fallthrough
	case "ja":
		fallthrough
	case "ko":
		fallthrough
	case "zh":
		*e = DocumentUpdateLanguage(v)
		return nil
	default:
		return fmt.Errorf("invalid value for DocumentUpdateLanguage: %v", v)
	}
}

type DocumentUpdateEmailSettings struct {
	RecipientSigningRequest *bool `default:"true" json:"recipientSigningRequest"`
	RecipientRemoved        *bool `default:"true" json:"recipientRemoved"`
	RecipientSigned         *bool `default:"true" json:"recipientSigned"`
	DocumentPending         *bool `default:"true" json:"documentPending"`
	DocumentCompleted       *bool `default:"true" json:"documentCompleted"`
	DocumentDeleted         *bool `default:"true" json:"documentDeleted"`
	OwnerDocumentCompleted  *bool `default:"true" json:"ownerDocumentCompleted"`
	OwnerRecipientExpired   *bool `default:"true" json:"ownerRecipientExpired"`
	OwnerDocumentCreated    *bool `default:"true" json:"ownerDocumentCreated"`
}

func (d DocumentUpdateEmailSettings) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DocumentUpdateEmailSettings) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DocumentUpdateEmailSettings) GetRecipientSigningRequest() *bool {
	if d == nil {
		return nil
	}
	return d.RecipientSigningRequest
}

func (d *DocumentUpdateEmailSettings) GetRecipientRemoved() *bool {
	if d == nil {
		return nil
	}
	return d.RecipientRemoved
}

func (d *DocumentUpdateEmailSettings) GetRecipientSigned() *bool {
	if d == nil {
		return nil
	}
	return d.RecipientSigned
}

func (d *DocumentUpdateEmailSettings) GetDocumentPending() *bool {
	if d == nil {
		return nil
	}
	return d.DocumentPending
}

func (d *DocumentUpdateEmailSettings) GetDocumentCompleted() *bool {
	if d == nil {
		return nil
	}
	return d.DocumentCompleted
}

func (d *DocumentUpdateEmailSettings) GetDocumentDeleted() *bool {
	if d == nil {
		return nil
	}
	return d.DocumentDeleted
}

func (d *DocumentUpdateEmailSettings) GetOwnerDocumentCompleted() *bool {
	if d == nil {
		return nil
	}
	return d.OwnerDocumentCompleted
}

func (d *DocumentUpdateEmailSettings) GetOwnerRecipientExpired() *bool {
	if d == nil {
		return nil
	}
	return d.OwnerRecipientExpired
}

func (d *DocumentUpdateEmailSettings) GetOwnerDocumentCreated() *bool {
	if d == nil {
		return nil
	}
	return d.OwnerDocumentCreated
}

type DocumentUpdateEnvelopeExpirationPeriod2 struct {
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	disabled bool `const:"true" json:"disabled"`
}

func (d DocumentUpdateEnvelopeExpirationPeriod2) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DocumentUpdateEnvelopeExpirationPeriod2) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, []string{"disabled"}); err != nil {
		return err
	}
	return nil
}

func (d *DocumentUpdateEnvelopeExpirationPeriod2) GetDisabled() bool {
	return true
}

// #region class-body-documentupdateenvelopeexpirationperiod2
// #endregion class-body-documentupdateenvelopeexpirationperiod2

type DocumentUpdateEnvelopeExpirationPeriodUnit string

const (
	DocumentUpdateEnvelopeExpirationPeriodUnitDay   DocumentUpdateEnvelopeExpirationPeriodUnit = "day"
	DocumentUpdateEnvelopeExpirationPeriodUnitWeek  DocumentUpdateEnvelopeExpirationPeriodUnit = "week"
	DocumentUpdateEnvelopeExpirationPeriodUnitMonth DocumentUpdateEnvelopeExpirationPeriodUnit = "month"
	DocumentUpdateEnvelopeExpirationPeriodUnitYear  DocumentUpdateEnvelopeExpirationPeriodUnit = "year"
)

func (e DocumentUpdateEnvelopeExpirationPeriodUnit) ToPointer() *DocumentUpdateEnvelopeExpirationPeriodUnit {
	return &e
}
func (e *DocumentUpdateEnvelopeExpirationPeriodUnit) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "day":
		fallthrough
	case "week":
		fallthrough
	case "month":
		fallthrough
	case "year":
		*e = DocumentUpdateEnvelopeExpirationPeriodUnit(v)
		return nil
	default:
		return fmt.Errorf("invalid value for DocumentUpdateEnvelopeExpirationPeriodUnit: %v", v)
	}
}

type DocumentUpdateEnvelopeExpirationPeriod1 struct {
	Unit   DocumentUpdateEnvelopeExpirationPeriodUnit `json:"unit"`
	Amount int64                                      `json:"amount"`
}

func (d DocumentUpdateEnvelopeExpirationPeriod1) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DocumentUpdateEnvelopeExpirationPeriod1) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, []string{"unit", "amount"}); err != nil {
		return err
	}
	return nil
}

func (d *DocumentUpdateEnvelopeExpirationPeriod1) GetUnit() DocumentUpdateEnvelopeExpirationPeriodUnit {
	if d == nil {
		return DocumentUpdateEnvelopeExpirationPeriodUnit("")
	}
	return d.Unit
}

func (d *DocumentUpdateEnvelopeExpirationPeriod1) GetAmount() int64 {
	if d == nil {
		return 0
	}
	return d.Amount
}

// #region class-body-documentupdateenvelopeexpirationperiod1
// #endregion class-body-documentupdateenvelopeexpirationperiod1

type DocumentUpdateEnvelopeExpirationPeriodUnionType string

const (
	DocumentUpdateEnvelopeExpirationPeriodUnionTypeDocumentUpdateEnvelopeExpirationPeriod1 DocumentUpdateEnvelopeExpirationPeriodUnionType = "document_update_envelopeExpirationPeriod_1"
	DocumentUpdateEnvelopeExpirationPeriodUnionTypeDocumentUpdateEnvelopeExpirationPeriod2 DocumentUpdateEnvelopeExpirationPeriodUnionType = "document_update_envelopeExpirationPeriod_2"
)

type DocumentUpdateEnvelopeExpirationPeriodUnion struct {
	DocumentUpdateEnvelopeExpirationPeriod1 *DocumentUpdateEnvelopeExpirationPeriod1 `queryParam:"inline" union:"member"`
	DocumentUpdateEnvelopeExpirationPeriod2 *DocumentUpdateEnvelopeExpirationPeriod2 `queryParam:"inline" union:"member"`

	Type DocumentUpdateEnvelopeExpirationPeriodUnionType
}

func CreateDocumentUpdateEnvelopeExpirationPeriodUnionDocumentUpdateEnvelopeExpirationPeriod1(documentUpdateEnvelopeExpirationPeriod1 DocumentUpdateEnvelopeExpirationPeriod1) DocumentUpdateEnvelopeExpirationPeriodUnion {
	typ := DocumentUpdateEnvelopeExpirationPeriodUnionTypeDocumentUpdateEnvelopeExpirationPeriod1

	return DocumentUpdateEnvelopeExpirationPeriodUnion{
		DocumentUpdateEnvelopeExpirationPeriod1: &documentUpdateEnvelopeExpirationPeriod1,
		Type:                                    typ,
	}
}

func CreateDocumentUpdateEnvelopeExpirationPeriodUnionDocumentUpdateEnvelopeExpirationPeriod2(documentUpdateEnvelopeExpirationPeriod2 DocumentUpdateEnvelopeExpirationPeriod2) DocumentUpdateEnvelopeExpirationPeriodUnion {
	typ := DocumentUpdateEnvelopeExpirationPeriodUnionTypeDocumentUpdateEnvelopeExpirationPeriod2

	return DocumentUpdateEnvelopeExpirationPeriodUnion{
		DocumentUpdateEnvelopeExpirationPeriod2: &documentUpdateEnvelopeExpirationPeriod2,
		Type:                                    typ,
	}
}

func (u *DocumentUpdateEnvelopeExpirationPeriodUnion) UnmarshalJSON(data []byte) (err error) {
	previous := *u
	*u = DocumentUpdateEnvelopeExpirationPeriodUnion{}
	defer func() {
		if err != nil {
			*u = previous
		}
	}()

	var documentUpdateEnvelopeExpirationPeriod1 DocumentUpdateEnvelopeExpirationPeriod1 = DocumentUpdateEnvelopeExpirationPeriod1{}
	if err := utils.UnmarshalJSON(data, &documentUpdateEnvelopeExpirationPeriod1, "", true, nil); err == nil {
		u.DocumentUpdateEnvelopeExpirationPeriod1 = &documentUpdateEnvelopeExpirationPeriod1
		u.Type = DocumentUpdateEnvelopeExpirationPeriodUnionTypeDocumentUpdateEnvelopeExpirationPeriod1
		return nil
	}

	var documentUpdateEnvelopeExpirationPeriod2 DocumentUpdateEnvelopeExpirationPeriod2 = DocumentUpdateEnvelopeExpirationPeriod2{}
	if err := utils.UnmarshalJSON(data, &documentUpdateEnvelopeExpirationPeriod2, "", true, nil); err == nil {
		u.DocumentUpdateEnvelopeExpirationPeriod2 = &documentUpdateEnvelopeExpirationPeriod2
		u.Type = DocumentUpdateEnvelopeExpirationPeriodUnionTypeDocumentUpdateEnvelopeExpirationPeriod2
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for DocumentUpdateEnvelopeExpirationPeriodUnion", string(data))
}

func (u DocumentUpdateEnvelopeExpirationPeriodUnion) MarshalJSON() ([]byte, error) {
	if u.DocumentUpdateEnvelopeExpirationPeriod1 != nil {
		return utils.MarshalJSON(u.DocumentUpdateEnvelopeExpirationPeriod1, "", true)
	}

	if u.DocumentUpdateEnvelopeExpirationPeriod2 != nil {
		return utils.MarshalJSON(u.DocumentUpdateEnvelopeExpirationPeriod2, "", true)
	}

	return nil, errors.New("could not marshal union type DocumentUpdateEnvelopeExpirationPeriodUnion: all fields are null")
}

type DocumentUpdateSendAfter2 struct {
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	disabled bool `const:"true" json:"disabled"`
}

func (d DocumentUpdateSendAfter2) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DocumentUpdateSendAfter2) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, []string{"disabled"}); err != nil {
		return err
	}
	return nil
}

func (d *DocumentUpdateSendAfter2) GetDisabled() bool {
	return true
}

// #region class-body-documentupdatesendafter2
// #endregion class-body-documentupdatesendafter2

type DocumentUpdateSendAfterUnit string

const (
	DocumentUpdateSendAfterUnitDay   DocumentUpdateSendAfterUnit = "day"
	DocumentUpdateSendAfterUnitWeek  DocumentUpdateSendAfterUnit = "week"
	DocumentUpdateSendAfterUnitMonth DocumentUpdateSendAfterUnit = "month"
)

func (e DocumentUpdateSendAfterUnit) ToPointer() *DocumentUpdateSendAfterUnit {
	return &e
}
func (e *DocumentUpdateSendAfterUnit) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "day":
		fallthrough
	case "week":
		fallthrough
	case "month":
		*e = DocumentUpdateSendAfterUnit(v)
		return nil
	default:
		return fmt.Errorf("invalid value for DocumentUpdateSendAfterUnit: %v", v)
	}
}

type DocumentUpdateSendAfter1 struct {
	Unit   DocumentUpdateSendAfterUnit `json:"unit"`
	Amount int64                       `json:"amount"`
}

func (d DocumentUpdateSendAfter1) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DocumentUpdateSendAfter1) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, []string{"unit", "amount"}); err != nil {
		return err
	}
	return nil
}

func (d *DocumentUpdateSendAfter1) GetUnit() DocumentUpdateSendAfterUnit {
	if d == nil {
		return DocumentUpdateSendAfterUnit("")
	}
	return d.Unit
}

func (d *DocumentUpdateSendAfter1) GetAmount() int64 {
	if d == nil {
		return 0
	}
	return d.Amount
}

// #region class-body-documentupdatesendafter1
// #endregion class-body-documentupdatesendafter1

type DocumentUpdateSendAfterUnionType string

const (
	DocumentUpdateSendAfterUnionTypeDocumentUpdateSendAfter1 DocumentUpdateSendAfterUnionType = "document_update_sendAfter_1"
	DocumentUpdateSendAfterUnionTypeDocumentUpdateSendAfter2 DocumentUpdateSendAfterUnionType = "document_update_sendAfter_2"
)

type DocumentUpdateSendAfterUnion struct {
	DocumentUpdateSendAfter1 *DocumentUpdateSendAfter1 `queryParam:"inline" union:"member"`
	DocumentUpdateSendAfter2 *DocumentUpdateSendAfter2 `queryParam:"inline" union:"member"`

	Type DocumentUpdateSendAfterUnionType
}

func CreateDocumentUpdateSendAfterUnionDocumentUpdateSendAfter1(documentUpdateSendAfter1 DocumentUpdateSendAfter1) DocumentUpdateSendAfterUnion {
	typ := DocumentUpdateSendAfterUnionTypeDocumentUpdateSendAfter1

	return DocumentUpdateSendAfterUnion{
		DocumentUpdateSendAfter1: &documentUpdateSendAfter1,
		Type:                     typ,
	}
}

func CreateDocumentUpdateSendAfterUnionDocumentUpdateSendAfter2(documentUpdateSendAfter2 DocumentUpdateSendAfter2) DocumentUpdateSendAfterUnion {
	typ := DocumentUpdateSendAfterUnionTypeDocumentUpdateSendAfter2

	return DocumentUpdateSendAfterUnion{
		DocumentUpdateSendAfter2: &documentUpdateSendAfter2,
		Type:                     typ,
	}
}

func (u *DocumentUpdateSendAfterUnion) UnmarshalJSON(data []byte) (err error) {
	previous := *u
	*u = DocumentUpdateSendAfterUnion{}
	defer func() {
		if err != nil {
			*u = previous
		}
	}()

	var documentUpdateSendAfter1 DocumentUpdateSendAfter1 = DocumentUpdateSendAfter1{}
	if err := utils.UnmarshalJSON(data, &documentUpdateSendAfter1, "", true, nil); err == nil {
		u.DocumentUpdateSendAfter1 = &documentUpdateSendAfter1
		u.Type = DocumentUpdateSendAfterUnionTypeDocumentUpdateSendAfter1
		return nil
	}

	var documentUpdateSendAfter2 DocumentUpdateSendAfter2 = DocumentUpdateSendAfter2{}
	if err := utils.UnmarshalJSON(data, &documentUpdateSendAfter2, "", true, nil); err == nil {
		u.DocumentUpdateSendAfter2 = &documentUpdateSendAfter2
		u.Type = DocumentUpdateSendAfterUnionTypeDocumentUpdateSendAfter2
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for DocumentUpdateSendAfterUnion", string(data))
}

func (u DocumentUpdateSendAfterUnion) MarshalJSON() ([]byte, error) {
	if u.DocumentUpdateSendAfter1 != nil {
		return utils.MarshalJSON(u.DocumentUpdateSendAfter1, "", true)
	}

	if u.DocumentUpdateSendAfter2 != nil {
		return utils.MarshalJSON(u.DocumentUpdateSendAfter2, "", true)
	}

	return nil, errors.New("could not marshal union type DocumentUpdateSendAfterUnion: all fields are null")
}

type DocumentUpdateRepeatEvery2 struct {
	//lint:ignore U1000 accessed via reflection for JSON marshaling
	disabled bool `const:"true" json:"disabled"`
}

func (d DocumentUpdateRepeatEvery2) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DocumentUpdateRepeatEvery2) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, []string{"disabled"}); err != nil {
		return err
	}
	return nil
}

func (d *DocumentUpdateRepeatEvery2) GetDisabled() bool {
	return true
}

// #region class-body-documentupdaterepeatevery2
// #endregion class-body-documentupdaterepeatevery2

type DocumentUpdateRepeatEveryUnit string

const (
	DocumentUpdateRepeatEveryUnitDay   DocumentUpdateRepeatEveryUnit = "day"
	DocumentUpdateRepeatEveryUnitWeek  DocumentUpdateRepeatEveryUnit = "week"
	DocumentUpdateRepeatEveryUnitMonth DocumentUpdateRepeatEveryUnit = "month"
)

func (e DocumentUpdateRepeatEveryUnit) ToPointer() *DocumentUpdateRepeatEveryUnit {
	return &e
}
func (e *DocumentUpdateRepeatEveryUnit) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "day":
		fallthrough
	case "week":
		fallthrough
	case "month":
		*e = DocumentUpdateRepeatEveryUnit(v)
		return nil
	default:
		return fmt.Errorf("invalid value for DocumentUpdateRepeatEveryUnit: %v", v)
	}
}

type DocumentUpdateRepeatEvery1 struct {
	Unit   DocumentUpdateRepeatEveryUnit `json:"unit"`
	Amount int64                         `json:"amount"`
}

func (d DocumentUpdateRepeatEvery1) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DocumentUpdateRepeatEvery1) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, []string{"unit", "amount"}); err != nil {
		return err
	}
	return nil
}

func (d *DocumentUpdateRepeatEvery1) GetUnit() DocumentUpdateRepeatEveryUnit {
	if d == nil {
		return DocumentUpdateRepeatEveryUnit("")
	}
	return d.Unit
}

func (d *DocumentUpdateRepeatEvery1) GetAmount() int64 {
	if d == nil {
		return 0
	}
	return d.Amount
}

// #region class-body-documentupdaterepeatevery1
// #endregion class-body-documentupdaterepeatevery1

type DocumentUpdateRepeatEveryUnionType string

const (
	DocumentUpdateRepeatEveryUnionTypeDocumentUpdateRepeatEvery1 DocumentUpdateRepeatEveryUnionType = "document_update_repeatEvery_1"
	DocumentUpdateRepeatEveryUnionTypeDocumentUpdateRepeatEvery2 DocumentUpdateRepeatEveryUnionType = "document_update_repeatEvery_2"
)

type DocumentUpdateRepeatEveryUnion struct {
	DocumentUpdateRepeatEvery1 *DocumentUpdateRepeatEvery1 `queryParam:"inline" union:"member"`
	DocumentUpdateRepeatEvery2 *DocumentUpdateRepeatEvery2 `queryParam:"inline" union:"member"`

	Type DocumentUpdateRepeatEveryUnionType
}

func CreateDocumentUpdateRepeatEveryUnionDocumentUpdateRepeatEvery1(documentUpdateRepeatEvery1 DocumentUpdateRepeatEvery1) DocumentUpdateRepeatEveryUnion {
	typ := DocumentUpdateRepeatEveryUnionTypeDocumentUpdateRepeatEvery1

	return DocumentUpdateRepeatEveryUnion{
		DocumentUpdateRepeatEvery1: &documentUpdateRepeatEvery1,
		Type:                       typ,
	}
}

func CreateDocumentUpdateRepeatEveryUnionDocumentUpdateRepeatEvery2(documentUpdateRepeatEvery2 DocumentUpdateRepeatEvery2) DocumentUpdateRepeatEveryUnion {
	typ := DocumentUpdateRepeatEveryUnionTypeDocumentUpdateRepeatEvery2

	return DocumentUpdateRepeatEveryUnion{
		DocumentUpdateRepeatEvery2: &documentUpdateRepeatEvery2,
		Type:                       typ,
	}
}

func (u *DocumentUpdateRepeatEveryUnion) UnmarshalJSON(data []byte) (err error) {
	previous := *u
	*u = DocumentUpdateRepeatEveryUnion{}
	defer func() {
		if err != nil {
			*u = previous
		}
	}()

	var documentUpdateRepeatEvery1 DocumentUpdateRepeatEvery1 = DocumentUpdateRepeatEvery1{}
	if err := utils.UnmarshalJSON(data, &documentUpdateRepeatEvery1, "", true, nil); err == nil {
		u.DocumentUpdateRepeatEvery1 = &documentUpdateRepeatEvery1
		u.Type = DocumentUpdateRepeatEveryUnionTypeDocumentUpdateRepeatEvery1
		return nil
	}

	var documentUpdateRepeatEvery2 DocumentUpdateRepeatEvery2 = DocumentUpdateRepeatEvery2{}
	if err := utils.UnmarshalJSON(data, &documentUpdateRepeatEvery2, "", true, nil); err == nil {
		u.DocumentUpdateRepeatEvery2 = &documentUpdateRepeatEvery2
		u.Type = DocumentUpdateRepeatEveryUnionTypeDocumentUpdateRepeatEvery2
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for DocumentUpdateRepeatEveryUnion", string(data))
}

func (u DocumentUpdateRepeatEveryUnion) MarshalJSON() ([]byte, error) {
	if u.DocumentUpdateRepeatEvery1 != nil {
		return utils.MarshalJSON(u.DocumentUpdateRepeatEvery1, "", true)
	}

	if u.DocumentUpdateRepeatEvery2 != nil {
		return utils.MarshalJSON(u.DocumentUpdateRepeatEvery2, "", true)
	}

	return nil, errors.New("could not marshal union type DocumentUpdateRepeatEveryUnion: all fields are null")
}

type DocumentUpdateReminderSettings struct {
	SendAfter   DocumentUpdateSendAfterUnion   `json:"sendAfter"`
	RepeatEvery DocumentUpdateRepeatEveryUnion `json:"repeatEvery"`
}

func (d *DocumentUpdateReminderSettings) GetSendAfter() DocumentUpdateSendAfterUnion {
	if d == nil {
		return DocumentUpdateSendAfterUnion{}
	}
	return d.SendAfter
}

func (d *DocumentUpdateReminderSettings) GetRepeatEvery() DocumentUpdateRepeatEveryUnion {
	if d == nil {
		return DocumentUpdateRepeatEveryUnion{}
	}
	return d.RepeatEvery
}

type DocumentUpdateMeta struct {
	Subject                  *string                                      `json:"subject,omitempty"`
	Message                  *string                                      `json:"message,omitempty"`
	Timezone                 *string                                      `json:"timezone,omitempty"`
	DateFormat               *DocumentUpdateDateFormat                    `json:"dateFormat,omitempty"`
	DistributionMethod       *DocumentUpdateDistributionMethod            `json:"distributionMethod,omitempty"`
	SigningOrder             *DocumentUpdateSigningOrder                  `json:"signingOrder,omitempty"`
	AllowDictateNextSigner   *bool                                        `json:"allowDictateNextSigner,omitempty"`
	RedirectURL              *string                                      `json:"redirectUrl,omitempty"`
	Language                 *DocumentUpdateLanguage                      `json:"language,omitempty"`
	TypedSignatureEnabled    *bool                                        `json:"typedSignatureEnabled,omitempty"`
	UploadSignatureEnabled   *bool                                        `json:"uploadSignatureEnabled,omitempty"`
	DrawSignatureEnabled     *bool                                        `json:"drawSignatureEnabled,omitempty"`
	EmailID                  *string                                      `json:"emailId,omitempty"`
	EmailReplyTo             *string                                      `json:"emailReplyTo,omitempty"`
	EmailSettings            *DocumentUpdateEmailSettings                 `json:"emailSettings,omitempty"`
	EnvelopeExpirationPeriod *DocumentUpdateEnvelopeExpirationPeriodUnion `json:"envelopeExpirationPeriod,omitempty"`
	ReminderSettings         *DocumentUpdateReminderSettings              `json:"reminderSettings,omitempty"`
}

func (d *DocumentUpdateMeta) GetSubject() *string {
	if d == nil {
		return nil
	}
	return d.Subject
}

func (d *DocumentUpdateMeta) GetMessage() *string {
	if d == nil {
		return nil
	}
	return d.Message
}

func (d *DocumentUpdateMeta) GetTimezone() *string {
	if d == nil {
		return nil
	}
	return d.Timezone
}

func (d *DocumentUpdateMeta) GetDateFormat() *DocumentUpdateDateFormat {
	if d == nil {
		return nil
	}
	return d.DateFormat
}

func (d *DocumentUpdateMeta) GetDistributionMethod() *DocumentUpdateDistributionMethod {
	if d == nil {
		return nil
	}
	return d.DistributionMethod
}

func (d *DocumentUpdateMeta) GetSigningOrder() *DocumentUpdateSigningOrder {
	if d == nil {
		return nil
	}
	return d.SigningOrder
}

func (d *DocumentUpdateMeta) GetAllowDictateNextSigner() *bool {
	if d == nil {
		return nil
	}
	return d.AllowDictateNextSigner
}

func (d *DocumentUpdateMeta) GetRedirectURL() *string {
	if d == nil {
		return nil
	}
	return d.RedirectURL
}

func (d *DocumentUpdateMeta) GetLanguage() *DocumentUpdateLanguage {
	if d == nil {
		return nil
	}
	return d.Language
}

func (d *DocumentUpdateMeta) GetTypedSignatureEnabled() *bool {
	if d == nil {
		return nil
	}
	return d.TypedSignatureEnabled
}

func (d *DocumentUpdateMeta) GetUploadSignatureEnabled() *bool {
	if d == nil {
		return nil
	}
	return d.UploadSignatureEnabled
}

func (d *DocumentUpdateMeta) GetDrawSignatureEnabled() *bool {
	if d == nil {
		return nil
	}
	return d.DrawSignatureEnabled
}

func (d *DocumentUpdateMeta) GetEmailID() *string {
	if d == nil {
		return nil
	}
	return d.EmailID
}

func (d *DocumentUpdateMeta) GetEmailReplyTo() *string {
	if d == nil {
		return nil
	}
	return d.EmailReplyTo
}

func (d *DocumentUpdateMeta) GetEmailSettings() *DocumentUpdateEmailSettings {
	if d == nil {
		return nil
	}
	return d.EmailSettings
}

func (d *DocumentUpdateMeta) GetEnvelopeExpirationPeriod() *DocumentUpdateEnvelopeExpirationPeriodUnion {
	if d == nil {
		return nil
	}
	return d.EnvelopeExpirationPeriod
}

func (d *DocumentUpdateMeta) GetReminderSettings() *DocumentUpdateReminderSettings {
	if d == nil {
		return nil
	}
	return d.ReminderSettings
}

type DocumentUpdateRequest struct {
	DocumentID float64             `json:"documentId"`
	Data       *DocumentUpdateData `json:"data,omitempty"`
	Meta       *DocumentUpdateMeta `json:"meta,omitempty"`
}

func (d *DocumentUpdateRequest) GetDocumentID() float64 {
	if d == nil {
		return 0.0
	}
	return d.DocumentID
}

func (d *DocumentUpdateRequest) GetData() *DocumentUpdateData {
	if d == nil {
		return nil
	}
	return d.Data
}

func (d *DocumentUpdateRequest) GetMeta() *DocumentUpdateMeta {
	if d == nil {
		return nil
	}
	return d.Meta
}

type DocumentUpdateVisibilityResponse string

const (
	DocumentUpdateVisibilityResponseEveryone        DocumentUpdateVisibilityResponse = "EVERYONE"
	DocumentUpdateVisibilityResponseManagerAndAbove DocumentUpdateVisibilityResponse = "MANAGER_AND_ABOVE"
	DocumentUpdateVisibilityResponseAdmin           DocumentUpdateVisibilityResponse = "ADMIN"
)

func (e DocumentUpdateVisibilityResponse) ToPointer() *DocumentUpdateVisibilityResponse {
	return &e
}
func (e *DocumentUpdateVisibilityResponse) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "EVERYONE":
		fallthrough
	case "MANAGER_AND_ABOVE":
		fallthrough
	case "ADMIN":
		*e = DocumentUpdateVisibilityResponse(v)
		return nil
	default:
		return fmt.Errorf("invalid value for DocumentUpdateVisibilityResponse: %v", v)
	}
}

type DocumentUpdateStatus string

const (
	DocumentUpdateStatusDraft     DocumentUpdateStatus = "DRAFT"
	DocumentUpdateStatusPending   DocumentUpdateStatus = "PENDING"
	DocumentUpdateStatusCompleted DocumentUpdateStatus = "COMPLETED"
	DocumentUpdateStatusRejected  DocumentUpdateStatus = "REJECTED"
	DocumentUpdateStatusCancelled DocumentUpdateStatus = "CANCELLED"
)

func (e DocumentUpdateStatus) ToPointer() *DocumentUpdateStatus {
	return &e
}
func (e *DocumentUpdateStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "DRAFT":
		fallthrough
	case "PENDING":
		fallthrough
	case "COMPLETED":
		fallthrough
	case "REJECTED":
		fallthrough
	case "CANCELLED":
		*e = DocumentUpdateStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for DocumentUpdateStatus: %v", v)
	}
}

type DocumentUpdateSource string

const (
	DocumentUpdateSourceDocument           DocumentUpdateSource = "DOCUMENT"
	DocumentUpdateSourceTemplate           DocumentUpdateSource = "TEMPLATE"
	DocumentUpdateSourceTemplateDirectLink DocumentUpdateSource = "TEMPLATE_DIRECT_LINK"
)

func (e DocumentUpdateSource) ToPointer() *DocumentUpdateSource {
	return &e
}
func (e *DocumentUpdateSource) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "DOCUMENT":
		fallthrough
	case "TEMPLATE":
		fallthrough
	case "TEMPLATE_DIRECT_LINK":
		*e = DocumentUpdateSource(v)
		return nil
	default:
		return fmt.Errorf("invalid value for DocumentUpdateSource: %v", v)
	}
}

type DocumentUpdateGlobalAccessAuthResponse string

const (
	DocumentUpdateGlobalAccessAuthResponseAccount       DocumentUpdateGlobalAccessAuthResponse = "ACCOUNT"
	DocumentUpdateGlobalAccessAuthResponseTwoFactorAuth DocumentUpdateGlobalAccessAuthResponse = "TWO_FACTOR_AUTH"
)

func (e DocumentUpdateGlobalAccessAuthResponse) ToPointer() *DocumentUpdateGlobalAccessAuthResponse {
	return &e
}
func (e *DocumentUpdateGlobalAccessAuthResponse) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "ACCOUNT":
		fallthrough
	case "TWO_FACTOR_AUTH":
		*e = DocumentUpdateGlobalAccessAuthResponse(v)
		return nil
	default:
		return fmt.Errorf("invalid value for DocumentUpdateGlobalAccessAuthResponse: %v", v)
	}
}

type DocumentUpdateGlobalActionAuthResponse string

const (
	DocumentUpdateGlobalActionAuthResponseAccount       DocumentUpdateGlobalActionAuthResponse = "ACCOUNT"
	DocumentUpdateGlobalActionAuthResponsePasskey       DocumentUpdateGlobalActionAuthResponse = "PASSKEY"
	DocumentUpdateGlobalActionAuthResponseTwoFactorAuth DocumentUpdateGlobalActionAuthResponse = "TWO_FACTOR_AUTH"
	DocumentUpdateGlobalActionAuthResponsePassword      DocumentUpdateGlobalActionAuthResponse = "PASSWORD"
)

func (e DocumentUpdateGlobalActionAuthResponse) ToPointer() *DocumentUpdateGlobalActionAuthResponse {
	return &e
}
func (e *DocumentUpdateGlobalActionAuthResponse) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "ACCOUNT":
		fallthrough
	case "PASSKEY":
		fallthrough
	case "TWO_FACTOR_AUTH":
		fallthrough
	case "PASSWORD":
		*e = DocumentUpdateGlobalActionAuthResponse(v)
		return nil
	default:
		return fmt.Errorf("invalid value for DocumentUpdateGlobalActionAuthResponse: %v", v)
	}
}

type DocumentUpdateAuthOptions struct {
	GlobalAccessAuth []DocumentUpdateGlobalAccessAuthResponse `json:"globalAccessAuth"`
	GlobalActionAuth []DocumentUpdateGlobalActionAuthResponse `json:"globalActionAuth"`
}

func (d *DocumentUpdateAuthOptions) GetGlobalAccessAuth() []DocumentUpdateGlobalAccessAuthResponse {
	if d == nil {
		return []DocumentUpdateGlobalAccessAuthResponse{}
	}
	return d.GlobalAccessAuth
}

func (d *DocumentUpdateAuthOptions) GetGlobalActionAuth() []DocumentUpdateGlobalActionAuthResponse {
	if d == nil {
		return []DocumentUpdateGlobalActionAuthResponse{}
	}
	return d.GlobalActionAuth
}

type DocumentUpdateFormValuesType string

const (
	DocumentUpdateFormValuesTypeStr     DocumentUpdateFormValuesType = "str"
	DocumentUpdateFormValuesTypeBoolean DocumentUpdateFormValuesType = "boolean"
	DocumentUpdateFormValuesTypeNumber  DocumentUpdateFormValuesType = "number"
)

type DocumentUpdateFormValues struct {
	Str     *string  `queryParam:"inline" union:"member"`
	Boolean *bool    `queryParam:"inline" union:"member"`
	Number  *float64 `queryParam:"inline" union:"member"`

	Type DocumentUpdateFormValuesType
}

func CreateDocumentUpdateFormValuesStr(str string) DocumentUpdateFormValues {
	typ := DocumentUpdateFormValuesTypeStr

	return DocumentUpdateFormValues{
		Str:  &str,
		Type: typ,
	}
}

func CreateDocumentUpdateFormValuesBoolean(boolean bool) DocumentUpdateFormValues {
	typ := DocumentUpdateFormValuesTypeBoolean

	return DocumentUpdateFormValues{
		Boolean: &boolean,
		Type:    typ,
	}
}

func CreateDocumentUpdateFormValuesNumber(number float64) DocumentUpdateFormValues {
	typ := DocumentUpdateFormValuesTypeNumber

	return DocumentUpdateFormValues{
		Number: &number,
		Type:   typ,
	}
}

func (u *DocumentUpdateFormValues) UnmarshalJSON(data []byte) (err error) {
	previous := *u
	*u = DocumentUpdateFormValues{}
	defer func() {
		if err != nil {
			*u = previous
		}
	}()

	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, nil); err == nil {
		u.Str = &str
		u.Type = DocumentUpdateFormValuesTypeStr
		return nil
	}

	var boolean bool = false
	if err := utils.UnmarshalJSON(data, &boolean, "", true, nil); err == nil {
		u.Boolean = &boolean
		u.Type = DocumentUpdateFormValuesTypeBoolean
		return nil
	}

	var number float64 = float64(0)
	if err := utils.UnmarshalJSON(data, &number, "", true, nil); err == nil {
		u.Number = &number
		u.Type = DocumentUpdateFormValuesTypeNumber
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for DocumentUpdateFormValues", string(data))
}

func (u DocumentUpdateFormValues) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.Boolean != nil {
		return utils.MarshalJSON(u.Boolean, "", true)
	}

	if u.Number != nil {
		return utils.MarshalJSON(u.Number, "", true)
	}

	return nil, errors.New("could not marshal union type DocumentUpdateFormValues: all fields are null")
}

// DocumentUpdateResponseBody - Successful response
type DocumentUpdateResponseBody struct {
	Visibility              DocumentUpdateVisibilityResponse    `json:"visibility"`
	Status                  DocumentUpdateStatus                `json:"status"`
	Source                  DocumentUpdateSource                `json:"source"`
	ID                      float64                             `json:"id"`
	ExternalID              *string                             `json:"externalId"`
	UserID                  float64                             `json:"userId"`
	AuthOptions             *DocumentUpdateAuthOptions          `json:"authOptions"`
	FormValues              map[string]DocumentUpdateFormValues `json:"formValues"`
	Title                   string                              `json:"title"`
	CreatedAt               string                              `json:"createdAt"`
	UpdatedAt               string                              `json:"updatedAt"`
	CompletedAt             *string                             `json:"completedAt"`
	DeletedAt               *string                             `json:"deletedAt"`
	TeamID                  float64                             `json:"teamId"`
	FolderID                *string                             `json:"folderId"`
	UseLegacyFieldInsertion bool                                `json:"useLegacyFieldInsertion"`
	EnvelopeID              string                              `json:"envelopeId"`
	InternalVersion         float64                             `json:"internalVersion"`
	DocumentDataID          *string                             `default:"" json:"documentDataId"`
	TemplateID              *float64                            `json:"templateId,omitempty"`
}

func (d DocumentUpdateResponseBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(d, "", false)
}

func (d *DocumentUpdateResponseBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &d, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (d *DocumentUpdateResponseBody) GetVisibility() DocumentUpdateVisibilityResponse {
	if d == nil {
		return DocumentUpdateVisibilityResponse("")
	}
	return d.Visibility
}

func (d *DocumentUpdateResponseBody) GetStatus() DocumentUpdateStatus {
	if d == nil {
		return DocumentUpdateStatus("")
	}
	return d.Status
}

func (d *DocumentUpdateResponseBody) GetSource() DocumentUpdateSource {
	if d == nil {
		return DocumentUpdateSource("")
	}
	return d.Source
}

func (d *DocumentUpdateResponseBody) GetID() float64 {
	if d == nil {
		return 0.0
	}
	return d.ID
}

func (d *DocumentUpdateResponseBody) GetExternalID() *string {
	if d == nil {
		return nil
	}
	return d.ExternalID
}

func (d *DocumentUpdateResponseBody) GetUserID() float64 {
	if d == nil {
		return 0.0
	}
	return d.UserID
}

func (d *DocumentUpdateResponseBody) GetAuthOptions() *DocumentUpdateAuthOptions {
	if d == nil {
		return nil
	}
	return d.AuthOptions
}

func (d *DocumentUpdateResponseBody) GetFormValues() map[string]DocumentUpdateFormValues {
	if d == nil {
		return nil
	}
	return d.FormValues
}

func (d *DocumentUpdateResponseBody) GetTitle() string {
	if d == nil {
		return ""
	}
	return d.Title
}

func (d *DocumentUpdateResponseBody) GetCreatedAt() string {
	if d == nil {
		return ""
	}
	return d.CreatedAt
}

func (d *DocumentUpdateResponseBody) GetUpdatedAt() string {
	if d == nil {
		return ""
	}
	return d.UpdatedAt
}

func (d *DocumentUpdateResponseBody) GetCompletedAt() *string {
	if d == nil {
		return nil
	}
	return d.CompletedAt
}

func (d *DocumentUpdateResponseBody) GetDeletedAt() *string {
	if d == nil {
		return nil
	}
	return d.DeletedAt
}

func (d *DocumentUpdateResponseBody) GetTeamID() float64 {
	if d == nil {
		return 0.0
	}
	return d.TeamID
}

func (d *DocumentUpdateResponseBody) GetFolderID() *string {
	if d == nil {
		return nil
	}
	return d.FolderID
}

func (d *DocumentUpdateResponseBody) GetUseLegacyFieldInsertion() bool {
	if d == nil {
		return false
	}
	return d.UseLegacyFieldInsertion
}

func (d *DocumentUpdateResponseBody) GetEnvelopeID() string {
	if d == nil {
		return ""
	}
	return d.EnvelopeID
}

func (d *DocumentUpdateResponseBody) GetInternalVersion() float64 {
	if d == nil {
		return 0.0
	}
	return d.InternalVersion
}

func (d *DocumentUpdateResponseBody) GetDocumentDataID() *string {
	if d == nil {
		return nil
	}
	return d.DocumentDataID
}

func (d *DocumentUpdateResponseBody) GetTemplateID() *float64 {
	if d == nil {
		return nil
	}
	return d.TemplateID
}

type DocumentUpdateResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful response
	Object *DocumentUpdateResponseBody
}

func (d *DocumentUpdateResponse) GetHTTPMeta() components.HTTPMetadata {
	if d == nil {
		return components.HTTPMetadata{}
	}
	return d.HTTPMeta
}

func (d *DocumentUpdateResponse) GetObject() *DocumentUpdateResponseBody {
	if d == nil {
		return nil
	}
	return d.Object
}
