// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/documenso/sdk-go/internal/utils"
	"github.com/documenso/sdk-go/models/components"
)

type TypeTemplateID string

const (
	TypeTemplateIDTemplateID TypeTemplateID = "templateId"
)

func (e TypeTemplateID) ToPointer() *TypeTemplateID {
	return &e
}
func (e *TypeTemplateID) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "templateId":
		*e = TypeTemplateID(v)
		return nil
	default:
		return fmt.Errorf("invalid value for TypeTemplateID: %v", v)
	}
}

type IdsTemplateID struct {
	Type TypeTemplateID `json:"type"`
	Ids  []float64      `json:"ids"`
}

func (i IdsTemplateID) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *IdsTemplateID) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, []string{"type", "ids"}); err != nil {
		return err
	}
	return nil
}

func (i *IdsTemplateID) GetType() TypeTemplateID {
	if i == nil {
		return TypeTemplateID("")
	}
	return i.Type
}

func (i *IdsTemplateID) GetIds() []float64 {
	if i == nil {
		return []float64{}
	}
	return i.Ids
}

type TypeDocumentID string

const (
	TypeDocumentIDDocumentID TypeDocumentID = "documentId"
)

func (e TypeDocumentID) ToPointer() *TypeDocumentID {
	return &e
}
func (e *TypeDocumentID) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "documentId":
		*e = TypeDocumentID(v)
		return nil
	default:
		return fmt.Errorf("invalid value for TypeDocumentID: %v", v)
	}
}

type IdsDocumentID struct {
	Type TypeDocumentID `json:"type"`
	Ids  []float64      `json:"ids"`
}

func (i IdsDocumentID) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *IdsDocumentID) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, []string{"type", "ids"}); err != nil {
		return err
	}
	return nil
}

func (i *IdsDocumentID) GetType() TypeDocumentID {
	if i == nil {
		return TypeDocumentID("")
	}
	return i.Type
}

func (i *IdsDocumentID) GetIds() []float64 {
	if i == nil {
		return []float64{}
	}
	return i.Ids
}

type TypeEnvelopeID string

const (
	TypeEnvelopeIDEnvelopeID TypeEnvelopeID = "envelopeId"
)

func (e TypeEnvelopeID) ToPointer() *TypeEnvelopeID {
	return &e
}
func (e *TypeEnvelopeID) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "envelopeId":
		*e = TypeEnvelopeID(v)
		return nil
	default:
		return fmt.Errorf("invalid value for TypeEnvelopeID: %v", v)
	}
}

type IdsEnvelopeID struct {
	Type TypeEnvelopeID `json:"type"`
	Ids  []string       `json:"ids"`
}

func (i IdsEnvelopeID) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(i, "", false)
}

func (i *IdsEnvelopeID) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &i, "", false, []string{"type", "ids"}); err != nil {
		return err
	}
	return nil
}

func (i *IdsEnvelopeID) GetType() TypeEnvelopeID {
	if i == nil {
		return TypeEnvelopeID("")
	}
	return i.Type
}

func (i *IdsEnvelopeID) GetIds() []string {
	if i == nil {
		return []string{}
	}
	return i.Ids
}

type IdsType string

const (
	IdsTypeIdsEnvelopeID IdsType = "ids_EnvelopeID"
	IdsTypeIdsDocumentID IdsType = "ids_DocumentID"
	IdsTypeIdsTemplateID IdsType = "ids_TemplateID"
)

type Ids struct {
	IdsEnvelopeID *IdsEnvelopeID `queryParam:"inline" union:"member"`
	IdsDocumentID *IdsDocumentID `queryParam:"inline" union:"member"`
	IdsTemplateID *IdsTemplateID `queryParam:"inline" union:"member"`

	Type IdsType
}

func CreateIdsIdsEnvelopeID(idsEnvelopeID IdsEnvelopeID) Ids {
	typ := IdsTypeIdsEnvelopeID

	return Ids{
		IdsEnvelopeID: &idsEnvelopeID,
		Type:          typ,
	}
}

func CreateIdsIdsDocumentID(idsDocumentID IdsDocumentID) Ids {
	typ := IdsTypeIdsDocumentID

	return Ids{
		IdsDocumentID: &idsDocumentID,
		Type:          typ,
	}
}

func CreateIdsIdsTemplateID(idsTemplateID IdsTemplateID) Ids {
	typ := IdsTypeIdsTemplateID

	return Ids{
		IdsTemplateID: &idsTemplateID,
		Type:          typ,
	}
}

func (u *Ids) UnmarshalJSON(data []byte) error {

	var idsEnvelopeID IdsEnvelopeID = IdsEnvelopeID{}
	if err := utils.UnmarshalJSON(data, &idsEnvelopeID, "", true, nil); err == nil {
		u.IdsEnvelopeID = &idsEnvelopeID
		u.Type = IdsTypeIdsEnvelopeID
		return nil
	}

	var idsDocumentID IdsDocumentID = IdsDocumentID{}
	if err := utils.UnmarshalJSON(data, &idsDocumentID, "", true, nil); err == nil {
		u.IdsDocumentID = &idsDocumentID
		u.Type = IdsTypeIdsDocumentID
		return nil
	}

	var idsTemplateID IdsTemplateID = IdsTemplateID{}
	if err := utils.UnmarshalJSON(data, &idsTemplateID, "", true, nil); err == nil {
		u.IdsTemplateID = &idsTemplateID
		u.Type = IdsTypeIdsTemplateID
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for Ids", string(data))
}

func (u Ids) MarshalJSON() ([]byte, error) {
	if u.IdsEnvelopeID != nil {
		return utils.MarshalJSON(u.IdsEnvelopeID, "", true)
	}

	if u.IdsDocumentID != nil {
		return utils.MarshalJSON(u.IdsDocumentID, "", true)
	}

	if u.IdsTemplateID != nil {
		return utils.MarshalJSON(u.IdsTemplateID, "", true)
	}

	return nil, errors.New("could not marshal union type Ids: all fields are null")
}

type EnvelopeGetManyRequest struct {
	Ids Ids `json:"ids"`
}

func (e *EnvelopeGetManyRequest) GetIds() Ids {
	if e == nil {
		return Ids{}
	}
	return e.Ids
}

type EnvelopeGetManyDataType string

const (
	EnvelopeGetManyDataTypeDocument EnvelopeGetManyDataType = "DOCUMENT"
	EnvelopeGetManyDataTypeTemplate EnvelopeGetManyDataType = "TEMPLATE"
)

func (e EnvelopeGetManyDataType) ToPointer() *EnvelopeGetManyDataType {
	return &e
}
func (e *EnvelopeGetManyDataType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "DOCUMENT":
		fallthrough
	case "TEMPLATE":
		*e = EnvelopeGetManyDataType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for EnvelopeGetManyDataType: %v", v)
	}
}

type EnvelopeGetManyStatus string

const (
	EnvelopeGetManyStatusDraft     EnvelopeGetManyStatus = "DRAFT"
	EnvelopeGetManyStatusPending   EnvelopeGetManyStatus = "PENDING"
	EnvelopeGetManyStatusCompleted EnvelopeGetManyStatus = "COMPLETED"
	EnvelopeGetManyStatusRejected  EnvelopeGetManyStatus = "REJECTED"
)

func (e EnvelopeGetManyStatus) ToPointer() *EnvelopeGetManyStatus {
	return &e
}
func (e *EnvelopeGetManyStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "DRAFT":
		fallthrough
	case "PENDING":
		fallthrough
	case "COMPLETED":
		fallthrough
	case "REJECTED":
		*e = EnvelopeGetManyStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for EnvelopeGetManyStatus: %v", v)
	}
}

type EnvelopeGetManySource string

const (
	EnvelopeGetManySourceDocument           EnvelopeGetManySource = "DOCUMENT"
	EnvelopeGetManySourceTemplate           EnvelopeGetManySource = "TEMPLATE"
	EnvelopeGetManySourceTemplateDirectLink EnvelopeGetManySource = "TEMPLATE_DIRECT_LINK"
)

func (e EnvelopeGetManySource) ToPointer() *EnvelopeGetManySource {
	return &e
}
func (e *EnvelopeGetManySource) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "DOCUMENT":
		fallthrough
	case "TEMPLATE":
		fallthrough
	case "TEMPLATE_DIRECT_LINK":
		*e = EnvelopeGetManySource(v)
		return nil
	default:
		return fmt.Errorf("invalid value for EnvelopeGetManySource: %v", v)
	}
}

type EnvelopeGetManyVisibility string

const (
	EnvelopeGetManyVisibilityEveryone        EnvelopeGetManyVisibility = "EVERYONE"
	EnvelopeGetManyVisibilityManagerAndAbove EnvelopeGetManyVisibility = "MANAGER_AND_ABOVE"
	EnvelopeGetManyVisibilityAdmin           EnvelopeGetManyVisibility = "ADMIN"
)

func (e EnvelopeGetManyVisibility) ToPointer() *EnvelopeGetManyVisibility {
	return &e
}
func (e *EnvelopeGetManyVisibility) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "EVERYONE":
		fallthrough
	case "MANAGER_AND_ABOVE":
		fallthrough
	case "ADMIN":
		*e = EnvelopeGetManyVisibility(v)
		return nil
	default:
		return fmt.Errorf("invalid value for EnvelopeGetManyVisibility: %v", v)
	}
}

type EnvelopeGetManyTemplateType string

const (
	EnvelopeGetManyTemplateTypePublic  EnvelopeGetManyTemplateType = "PUBLIC"
	EnvelopeGetManyTemplateTypePrivate EnvelopeGetManyTemplateType = "PRIVATE"
)

func (e EnvelopeGetManyTemplateType) ToPointer() *EnvelopeGetManyTemplateType {
	return &e
}
func (e *EnvelopeGetManyTemplateType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "PUBLIC":
		fallthrough
	case "PRIVATE":
		*e = EnvelopeGetManyTemplateType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for EnvelopeGetManyTemplateType: %v", v)
	}
}

type EnvelopeGetManyGlobalAccessAuth string

const (
	EnvelopeGetManyGlobalAccessAuthAccount       EnvelopeGetManyGlobalAccessAuth = "ACCOUNT"
	EnvelopeGetManyGlobalAccessAuthTwoFactorAuth EnvelopeGetManyGlobalAccessAuth = "TWO_FACTOR_AUTH"
)

func (e EnvelopeGetManyGlobalAccessAuth) ToPointer() *EnvelopeGetManyGlobalAccessAuth {
	return &e
}
func (e *EnvelopeGetManyGlobalAccessAuth) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "ACCOUNT":
		fallthrough
	case "TWO_FACTOR_AUTH":
		*e = EnvelopeGetManyGlobalAccessAuth(v)
		return nil
	default:
		return fmt.Errorf("invalid value for EnvelopeGetManyGlobalAccessAuth: %v", v)
	}
}

type EnvelopeGetManyGlobalActionAuth string

const (
	EnvelopeGetManyGlobalActionAuthAccount       EnvelopeGetManyGlobalActionAuth = "ACCOUNT"
	EnvelopeGetManyGlobalActionAuthPasskey       EnvelopeGetManyGlobalActionAuth = "PASSKEY"
	EnvelopeGetManyGlobalActionAuthTwoFactorAuth EnvelopeGetManyGlobalActionAuth = "TWO_FACTOR_AUTH"
	EnvelopeGetManyGlobalActionAuthPassword      EnvelopeGetManyGlobalActionAuth = "PASSWORD"
)

func (e EnvelopeGetManyGlobalActionAuth) ToPointer() *EnvelopeGetManyGlobalActionAuth {
	return &e
}
func (e *EnvelopeGetManyGlobalActionAuth) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "ACCOUNT":
		fallthrough
	case "PASSKEY":
		fallthrough
	case "TWO_FACTOR_AUTH":
		fallthrough
	case "PASSWORD":
		*e = EnvelopeGetManyGlobalActionAuth(v)
		return nil
	default:
		return fmt.Errorf("invalid value for EnvelopeGetManyGlobalActionAuth: %v", v)
	}
}

type EnvelopeGetManyAuthOptions struct {
	GlobalAccessAuth []EnvelopeGetManyGlobalAccessAuth `json:"globalAccessAuth"`
	GlobalActionAuth []EnvelopeGetManyGlobalActionAuth `json:"globalActionAuth"`
}

func (e *EnvelopeGetManyAuthOptions) GetGlobalAccessAuth() []EnvelopeGetManyGlobalAccessAuth {
	if e == nil {
		return []EnvelopeGetManyGlobalAccessAuth{}
	}
	return e.GlobalAccessAuth
}

func (e *EnvelopeGetManyAuthOptions) GetGlobalActionAuth() []EnvelopeGetManyGlobalActionAuth {
	if e == nil {
		return []EnvelopeGetManyGlobalActionAuth{}
	}
	return e.GlobalActionAuth
}

type EnvelopeGetManyFormValuesType string

const (
	EnvelopeGetManyFormValuesTypeStr     EnvelopeGetManyFormValuesType = "str"
	EnvelopeGetManyFormValuesTypeBoolean EnvelopeGetManyFormValuesType = "boolean"
	EnvelopeGetManyFormValuesTypeNumber  EnvelopeGetManyFormValuesType = "number"
)

type EnvelopeGetManyFormValues struct {
	Str     *string  `queryParam:"inline" union:"member"`
	Boolean *bool    `queryParam:"inline" union:"member"`
	Number  *float64 `queryParam:"inline" union:"member"`

	Type EnvelopeGetManyFormValuesType
}

func CreateEnvelopeGetManyFormValuesStr(str string) EnvelopeGetManyFormValues {
	typ := EnvelopeGetManyFormValuesTypeStr

	return EnvelopeGetManyFormValues{
		Str:  &str,
		Type: typ,
	}
}

func CreateEnvelopeGetManyFormValuesBoolean(boolean bool) EnvelopeGetManyFormValues {
	typ := EnvelopeGetManyFormValuesTypeBoolean

	return EnvelopeGetManyFormValues{
		Boolean: &boolean,
		Type:    typ,
	}
}

func CreateEnvelopeGetManyFormValuesNumber(number float64) EnvelopeGetManyFormValues {
	typ := EnvelopeGetManyFormValuesTypeNumber

	return EnvelopeGetManyFormValues{
		Number: &number,
		Type:   typ,
	}
}

func (u *EnvelopeGetManyFormValues) UnmarshalJSON(data []byte) error {

	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, nil); err == nil {
		u.Str = &str
		u.Type = EnvelopeGetManyFormValuesTypeStr
		return nil
	}

	var boolean bool = false
	if err := utils.UnmarshalJSON(data, &boolean, "", true, nil); err == nil {
		u.Boolean = &boolean
		u.Type = EnvelopeGetManyFormValuesTypeBoolean
		return nil
	}

	var number float64 = float64(0)
	if err := utils.UnmarshalJSON(data, &number, "", true, nil); err == nil {
		u.Number = &number
		u.Type = EnvelopeGetManyFormValuesTypeNumber
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for EnvelopeGetManyFormValues", string(data))
}

func (u EnvelopeGetManyFormValues) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.Boolean != nil {
		return utils.MarshalJSON(u.Boolean, "", true)
	}

	if u.Number != nil {
		return utils.MarshalJSON(u.Number, "", true)
	}

	return nil, errors.New("could not marshal union type EnvelopeGetManyFormValues: all fields are null")
}

type EnvelopeGetManySigningOrder string

const (
	EnvelopeGetManySigningOrderParallel   EnvelopeGetManySigningOrder = "PARALLEL"
	EnvelopeGetManySigningOrderSequential EnvelopeGetManySigningOrder = "SEQUENTIAL"
)

func (e EnvelopeGetManySigningOrder) ToPointer() *EnvelopeGetManySigningOrder {
	return &e
}
func (e *EnvelopeGetManySigningOrder) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "PARALLEL":
		fallthrough
	case "SEQUENTIAL":
		*e = EnvelopeGetManySigningOrder(v)
		return nil
	default:
		return fmt.Errorf("invalid value for EnvelopeGetManySigningOrder: %v", v)
	}
}

type EnvelopeGetManyDistributionMethod string

const (
	EnvelopeGetManyDistributionMethodEmail EnvelopeGetManyDistributionMethod = "EMAIL"
	EnvelopeGetManyDistributionMethodNone  EnvelopeGetManyDistributionMethod = "NONE"
)

func (e EnvelopeGetManyDistributionMethod) ToPointer() *EnvelopeGetManyDistributionMethod {
	return &e
}
func (e *EnvelopeGetManyDistributionMethod) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "EMAIL":
		fallthrough
	case "NONE":
		*e = EnvelopeGetManyDistributionMethod(v)
		return nil
	default:
		return fmt.Errorf("invalid value for EnvelopeGetManyDistributionMethod: %v", v)
	}
}

type EnvelopeGetManyEmailSettings struct {
	RecipientSigningRequest *bool `default:"true" json:"recipientSigningRequest"`
	RecipientRemoved        *bool `default:"true" json:"recipientRemoved"`
	RecipientSigned         *bool `default:"true" json:"recipientSigned"`
	DocumentPending         *bool `default:"true" json:"documentPending"`
	DocumentCompleted       *bool `default:"true" json:"documentCompleted"`
	DocumentDeleted         *bool `default:"true" json:"documentDeleted"`
	OwnerDocumentCompleted  *bool `default:"true" json:"ownerDocumentCompleted"`
}

func (e EnvelopeGetManyEmailSettings) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *EnvelopeGetManyEmailSettings) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (e *EnvelopeGetManyEmailSettings) GetRecipientSigningRequest() *bool {
	if e == nil {
		return nil
	}
	return e.RecipientSigningRequest
}

func (e *EnvelopeGetManyEmailSettings) GetRecipientRemoved() *bool {
	if e == nil {
		return nil
	}
	return e.RecipientRemoved
}

func (e *EnvelopeGetManyEmailSettings) GetRecipientSigned() *bool {
	if e == nil {
		return nil
	}
	return e.RecipientSigned
}

func (e *EnvelopeGetManyEmailSettings) GetDocumentPending() *bool {
	if e == nil {
		return nil
	}
	return e.DocumentPending
}

func (e *EnvelopeGetManyEmailSettings) GetDocumentCompleted() *bool {
	if e == nil {
		return nil
	}
	return e.DocumentCompleted
}

func (e *EnvelopeGetManyEmailSettings) GetDocumentDeleted() *bool {
	if e == nil {
		return nil
	}
	return e.DocumentDeleted
}

func (e *EnvelopeGetManyEmailSettings) GetOwnerDocumentCompleted() *bool {
	if e == nil {
		return nil
	}
	return e.OwnerDocumentCompleted
}

type EnvelopeGetManyDocumentMeta struct {
	SigningOrder           EnvelopeGetManySigningOrder       `json:"signingOrder"`
	DistributionMethod     EnvelopeGetManyDistributionMethod `json:"distributionMethod"`
	ID                     string                            `json:"id"`
	Subject                *string                           `json:"subject"`
	Message                *string                           `json:"message"`
	Timezone               *string                           `json:"timezone"`
	DateFormat             *string                           `json:"dateFormat"`
	RedirectURL            *string                           `json:"redirectUrl"`
	TypedSignatureEnabled  bool                              `json:"typedSignatureEnabled"`
	UploadSignatureEnabled bool                              `json:"uploadSignatureEnabled"`
	DrawSignatureEnabled   bool                              `json:"drawSignatureEnabled"`
	AllowDictateNextSigner bool                              `json:"allowDictateNextSigner"`
	Language               string                            `json:"language"`
	EmailSettings          *EnvelopeGetManyEmailSettings     `json:"emailSettings"`
	EmailID                *string                           `json:"emailId"`
	EmailReplyTo           *string                           `json:"emailReplyTo"`
}

func (e *EnvelopeGetManyDocumentMeta) GetSigningOrder() EnvelopeGetManySigningOrder {
	if e == nil {
		return EnvelopeGetManySigningOrder("")
	}
	return e.SigningOrder
}

func (e *EnvelopeGetManyDocumentMeta) GetDistributionMethod() EnvelopeGetManyDistributionMethod {
	if e == nil {
		return EnvelopeGetManyDistributionMethod("")
	}
	return e.DistributionMethod
}

func (e *EnvelopeGetManyDocumentMeta) GetID() string {
	if e == nil {
		return ""
	}
	return e.ID
}

func (e *EnvelopeGetManyDocumentMeta) GetSubject() *string {
	if e == nil {
		return nil
	}
	return e.Subject
}

func (e *EnvelopeGetManyDocumentMeta) GetMessage() *string {
	if e == nil {
		return nil
	}
	return e.Message
}

func (e *EnvelopeGetManyDocumentMeta) GetTimezone() *string {
	if e == nil {
		return nil
	}
	return e.Timezone
}

func (e *EnvelopeGetManyDocumentMeta) GetDateFormat() *string {
	if e == nil {
		return nil
	}
	return e.DateFormat
}

func (e *EnvelopeGetManyDocumentMeta) GetRedirectURL() *string {
	if e == nil {
		return nil
	}
	return e.RedirectURL
}

func (e *EnvelopeGetManyDocumentMeta) GetTypedSignatureEnabled() bool {
	if e == nil {
		return false
	}
	return e.TypedSignatureEnabled
}

func (e *EnvelopeGetManyDocumentMeta) GetUploadSignatureEnabled() bool {
	if e == nil {
		return false
	}
	return e.UploadSignatureEnabled
}

func (e *EnvelopeGetManyDocumentMeta) GetDrawSignatureEnabled() bool {
	if e == nil {
		return false
	}
	return e.DrawSignatureEnabled
}

func (e *EnvelopeGetManyDocumentMeta) GetAllowDictateNextSigner() bool {
	if e == nil {
		return false
	}
	return e.AllowDictateNextSigner
}

func (e *EnvelopeGetManyDocumentMeta) GetLanguage() string {
	if e == nil {
		return ""
	}
	return e.Language
}

func (e *EnvelopeGetManyDocumentMeta) GetEmailSettings() *EnvelopeGetManyEmailSettings {
	if e == nil {
		return nil
	}
	return e.EmailSettings
}

func (e *EnvelopeGetManyDocumentMeta) GetEmailID() *string {
	if e == nil {
		return nil
	}
	return e.EmailID
}

func (e *EnvelopeGetManyDocumentMeta) GetEmailReplyTo() *string {
	if e == nil {
		return nil
	}
	return e.EmailReplyTo
}

type EnvelopeGetManyRole string

const (
	EnvelopeGetManyRoleCc        EnvelopeGetManyRole = "CC"
	EnvelopeGetManyRoleSigner    EnvelopeGetManyRole = "SIGNER"
	EnvelopeGetManyRoleViewer    EnvelopeGetManyRole = "VIEWER"
	EnvelopeGetManyRoleApprover  EnvelopeGetManyRole = "APPROVER"
	EnvelopeGetManyRoleAssistant EnvelopeGetManyRole = "ASSISTANT"
)

func (e EnvelopeGetManyRole) ToPointer() *EnvelopeGetManyRole {
	return &e
}
func (e *EnvelopeGetManyRole) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "CC":
		fallthrough
	case "SIGNER":
		fallthrough
	case "VIEWER":
		fallthrough
	case "APPROVER":
		fallthrough
	case "ASSISTANT":
		*e = EnvelopeGetManyRole(v)
		return nil
	default:
		return fmt.Errorf("invalid value for EnvelopeGetManyRole: %v", v)
	}
}

type EnvelopeGetManyReadStatus string

const (
	EnvelopeGetManyReadStatusNotOpened EnvelopeGetManyReadStatus = "NOT_OPENED"
	EnvelopeGetManyReadStatusOpened    EnvelopeGetManyReadStatus = "OPENED"
)

func (e EnvelopeGetManyReadStatus) ToPointer() *EnvelopeGetManyReadStatus {
	return &e
}
func (e *EnvelopeGetManyReadStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "NOT_OPENED":
		fallthrough
	case "OPENED":
		*e = EnvelopeGetManyReadStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for EnvelopeGetManyReadStatus: %v", v)
	}
}

type EnvelopeGetManySigningStatus string

const (
	EnvelopeGetManySigningStatusNotSigned EnvelopeGetManySigningStatus = "NOT_SIGNED"
	EnvelopeGetManySigningStatusSigned    EnvelopeGetManySigningStatus = "SIGNED"
	EnvelopeGetManySigningStatusRejected  EnvelopeGetManySigningStatus = "REJECTED"
)

func (e EnvelopeGetManySigningStatus) ToPointer() *EnvelopeGetManySigningStatus {
	return &e
}
func (e *EnvelopeGetManySigningStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "NOT_SIGNED":
		fallthrough
	case "SIGNED":
		fallthrough
	case "REJECTED":
		*e = EnvelopeGetManySigningStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for EnvelopeGetManySigningStatus: %v", v)
	}
}

type EnvelopeGetManySendStatus string

const (
	EnvelopeGetManySendStatusNotSent EnvelopeGetManySendStatus = "NOT_SENT"
	EnvelopeGetManySendStatusSent    EnvelopeGetManySendStatus = "SENT"
)

func (e EnvelopeGetManySendStatus) ToPointer() *EnvelopeGetManySendStatus {
	return &e
}
func (e *EnvelopeGetManySendStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "NOT_SENT":
		fallthrough
	case "SENT":
		*e = EnvelopeGetManySendStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for EnvelopeGetManySendStatus: %v", v)
	}
}

type EnvelopeGetManyAccessAuth string

const (
	EnvelopeGetManyAccessAuthAccount       EnvelopeGetManyAccessAuth = "ACCOUNT"
	EnvelopeGetManyAccessAuthTwoFactorAuth EnvelopeGetManyAccessAuth = "TWO_FACTOR_AUTH"
)

func (e EnvelopeGetManyAccessAuth) ToPointer() *EnvelopeGetManyAccessAuth {
	return &e
}
func (e *EnvelopeGetManyAccessAuth) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "ACCOUNT":
		fallthrough
	case "TWO_FACTOR_AUTH":
		*e = EnvelopeGetManyAccessAuth(v)
		return nil
	default:
		return fmt.Errorf("invalid value for EnvelopeGetManyAccessAuth: %v", v)
	}
}

type EnvelopeGetManyActionAuth string

const (
	EnvelopeGetManyActionAuthAccount       EnvelopeGetManyActionAuth = "ACCOUNT"
	EnvelopeGetManyActionAuthPasskey       EnvelopeGetManyActionAuth = "PASSKEY"
	EnvelopeGetManyActionAuthTwoFactorAuth EnvelopeGetManyActionAuth = "TWO_FACTOR_AUTH"
	EnvelopeGetManyActionAuthPassword      EnvelopeGetManyActionAuth = "PASSWORD"
	EnvelopeGetManyActionAuthExplicitNone  EnvelopeGetManyActionAuth = "EXPLICIT_NONE"
)

func (e EnvelopeGetManyActionAuth) ToPointer() *EnvelopeGetManyActionAuth {
	return &e
}
func (e *EnvelopeGetManyActionAuth) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "ACCOUNT":
		fallthrough
	case "PASSKEY":
		fallthrough
	case "TWO_FACTOR_AUTH":
		fallthrough
	case "PASSWORD":
		fallthrough
	case "EXPLICIT_NONE":
		*e = EnvelopeGetManyActionAuth(v)
		return nil
	default:
		return fmt.Errorf("invalid value for EnvelopeGetManyActionAuth: %v", v)
	}
}

type EnvelopeGetManyRecipientAuthOptions struct {
	AccessAuth []EnvelopeGetManyAccessAuth `json:"accessAuth"`
	ActionAuth []EnvelopeGetManyActionAuth `json:"actionAuth"`
}

func (e *EnvelopeGetManyRecipientAuthOptions) GetAccessAuth() []EnvelopeGetManyAccessAuth {
	if e == nil {
		return []EnvelopeGetManyAccessAuth{}
	}
	return e.AccessAuth
}

func (e *EnvelopeGetManyRecipientAuthOptions) GetActionAuth() []EnvelopeGetManyActionAuth {
	if e == nil {
		return []EnvelopeGetManyActionAuth{}
	}
	return e.ActionAuth
}

type EnvelopeGetManyRecipient struct {
	EnvelopeID        string                               `json:"envelopeId"`
	Role              EnvelopeGetManyRole                  `json:"role"`
	ReadStatus        EnvelopeGetManyReadStatus            `json:"readStatus"`
	SigningStatus     EnvelopeGetManySigningStatus         `json:"signingStatus"`
	SendStatus        EnvelopeGetManySendStatus            `json:"sendStatus"`
	ID                float64                              `json:"id"`
	Email             string                               `json:"email"`
	Name              string                               `json:"name"`
	Token             string                               `json:"token"`
	DocumentDeletedAt *string                              `json:"documentDeletedAt"`
	Expired           *string                              `json:"expired"`
	SignedAt          *string                              `json:"signedAt"`
	AuthOptions       *EnvelopeGetManyRecipientAuthOptions `json:"authOptions"`
	SigningOrder      *float64                             `json:"signingOrder"`
	RejectionReason   *string                              `json:"rejectionReason"`
}

func (e *EnvelopeGetManyRecipient) GetEnvelopeID() string {
	if e == nil {
		return ""
	}
	return e.EnvelopeID
}

func (e *EnvelopeGetManyRecipient) GetRole() EnvelopeGetManyRole {
	if e == nil {
		return EnvelopeGetManyRole("")
	}
	return e.Role
}

func (e *EnvelopeGetManyRecipient) GetReadStatus() EnvelopeGetManyReadStatus {
	if e == nil {
		return EnvelopeGetManyReadStatus("")
	}
	return e.ReadStatus
}

func (e *EnvelopeGetManyRecipient) GetSigningStatus() EnvelopeGetManySigningStatus {
	if e == nil {
		return EnvelopeGetManySigningStatus("")
	}
	return e.SigningStatus
}

func (e *EnvelopeGetManyRecipient) GetSendStatus() EnvelopeGetManySendStatus {
	if e == nil {
		return EnvelopeGetManySendStatus("")
	}
	return e.SendStatus
}

func (e *EnvelopeGetManyRecipient) GetID() float64 {
	if e == nil {
		return 0.0
	}
	return e.ID
}

func (e *EnvelopeGetManyRecipient) GetEmail() string {
	if e == nil {
		return ""
	}
	return e.Email
}

func (e *EnvelopeGetManyRecipient) GetName() string {
	if e == nil {
		return ""
	}
	return e.Name
}

func (e *EnvelopeGetManyRecipient) GetToken() string {
	if e == nil {
		return ""
	}
	return e.Token
}

func (e *EnvelopeGetManyRecipient) GetDocumentDeletedAt() *string {
	if e == nil {
		return nil
	}
	return e.DocumentDeletedAt
}

func (e *EnvelopeGetManyRecipient) GetExpired() *string {
	if e == nil {
		return nil
	}
	return e.Expired
}

func (e *EnvelopeGetManyRecipient) GetSignedAt() *string {
	if e == nil {
		return nil
	}
	return e.SignedAt
}

func (e *EnvelopeGetManyRecipient) GetAuthOptions() *EnvelopeGetManyRecipientAuthOptions {
	if e == nil {
		return nil
	}
	return e.AuthOptions
}

func (e *EnvelopeGetManyRecipient) GetSigningOrder() *float64 {
	if e == nil {
		return nil
	}
	return e.SigningOrder
}

func (e *EnvelopeGetManyRecipient) GetRejectionReason() *string {
	if e == nil {
		return nil
	}
	return e.RejectionReason
}

type EnvelopeGetManyFieldType string

const (
	EnvelopeGetManyFieldTypeSignature     EnvelopeGetManyFieldType = "SIGNATURE"
	EnvelopeGetManyFieldTypeFreeSignature EnvelopeGetManyFieldType = "FREE_SIGNATURE"
	EnvelopeGetManyFieldTypeInitials      EnvelopeGetManyFieldType = "INITIALS"
	EnvelopeGetManyFieldTypeName          EnvelopeGetManyFieldType = "NAME"
	EnvelopeGetManyFieldTypeEmail         EnvelopeGetManyFieldType = "EMAIL"
	EnvelopeGetManyFieldTypeDate          EnvelopeGetManyFieldType = "DATE"
	EnvelopeGetManyFieldTypeText          EnvelopeGetManyFieldType = "TEXT"
	EnvelopeGetManyFieldTypeNumber        EnvelopeGetManyFieldType = "NUMBER"
	EnvelopeGetManyFieldTypeRadio         EnvelopeGetManyFieldType = "RADIO"
	EnvelopeGetManyFieldTypeCheckbox      EnvelopeGetManyFieldType = "CHECKBOX"
	EnvelopeGetManyFieldTypeDropdown      EnvelopeGetManyFieldType = "DROPDOWN"
)

func (e EnvelopeGetManyFieldType) ToPointer() *EnvelopeGetManyFieldType {
	return &e
}
func (e *EnvelopeGetManyFieldType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "SIGNATURE":
		fallthrough
	case "FREE_SIGNATURE":
		fallthrough
	case "INITIALS":
		fallthrough
	case "NAME":
		fallthrough
	case "EMAIL":
		fallthrough
	case "DATE":
		fallthrough
	case "TEXT":
		fallthrough
	case "NUMBER":
		fallthrough
	case "RADIO":
		fallthrough
	case "CHECKBOX":
		fallthrough
	case "DROPDOWN":
		*e = EnvelopeGetManyFieldType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for EnvelopeGetManyFieldType: %v", v)
	}
}

type EnvelopeGetManyTypeDropdown string

const (
	EnvelopeGetManyTypeDropdownDropdown EnvelopeGetManyTypeDropdown = "dropdown"
)

func (e EnvelopeGetManyTypeDropdown) ToPointer() *EnvelopeGetManyTypeDropdown {
	return &e
}
func (e *EnvelopeGetManyTypeDropdown) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "dropdown":
		*e = EnvelopeGetManyTypeDropdown(v)
		return nil
	default:
		return fmt.Errorf("invalid value for EnvelopeGetManyTypeDropdown: %v", v)
	}
}

type EnvelopeGetManyValue3 struct {
	Value string `json:"value"`
}

func (e EnvelopeGetManyValue3) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *EnvelopeGetManyValue3) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, []string{"value"}); err != nil {
		return err
	}
	return nil
}

func (e *EnvelopeGetManyValue3) GetValue() string {
	if e == nil {
		return ""
	}
	return e.Value
}

type EnvelopeGetManyFieldMetaDropdown struct {
	Label        *string                     `json:"label,omitempty"`
	Placeholder  *string                     `json:"placeholder,omitempty"`
	Required     *bool                       `json:"required,omitempty"`
	ReadOnly     *bool                       `json:"readOnly,omitempty"`
	FontSize     *float64                    `default:"12" json:"fontSize"`
	Type         EnvelopeGetManyTypeDropdown `json:"type"`
	Values       []EnvelopeGetManyValue3     `json:"values,omitempty"`
	DefaultValue *string                     `json:"defaultValue,omitempty"`
}

func (e EnvelopeGetManyFieldMetaDropdown) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *EnvelopeGetManyFieldMetaDropdown) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, []string{"type"}); err != nil {
		return err
	}
	return nil
}

func (e *EnvelopeGetManyFieldMetaDropdown) GetLabel() *string {
	if e == nil {
		return nil
	}
	return e.Label
}

func (e *EnvelopeGetManyFieldMetaDropdown) GetPlaceholder() *string {
	if e == nil {
		return nil
	}
	return e.Placeholder
}

func (e *EnvelopeGetManyFieldMetaDropdown) GetRequired() *bool {
	if e == nil {
		return nil
	}
	return e.Required
}

func (e *EnvelopeGetManyFieldMetaDropdown) GetReadOnly() *bool {
	if e == nil {
		return nil
	}
	return e.ReadOnly
}

func (e *EnvelopeGetManyFieldMetaDropdown) GetFontSize() *float64 {
	if e == nil {
		return nil
	}
	return e.FontSize
}

func (e *EnvelopeGetManyFieldMetaDropdown) GetType() EnvelopeGetManyTypeDropdown {
	if e == nil {
		return EnvelopeGetManyTypeDropdown("")
	}
	return e.Type
}

func (e *EnvelopeGetManyFieldMetaDropdown) GetValues() []EnvelopeGetManyValue3 {
	if e == nil {
		return nil
	}
	return e.Values
}

func (e *EnvelopeGetManyFieldMetaDropdown) GetDefaultValue() *string {
	if e == nil {
		return nil
	}
	return e.DefaultValue
}

type EnvelopeGetManyTypeCheckbox string

const (
	EnvelopeGetManyTypeCheckboxCheckbox EnvelopeGetManyTypeCheckbox = "checkbox"
)

func (e EnvelopeGetManyTypeCheckbox) ToPointer() *EnvelopeGetManyTypeCheckbox {
	return &e
}
func (e *EnvelopeGetManyTypeCheckbox) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "checkbox":
		*e = EnvelopeGetManyTypeCheckbox(v)
		return nil
	default:
		return fmt.Errorf("invalid value for EnvelopeGetManyTypeCheckbox: %v", v)
	}
}

type EnvelopeGetManyValue2 struct {
	ID      float64 `json:"id"`
	Checked bool    `json:"checked"`
	Value   string  `json:"value"`
}

func (e EnvelopeGetManyValue2) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *EnvelopeGetManyValue2) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, []string{"id", "checked", "value"}); err != nil {
		return err
	}
	return nil
}

func (e *EnvelopeGetManyValue2) GetID() float64 {
	if e == nil {
		return 0.0
	}
	return e.ID
}

func (e *EnvelopeGetManyValue2) GetChecked() bool {
	if e == nil {
		return false
	}
	return e.Checked
}

func (e *EnvelopeGetManyValue2) GetValue() string {
	if e == nil {
		return ""
	}
	return e.Value
}

type EnvelopeGetManyDirection2 string

const (
	EnvelopeGetManyDirection2Vertical   EnvelopeGetManyDirection2 = "vertical"
	EnvelopeGetManyDirection2Horizontal EnvelopeGetManyDirection2 = "horizontal"
)

func (e EnvelopeGetManyDirection2) ToPointer() *EnvelopeGetManyDirection2 {
	return &e
}
func (e *EnvelopeGetManyDirection2) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "vertical":
		fallthrough
	case "horizontal":
		*e = EnvelopeGetManyDirection2(v)
		return nil
	default:
		return fmt.Errorf("invalid value for EnvelopeGetManyDirection2: %v", v)
	}
}

type EnvelopeGetManyFieldMetaCheckbox struct {
	Label            *string                     `json:"label,omitempty"`
	Placeholder      *string                     `json:"placeholder,omitempty"`
	Required         *bool                       `json:"required,omitempty"`
	ReadOnly         *bool                       `json:"readOnly,omitempty"`
	FontSize         *float64                    `default:"12" json:"fontSize"`
	Type             EnvelopeGetManyTypeCheckbox `json:"type"`
	Values           []EnvelopeGetManyValue2     `json:"values,omitempty"`
	ValidationRule   *string                     `json:"validationRule,omitempty"`
	ValidationLength *float64                    `json:"validationLength,omitempty"`
	Direction        *EnvelopeGetManyDirection2  `default:"vertical" json:"direction"`
}

func (e EnvelopeGetManyFieldMetaCheckbox) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *EnvelopeGetManyFieldMetaCheckbox) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, []string{"type"}); err != nil {
		return err
	}
	return nil
}

func (e *EnvelopeGetManyFieldMetaCheckbox) GetLabel() *string {
	if e == nil {
		return nil
	}
	return e.Label
}

func (e *EnvelopeGetManyFieldMetaCheckbox) GetPlaceholder() *string {
	if e == nil {
		return nil
	}
	return e.Placeholder
}

func (e *EnvelopeGetManyFieldMetaCheckbox) GetRequired() *bool {
	if e == nil {
		return nil
	}
	return e.Required
}

func (e *EnvelopeGetManyFieldMetaCheckbox) GetReadOnly() *bool {
	if e == nil {
		return nil
	}
	return e.ReadOnly
}

func (e *EnvelopeGetManyFieldMetaCheckbox) GetFontSize() *float64 {
	if e == nil {
		return nil
	}
	return e.FontSize
}

func (e *EnvelopeGetManyFieldMetaCheckbox) GetType() EnvelopeGetManyTypeCheckbox {
	if e == nil {
		return EnvelopeGetManyTypeCheckbox("")
	}
	return e.Type
}

func (e *EnvelopeGetManyFieldMetaCheckbox) GetValues() []EnvelopeGetManyValue2 {
	if e == nil {
		return nil
	}
	return e.Values
}

func (e *EnvelopeGetManyFieldMetaCheckbox) GetValidationRule() *string {
	if e == nil {
		return nil
	}
	return e.ValidationRule
}

func (e *EnvelopeGetManyFieldMetaCheckbox) GetValidationLength() *float64 {
	if e == nil {
		return nil
	}
	return e.ValidationLength
}

func (e *EnvelopeGetManyFieldMetaCheckbox) GetDirection() *EnvelopeGetManyDirection2 {
	if e == nil {
		return nil
	}
	return e.Direction
}

type EnvelopeGetManyTypeRadio string

const (
	EnvelopeGetManyTypeRadioRadio EnvelopeGetManyTypeRadio = "radio"
)

func (e EnvelopeGetManyTypeRadio) ToPointer() *EnvelopeGetManyTypeRadio {
	return &e
}
func (e *EnvelopeGetManyTypeRadio) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "radio":
		*e = EnvelopeGetManyTypeRadio(v)
		return nil
	default:
		return fmt.Errorf("invalid value for EnvelopeGetManyTypeRadio: %v", v)
	}
}

type EnvelopeGetManyValue1 struct {
	ID      float64 `json:"id"`
	Checked bool    `json:"checked"`
	Value   string  `json:"value"`
}

func (e EnvelopeGetManyValue1) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *EnvelopeGetManyValue1) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, []string{"id", "checked", "value"}); err != nil {
		return err
	}
	return nil
}

func (e *EnvelopeGetManyValue1) GetID() float64 {
	if e == nil {
		return 0.0
	}
	return e.ID
}

func (e *EnvelopeGetManyValue1) GetChecked() bool {
	if e == nil {
		return false
	}
	return e.Checked
}

func (e *EnvelopeGetManyValue1) GetValue() string {
	if e == nil {
		return ""
	}
	return e.Value
}

type EnvelopeGetManyDirection1 string

const (
	EnvelopeGetManyDirection1Vertical   EnvelopeGetManyDirection1 = "vertical"
	EnvelopeGetManyDirection1Horizontal EnvelopeGetManyDirection1 = "horizontal"
)

func (e EnvelopeGetManyDirection1) ToPointer() *EnvelopeGetManyDirection1 {
	return &e
}
func (e *EnvelopeGetManyDirection1) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "vertical":
		fallthrough
	case "horizontal":
		*e = EnvelopeGetManyDirection1(v)
		return nil
	default:
		return fmt.Errorf("invalid value for EnvelopeGetManyDirection1: %v", v)
	}
}

type EnvelopeGetManyFieldMetaRadio struct {
	Label       *string                    `json:"label,omitempty"`
	Placeholder *string                    `json:"placeholder,omitempty"`
	Required    *bool                      `json:"required,omitempty"`
	ReadOnly    *bool                      `json:"readOnly,omitempty"`
	FontSize    *float64                   `default:"12" json:"fontSize"`
	Type        EnvelopeGetManyTypeRadio   `json:"type"`
	Values      []EnvelopeGetManyValue1    `json:"values,omitempty"`
	Direction   *EnvelopeGetManyDirection1 `default:"vertical" json:"direction"`
}

func (e EnvelopeGetManyFieldMetaRadio) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *EnvelopeGetManyFieldMetaRadio) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, []string{"type"}); err != nil {
		return err
	}
	return nil
}

func (e *EnvelopeGetManyFieldMetaRadio) GetLabel() *string {
	if e == nil {
		return nil
	}
	return e.Label
}

func (e *EnvelopeGetManyFieldMetaRadio) GetPlaceholder() *string {
	if e == nil {
		return nil
	}
	return e.Placeholder
}

func (e *EnvelopeGetManyFieldMetaRadio) GetRequired() *bool {
	if e == nil {
		return nil
	}
	return e.Required
}

func (e *EnvelopeGetManyFieldMetaRadio) GetReadOnly() *bool {
	if e == nil {
		return nil
	}
	return e.ReadOnly
}

func (e *EnvelopeGetManyFieldMetaRadio) GetFontSize() *float64 {
	if e == nil {
		return nil
	}
	return e.FontSize
}

func (e *EnvelopeGetManyFieldMetaRadio) GetType() EnvelopeGetManyTypeRadio {
	if e == nil {
		return EnvelopeGetManyTypeRadio("")
	}
	return e.Type
}

func (e *EnvelopeGetManyFieldMetaRadio) GetValues() []EnvelopeGetManyValue1 {
	if e == nil {
		return nil
	}
	return e.Values
}

func (e *EnvelopeGetManyFieldMetaRadio) GetDirection() *EnvelopeGetManyDirection1 {
	if e == nil {
		return nil
	}
	return e.Direction
}

type EnvelopeGetManyTypeNumber string

const (
	EnvelopeGetManyTypeNumberNumber EnvelopeGetManyTypeNumber = "number"
)

func (e EnvelopeGetManyTypeNumber) ToPointer() *EnvelopeGetManyTypeNumber {
	return &e
}
func (e *EnvelopeGetManyTypeNumber) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "number":
		*e = EnvelopeGetManyTypeNumber(v)
		return nil
	default:
		return fmt.Errorf("invalid value for EnvelopeGetManyTypeNumber: %v", v)
	}
}

type EnvelopeGetManyTextAlign6 string

const (
	EnvelopeGetManyTextAlign6Left   EnvelopeGetManyTextAlign6 = "left"
	EnvelopeGetManyTextAlign6Center EnvelopeGetManyTextAlign6 = "center"
	EnvelopeGetManyTextAlign6Right  EnvelopeGetManyTextAlign6 = "right"
)

func (e EnvelopeGetManyTextAlign6) ToPointer() *EnvelopeGetManyTextAlign6 {
	return &e
}
func (e *EnvelopeGetManyTextAlign6) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "left":
		fallthrough
	case "center":
		fallthrough
	case "right":
		*e = EnvelopeGetManyTextAlign6(v)
		return nil
	default:
		return fmt.Errorf("invalid value for EnvelopeGetManyTextAlign6: %v", v)
	}
}

type EnvelopeGetManyVerticalAlign2 string

const (
	EnvelopeGetManyVerticalAlign2Top    EnvelopeGetManyVerticalAlign2 = "top"
	EnvelopeGetManyVerticalAlign2Middle EnvelopeGetManyVerticalAlign2 = "middle"
	EnvelopeGetManyVerticalAlign2Bottom EnvelopeGetManyVerticalAlign2 = "bottom"
)

func (e EnvelopeGetManyVerticalAlign2) ToPointer() *EnvelopeGetManyVerticalAlign2 {
	return &e
}
func (e *EnvelopeGetManyVerticalAlign2) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "top":
		fallthrough
	case "middle":
		fallthrough
	case "bottom":
		*e = EnvelopeGetManyVerticalAlign2(v)
		return nil
	default:
		return fmt.Errorf("invalid value for EnvelopeGetManyVerticalAlign2: %v", v)
	}
}

type EnvelopeGetManyFieldMetaNumber struct {
	Label         *string                        `json:"label,omitempty"`
	Placeholder   *string                        `json:"placeholder,omitempty"`
	Required      *bool                          `json:"required,omitempty"`
	ReadOnly      *bool                          `json:"readOnly,omitempty"`
	FontSize      *float64                       `default:"12" json:"fontSize"`
	Type          EnvelopeGetManyTypeNumber      `json:"type"`
	NumberFormat  *string                        `json:"numberFormat,omitempty"`
	Value         *string                        `json:"value,omitempty"`
	MinValue      *float64                       `json:"minValue,omitempty"`
	MaxValue      *float64                       `json:"maxValue,omitempty"`
	TextAlign     *EnvelopeGetManyTextAlign6     `json:"textAlign,omitempty"`
	LineHeight    *float64                       `json:"lineHeight,omitempty"`
	LetterSpacing *float64                       `json:"letterSpacing,omitempty"`
	VerticalAlign *EnvelopeGetManyVerticalAlign2 `json:"verticalAlign,omitempty"`
}

func (e EnvelopeGetManyFieldMetaNumber) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *EnvelopeGetManyFieldMetaNumber) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, []string{"type"}); err != nil {
		return err
	}
	return nil
}

func (e *EnvelopeGetManyFieldMetaNumber) GetLabel() *string {
	if e == nil {
		return nil
	}
	return e.Label
}

func (e *EnvelopeGetManyFieldMetaNumber) GetPlaceholder() *string {
	if e == nil {
		return nil
	}
	return e.Placeholder
}

func (e *EnvelopeGetManyFieldMetaNumber) GetRequired() *bool {
	if e == nil {
		return nil
	}
	return e.Required
}

func (e *EnvelopeGetManyFieldMetaNumber) GetReadOnly() *bool {
	if e == nil {
		return nil
	}
	return e.ReadOnly
}

func (e *EnvelopeGetManyFieldMetaNumber) GetFontSize() *float64 {
	if e == nil {
		return nil
	}
	return e.FontSize
}

func (e *EnvelopeGetManyFieldMetaNumber) GetType() EnvelopeGetManyTypeNumber {
	if e == nil {
		return EnvelopeGetManyTypeNumber("")
	}
	return e.Type
}

func (e *EnvelopeGetManyFieldMetaNumber) GetNumberFormat() *string {
	if e == nil {
		return nil
	}
	return e.NumberFormat
}

func (e *EnvelopeGetManyFieldMetaNumber) GetValue() *string {
	if e == nil {
		return nil
	}
	return e.Value
}

func (e *EnvelopeGetManyFieldMetaNumber) GetMinValue() *float64 {
	if e == nil {
		return nil
	}
	return e.MinValue
}

func (e *EnvelopeGetManyFieldMetaNumber) GetMaxValue() *float64 {
	if e == nil {
		return nil
	}
	return e.MaxValue
}

func (e *EnvelopeGetManyFieldMetaNumber) GetTextAlign() *EnvelopeGetManyTextAlign6 {
	if e == nil {
		return nil
	}
	return e.TextAlign
}

func (e *EnvelopeGetManyFieldMetaNumber) GetLineHeight() *float64 {
	if e == nil {
		return nil
	}
	return e.LineHeight
}

func (e *EnvelopeGetManyFieldMetaNumber) GetLetterSpacing() *float64 {
	if e == nil {
		return nil
	}
	return e.LetterSpacing
}

func (e *EnvelopeGetManyFieldMetaNumber) GetVerticalAlign() *EnvelopeGetManyVerticalAlign2 {
	if e == nil {
		return nil
	}
	return e.VerticalAlign
}

type EnvelopeGetManyTypeText string

const (
	EnvelopeGetManyTypeTextText EnvelopeGetManyTypeText = "text"
)

func (e EnvelopeGetManyTypeText) ToPointer() *EnvelopeGetManyTypeText {
	return &e
}
func (e *EnvelopeGetManyTypeText) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "text":
		*e = EnvelopeGetManyTypeText(v)
		return nil
	default:
		return fmt.Errorf("invalid value for EnvelopeGetManyTypeText: %v", v)
	}
}

type EnvelopeGetManyTextAlign5 string

const (
	EnvelopeGetManyTextAlign5Left   EnvelopeGetManyTextAlign5 = "left"
	EnvelopeGetManyTextAlign5Center EnvelopeGetManyTextAlign5 = "center"
	EnvelopeGetManyTextAlign5Right  EnvelopeGetManyTextAlign5 = "right"
)

func (e EnvelopeGetManyTextAlign5) ToPointer() *EnvelopeGetManyTextAlign5 {
	return &e
}
func (e *EnvelopeGetManyTextAlign5) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "left":
		fallthrough
	case "center":
		fallthrough
	case "right":
		*e = EnvelopeGetManyTextAlign5(v)
		return nil
	default:
		return fmt.Errorf("invalid value for EnvelopeGetManyTextAlign5: %v", v)
	}
}

type EnvelopeGetManyVerticalAlign1 string

const (
	EnvelopeGetManyVerticalAlign1Top    EnvelopeGetManyVerticalAlign1 = "top"
	EnvelopeGetManyVerticalAlign1Middle EnvelopeGetManyVerticalAlign1 = "middle"
	EnvelopeGetManyVerticalAlign1Bottom EnvelopeGetManyVerticalAlign1 = "bottom"
)

func (e EnvelopeGetManyVerticalAlign1) ToPointer() *EnvelopeGetManyVerticalAlign1 {
	return &e
}
func (e *EnvelopeGetManyVerticalAlign1) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "top":
		fallthrough
	case "middle":
		fallthrough
	case "bottom":
		*e = EnvelopeGetManyVerticalAlign1(v)
		return nil
	default:
		return fmt.Errorf("invalid value for EnvelopeGetManyVerticalAlign1: %v", v)
	}
}

type EnvelopeGetManyFieldMetaText struct {
	Label          *string                        `json:"label,omitempty"`
	Placeholder    *string                        `json:"placeholder,omitempty"`
	Required       *bool                          `json:"required,omitempty"`
	ReadOnly       *bool                          `json:"readOnly,omitempty"`
	FontSize       *float64                       `default:"12" json:"fontSize"`
	Type           EnvelopeGetManyTypeText        `json:"type"`
	Text           *string                        `json:"text,omitempty"`
	CharacterLimit *float64                       `json:"characterLimit,omitempty"`
	TextAlign      *EnvelopeGetManyTextAlign5     `json:"textAlign,omitempty"`
	LineHeight     *float64                       `json:"lineHeight,omitempty"`
	LetterSpacing  *float64                       `json:"letterSpacing,omitempty"`
	VerticalAlign  *EnvelopeGetManyVerticalAlign1 `json:"verticalAlign,omitempty"`
}

func (e EnvelopeGetManyFieldMetaText) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *EnvelopeGetManyFieldMetaText) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, []string{"type"}); err != nil {
		return err
	}
	return nil
}

func (e *EnvelopeGetManyFieldMetaText) GetLabel() *string {
	if e == nil {
		return nil
	}
	return e.Label
}

func (e *EnvelopeGetManyFieldMetaText) GetPlaceholder() *string {
	if e == nil {
		return nil
	}
	return e.Placeholder
}

func (e *EnvelopeGetManyFieldMetaText) GetRequired() *bool {
	if e == nil {
		return nil
	}
	return e.Required
}

func (e *EnvelopeGetManyFieldMetaText) GetReadOnly() *bool {
	if e == nil {
		return nil
	}
	return e.ReadOnly
}

func (e *EnvelopeGetManyFieldMetaText) GetFontSize() *float64 {
	if e == nil {
		return nil
	}
	return e.FontSize
}

func (e *EnvelopeGetManyFieldMetaText) GetType() EnvelopeGetManyTypeText {
	if e == nil {
		return EnvelopeGetManyTypeText("")
	}
	return e.Type
}

func (e *EnvelopeGetManyFieldMetaText) GetText() *string {
	if e == nil {
		return nil
	}
	return e.Text
}

func (e *EnvelopeGetManyFieldMetaText) GetCharacterLimit() *float64 {
	if e == nil {
		return nil
	}
	return e.CharacterLimit
}

func (e *EnvelopeGetManyFieldMetaText) GetTextAlign() *EnvelopeGetManyTextAlign5 {
	if e == nil {
		return nil
	}
	return e.TextAlign
}

func (e *EnvelopeGetManyFieldMetaText) GetLineHeight() *float64 {
	if e == nil {
		return nil
	}
	return e.LineHeight
}

func (e *EnvelopeGetManyFieldMetaText) GetLetterSpacing() *float64 {
	if e == nil {
		return nil
	}
	return e.LetterSpacing
}

func (e *EnvelopeGetManyFieldMetaText) GetVerticalAlign() *EnvelopeGetManyVerticalAlign1 {
	if e == nil {
		return nil
	}
	return e.VerticalAlign
}

type EnvelopeGetManyTypeDate string

const (
	EnvelopeGetManyTypeDateDate EnvelopeGetManyTypeDate = "date"
)

func (e EnvelopeGetManyTypeDate) ToPointer() *EnvelopeGetManyTypeDate {
	return &e
}
func (e *EnvelopeGetManyTypeDate) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "date":
		*e = EnvelopeGetManyTypeDate(v)
		return nil
	default:
		return fmt.Errorf("invalid value for EnvelopeGetManyTypeDate: %v", v)
	}
}

type EnvelopeGetManyTextAlign4 string

const (
	EnvelopeGetManyTextAlign4Left   EnvelopeGetManyTextAlign4 = "left"
	EnvelopeGetManyTextAlign4Center EnvelopeGetManyTextAlign4 = "center"
	EnvelopeGetManyTextAlign4Right  EnvelopeGetManyTextAlign4 = "right"
)

func (e EnvelopeGetManyTextAlign4) ToPointer() *EnvelopeGetManyTextAlign4 {
	return &e
}
func (e *EnvelopeGetManyTextAlign4) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "left":
		fallthrough
	case "center":
		fallthrough
	case "right":
		*e = EnvelopeGetManyTextAlign4(v)
		return nil
	default:
		return fmt.Errorf("invalid value for EnvelopeGetManyTextAlign4: %v", v)
	}
}

type EnvelopeGetManyFieldMetaDate struct {
	Label       *string                    `json:"label,omitempty"`
	Placeholder *string                    `json:"placeholder,omitempty"`
	Required    *bool                      `json:"required,omitempty"`
	ReadOnly    *bool                      `json:"readOnly,omitempty"`
	FontSize    *float64                   `default:"12" json:"fontSize"`
	Type        EnvelopeGetManyTypeDate    `json:"type"`
	TextAlign   *EnvelopeGetManyTextAlign4 `json:"textAlign,omitempty"`
}

func (e EnvelopeGetManyFieldMetaDate) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *EnvelopeGetManyFieldMetaDate) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, []string{"type"}); err != nil {
		return err
	}
	return nil
}

func (e *EnvelopeGetManyFieldMetaDate) GetLabel() *string {
	if e == nil {
		return nil
	}
	return e.Label
}

func (e *EnvelopeGetManyFieldMetaDate) GetPlaceholder() *string {
	if e == nil {
		return nil
	}
	return e.Placeholder
}

func (e *EnvelopeGetManyFieldMetaDate) GetRequired() *bool {
	if e == nil {
		return nil
	}
	return e.Required
}

func (e *EnvelopeGetManyFieldMetaDate) GetReadOnly() *bool {
	if e == nil {
		return nil
	}
	return e.ReadOnly
}

func (e *EnvelopeGetManyFieldMetaDate) GetFontSize() *float64 {
	if e == nil {
		return nil
	}
	return e.FontSize
}

func (e *EnvelopeGetManyFieldMetaDate) GetType() EnvelopeGetManyTypeDate {
	if e == nil {
		return EnvelopeGetManyTypeDate("")
	}
	return e.Type
}

func (e *EnvelopeGetManyFieldMetaDate) GetTextAlign() *EnvelopeGetManyTextAlign4 {
	if e == nil {
		return nil
	}
	return e.TextAlign
}

type EnvelopeGetManyTypeEmail string

const (
	EnvelopeGetManyTypeEmailEmail EnvelopeGetManyTypeEmail = "email"
)

func (e EnvelopeGetManyTypeEmail) ToPointer() *EnvelopeGetManyTypeEmail {
	return &e
}
func (e *EnvelopeGetManyTypeEmail) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "email":
		*e = EnvelopeGetManyTypeEmail(v)
		return nil
	default:
		return fmt.Errorf("invalid value for EnvelopeGetManyTypeEmail: %v", v)
	}
}

type EnvelopeGetManyTextAlign3 string

const (
	EnvelopeGetManyTextAlign3Left   EnvelopeGetManyTextAlign3 = "left"
	EnvelopeGetManyTextAlign3Center EnvelopeGetManyTextAlign3 = "center"
	EnvelopeGetManyTextAlign3Right  EnvelopeGetManyTextAlign3 = "right"
)

func (e EnvelopeGetManyTextAlign3) ToPointer() *EnvelopeGetManyTextAlign3 {
	return &e
}
func (e *EnvelopeGetManyTextAlign3) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "left":
		fallthrough
	case "center":
		fallthrough
	case "right":
		*e = EnvelopeGetManyTextAlign3(v)
		return nil
	default:
		return fmt.Errorf("invalid value for EnvelopeGetManyTextAlign3: %v", v)
	}
}

type EnvelopeGetManyFieldMetaEmail struct {
	Label       *string                    `json:"label,omitempty"`
	Placeholder *string                    `json:"placeholder,omitempty"`
	Required    *bool                      `json:"required,omitempty"`
	ReadOnly    *bool                      `json:"readOnly,omitempty"`
	FontSize    *float64                   `default:"12" json:"fontSize"`
	Type        EnvelopeGetManyTypeEmail   `json:"type"`
	TextAlign   *EnvelopeGetManyTextAlign3 `json:"textAlign,omitempty"`
}

func (e EnvelopeGetManyFieldMetaEmail) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *EnvelopeGetManyFieldMetaEmail) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, []string{"type"}); err != nil {
		return err
	}
	return nil
}

func (e *EnvelopeGetManyFieldMetaEmail) GetLabel() *string {
	if e == nil {
		return nil
	}
	return e.Label
}

func (e *EnvelopeGetManyFieldMetaEmail) GetPlaceholder() *string {
	if e == nil {
		return nil
	}
	return e.Placeholder
}

func (e *EnvelopeGetManyFieldMetaEmail) GetRequired() *bool {
	if e == nil {
		return nil
	}
	return e.Required
}

func (e *EnvelopeGetManyFieldMetaEmail) GetReadOnly() *bool {
	if e == nil {
		return nil
	}
	return e.ReadOnly
}

func (e *EnvelopeGetManyFieldMetaEmail) GetFontSize() *float64 {
	if e == nil {
		return nil
	}
	return e.FontSize
}

func (e *EnvelopeGetManyFieldMetaEmail) GetType() EnvelopeGetManyTypeEmail {
	if e == nil {
		return EnvelopeGetManyTypeEmail("")
	}
	return e.Type
}

func (e *EnvelopeGetManyFieldMetaEmail) GetTextAlign() *EnvelopeGetManyTextAlign3 {
	if e == nil {
		return nil
	}
	return e.TextAlign
}

type EnvelopeGetManyTypeName string

const (
	EnvelopeGetManyTypeNameName EnvelopeGetManyTypeName = "name"
)

func (e EnvelopeGetManyTypeName) ToPointer() *EnvelopeGetManyTypeName {
	return &e
}
func (e *EnvelopeGetManyTypeName) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "name":
		*e = EnvelopeGetManyTypeName(v)
		return nil
	default:
		return fmt.Errorf("invalid value for EnvelopeGetManyTypeName: %v", v)
	}
}

type EnvelopeGetManyTextAlign2 string

const (
	EnvelopeGetManyTextAlign2Left   EnvelopeGetManyTextAlign2 = "left"
	EnvelopeGetManyTextAlign2Center EnvelopeGetManyTextAlign2 = "center"
	EnvelopeGetManyTextAlign2Right  EnvelopeGetManyTextAlign2 = "right"
)

func (e EnvelopeGetManyTextAlign2) ToPointer() *EnvelopeGetManyTextAlign2 {
	return &e
}
func (e *EnvelopeGetManyTextAlign2) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "left":
		fallthrough
	case "center":
		fallthrough
	case "right":
		*e = EnvelopeGetManyTextAlign2(v)
		return nil
	default:
		return fmt.Errorf("invalid value for EnvelopeGetManyTextAlign2: %v", v)
	}
}

type EnvelopeGetManyFieldMetaName struct {
	Label       *string                    `json:"label,omitempty"`
	Placeholder *string                    `json:"placeholder,omitempty"`
	Required    *bool                      `json:"required,omitempty"`
	ReadOnly    *bool                      `json:"readOnly,omitempty"`
	FontSize    *float64                   `default:"12" json:"fontSize"`
	Type        EnvelopeGetManyTypeName    `json:"type"`
	TextAlign   *EnvelopeGetManyTextAlign2 `json:"textAlign,omitempty"`
}

func (e EnvelopeGetManyFieldMetaName) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *EnvelopeGetManyFieldMetaName) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, []string{"type"}); err != nil {
		return err
	}
	return nil
}

func (e *EnvelopeGetManyFieldMetaName) GetLabel() *string {
	if e == nil {
		return nil
	}
	return e.Label
}

func (e *EnvelopeGetManyFieldMetaName) GetPlaceholder() *string {
	if e == nil {
		return nil
	}
	return e.Placeholder
}

func (e *EnvelopeGetManyFieldMetaName) GetRequired() *bool {
	if e == nil {
		return nil
	}
	return e.Required
}

func (e *EnvelopeGetManyFieldMetaName) GetReadOnly() *bool {
	if e == nil {
		return nil
	}
	return e.ReadOnly
}

func (e *EnvelopeGetManyFieldMetaName) GetFontSize() *float64 {
	if e == nil {
		return nil
	}
	return e.FontSize
}

func (e *EnvelopeGetManyFieldMetaName) GetType() EnvelopeGetManyTypeName {
	if e == nil {
		return EnvelopeGetManyTypeName("")
	}
	return e.Type
}

func (e *EnvelopeGetManyFieldMetaName) GetTextAlign() *EnvelopeGetManyTextAlign2 {
	if e == nil {
		return nil
	}
	return e.TextAlign
}

type EnvelopeGetManyTypeInitials string

const (
	EnvelopeGetManyTypeInitialsInitials EnvelopeGetManyTypeInitials = "initials"
)

func (e EnvelopeGetManyTypeInitials) ToPointer() *EnvelopeGetManyTypeInitials {
	return &e
}
func (e *EnvelopeGetManyTypeInitials) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "initials":
		*e = EnvelopeGetManyTypeInitials(v)
		return nil
	default:
		return fmt.Errorf("invalid value for EnvelopeGetManyTypeInitials: %v", v)
	}
}

type EnvelopeGetManyTextAlign1 string

const (
	EnvelopeGetManyTextAlign1Left   EnvelopeGetManyTextAlign1 = "left"
	EnvelopeGetManyTextAlign1Center EnvelopeGetManyTextAlign1 = "center"
	EnvelopeGetManyTextAlign1Right  EnvelopeGetManyTextAlign1 = "right"
)

func (e EnvelopeGetManyTextAlign1) ToPointer() *EnvelopeGetManyTextAlign1 {
	return &e
}
func (e *EnvelopeGetManyTextAlign1) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "left":
		fallthrough
	case "center":
		fallthrough
	case "right":
		*e = EnvelopeGetManyTextAlign1(v)
		return nil
	default:
		return fmt.Errorf("invalid value for EnvelopeGetManyTextAlign1: %v", v)
	}
}

type EnvelopeGetManyFieldMetaInitials struct {
	Label       *string                     `json:"label,omitempty"`
	Placeholder *string                     `json:"placeholder,omitempty"`
	Required    *bool                       `json:"required,omitempty"`
	ReadOnly    *bool                       `json:"readOnly,omitempty"`
	FontSize    *float64                    `default:"12" json:"fontSize"`
	Type        EnvelopeGetManyTypeInitials `json:"type"`
	TextAlign   *EnvelopeGetManyTextAlign1  `json:"textAlign,omitempty"`
}

func (e EnvelopeGetManyFieldMetaInitials) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *EnvelopeGetManyFieldMetaInitials) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, []string{"type"}); err != nil {
		return err
	}
	return nil
}

func (e *EnvelopeGetManyFieldMetaInitials) GetLabel() *string {
	if e == nil {
		return nil
	}
	return e.Label
}

func (e *EnvelopeGetManyFieldMetaInitials) GetPlaceholder() *string {
	if e == nil {
		return nil
	}
	return e.Placeholder
}

func (e *EnvelopeGetManyFieldMetaInitials) GetRequired() *bool {
	if e == nil {
		return nil
	}
	return e.Required
}

func (e *EnvelopeGetManyFieldMetaInitials) GetReadOnly() *bool {
	if e == nil {
		return nil
	}
	return e.ReadOnly
}

func (e *EnvelopeGetManyFieldMetaInitials) GetFontSize() *float64 {
	if e == nil {
		return nil
	}
	return e.FontSize
}

func (e *EnvelopeGetManyFieldMetaInitials) GetType() EnvelopeGetManyTypeInitials {
	if e == nil {
		return EnvelopeGetManyTypeInitials("")
	}
	return e.Type
}

func (e *EnvelopeGetManyFieldMetaInitials) GetTextAlign() *EnvelopeGetManyTextAlign1 {
	if e == nil {
		return nil
	}
	return e.TextAlign
}

type EnvelopeGetManyTypeSignature string

const (
	EnvelopeGetManyTypeSignatureSignature EnvelopeGetManyTypeSignature = "signature"
)

func (e EnvelopeGetManyTypeSignature) ToPointer() *EnvelopeGetManyTypeSignature {
	return &e
}
func (e *EnvelopeGetManyTypeSignature) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "signature":
		*e = EnvelopeGetManyTypeSignature(v)
		return nil
	default:
		return fmt.Errorf("invalid value for EnvelopeGetManyTypeSignature: %v", v)
	}
}

type EnvelopeGetManyFieldMetaSignature struct {
	Label       *string                      `json:"label,omitempty"`
	Placeholder *string                      `json:"placeholder,omitempty"`
	Required    *bool                        `json:"required,omitempty"`
	ReadOnly    *bool                        `json:"readOnly,omitempty"`
	FontSize    *float64                     `default:"12" json:"fontSize"`
	Type        EnvelopeGetManyTypeSignature `json:"type"`
}

func (e EnvelopeGetManyFieldMetaSignature) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *EnvelopeGetManyFieldMetaSignature) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, []string{"type"}); err != nil {
		return err
	}
	return nil
}

func (e *EnvelopeGetManyFieldMetaSignature) GetLabel() *string {
	if e == nil {
		return nil
	}
	return e.Label
}

func (e *EnvelopeGetManyFieldMetaSignature) GetPlaceholder() *string {
	if e == nil {
		return nil
	}
	return e.Placeholder
}

func (e *EnvelopeGetManyFieldMetaSignature) GetRequired() *bool {
	if e == nil {
		return nil
	}
	return e.Required
}

func (e *EnvelopeGetManyFieldMetaSignature) GetReadOnly() *bool {
	if e == nil {
		return nil
	}
	return e.ReadOnly
}

func (e *EnvelopeGetManyFieldMetaSignature) GetFontSize() *float64 {
	if e == nil {
		return nil
	}
	return e.FontSize
}

func (e *EnvelopeGetManyFieldMetaSignature) GetType() EnvelopeGetManyTypeSignature {
	if e == nil {
		return EnvelopeGetManyTypeSignature("")
	}
	return e.Type
}

type EnvelopeGetManyFieldMetaUnionType string

const (
	EnvelopeGetManyFieldMetaUnionTypeEnvelopeGetManyFieldMetaSignature EnvelopeGetManyFieldMetaUnionType = "envelope_getMany_fieldMeta_Signature"
	EnvelopeGetManyFieldMetaUnionTypeEnvelopeGetManyFieldMetaInitials  EnvelopeGetManyFieldMetaUnionType = "envelope_getMany_fieldMeta_Initials"
	EnvelopeGetManyFieldMetaUnionTypeEnvelopeGetManyFieldMetaName      EnvelopeGetManyFieldMetaUnionType = "envelope_getMany_fieldMeta_Name"
	EnvelopeGetManyFieldMetaUnionTypeEnvelopeGetManyFieldMetaEmail     EnvelopeGetManyFieldMetaUnionType = "envelope_getMany_fieldMeta_Email"
	EnvelopeGetManyFieldMetaUnionTypeEnvelopeGetManyFieldMetaDate      EnvelopeGetManyFieldMetaUnionType = "envelope_getMany_fieldMeta_Date"
	EnvelopeGetManyFieldMetaUnionTypeEnvelopeGetManyFieldMetaText      EnvelopeGetManyFieldMetaUnionType = "envelope_getMany_fieldMeta_Text"
	EnvelopeGetManyFieldMetaUnionTypeEnvelopeGetManyFieldMetaNumber    EnvelopeGetManyFieldMetaUnionType = "envelope_getMany_fieldMeta_Number"
	EnvelopeGetManyFieldMetaUnionTypeEnvelopeGetManyFieldMetaRadio     EnvelopeGetManyFieldMetaUnionType = "envelope_getMany_fieldMeta_Radio"
	EnvelopeGetManyFieldMetaUnionTypeEnvelopeGetManyFieldMetaCheckbox  EnvelopeGetManyFieldMetaUnionType = "envelope_getMany_fieldMeta_Checkbox"
	EnvelopeGetManyFieldMetaUnionTypeEnvelopeGetManyFieldMetaDropdown  EnvelopeGetManyFieldMetaUnionType = "envelope_getMany_fieldMeta_Dropdown"
)

type EnvelopeGetManyFieldMetaUnion struct {
	EnvelopeGetManyFieldMetaSignature *EnvelopeGetManyFieldMetaSignature `queryParam:"inline" union:"member"`
	EnvelopeGetManyFieldMetaInitials  *EnvelopeGetManyFieldMetaInitials  `queryParam:"inline" union:"member"`
	EnvelopeGetManyFieldMetaName      *EnvelopeGetManyFieldMetaName      `queryParam:"inline" union:"member"`
	EnvelopeGetManyFieldMetaEmail     *EnvelopeGetManyFieldMetaEmail     `queryParam:"inline" union:"member"`
	EnvelopeGetManyFieldMetaDate      *EnvelopeGetManyFieldMetaDate      `queryParam:"inline" union:"member"`
	EnvelopeGetManyFieldMetaText      *EnvelopeGetManyFieldMetaText      `queryParam:"inline" union:"member"`
	EnvelopeGetManyFieldMetaNumber    *EnvelopeGetManyFieldMetaNumber    `queryParam:"inline" union:"member"`
	EnvelopeGetManyFieldMetaRadio     *EnvelopeGetManyFieldMetaRadio     `queryParam:"inline" union:"member"`
	EnvelopeGetManyFieldMetaCheckbox  *EnvelopeGetManyFieldMetaCheckbox  `queryParam:"inline" union:"member"`
	EnvelopeGetManyFieldMetaDropdown  *EnvelopeGetManyFieldMetaDropdown  `queryParam:"inline" union:"member"`

	Type EnvelopeGetManyFieldMetaUnionType
}

func CreateEnvelopeGetManyFieldMetaUnionEnvelopeGetManyFieldMetaSignature(envelopeGetManyFieldMetaSignature EnvelopeGetManyFieldMetaSignature) EnvelopeGetManyFieldMetaUnion {
	typ := EnvelopeGetManyFieldMetaUnionTypeEnvelopeGetManyFieldMetaSignature

	return EnvelopeGetManyFieldMetaUnion{
		EnvelopeGetManyFieldMetaSignature: &envelopeGetManyFieldMetaSignature,
		Type:                              typ,
	}
}

func CreateEnvelopeGetManyFieldMetaUnionEnvelopeGetManyFieldMetaInitials(envelopeGetManyFieldMetaInitials EnvelopeGetManyFieldMetaInitials) EnvelopeGetManyFieldMetaUnion {
	typ := EnvelopeGetManyFieldMetaUnionTypeEnvelopeGetManyFieldMetaInitials

	return EnvelopeGetManyFieldMetaUnion{
		EnvelopeGetManyFieldMetaInitials: &envelopeGetManyFieldMetaInitials,
		Type:                             typ,
	}
}

func CreateEnvelopeGetManyFieldMetaUnionEnvelopeGetManyFieldMetaName(envelopeGetManyFieldMetaName EnvelopeGetManyFieldMetaName) EnvelopeGetManyFieldMetaUnion {
	typ := EnvelopeGetManyFieldMetaUnionTypeEnvelopeGetManyFieldMetaName

	return EnvelopeGetManyFieldMetaUnion{
		EnvelopeGetManyFieldMetaName: &envelopeGetManyFieldMetaName,
		Type:                         typ,
	}
}

func CreateEnvelopeGetManyFieldMetaUnionEnvelopeGetManyFieldMetaEmail(envelopeGetManyFieldMetaEmail EnvelopeGetManyFieldMetaEmail) EnvelopeGetManyFieldMetaUnion {
	typ := EnvelopeGetManyFieldMetaUnionTypeEnvelopeGetManyFieldMetaEmail

	return EnvelopeGetManyFieldMetaUnion{
		EnvelopeGetManyFieldMetaEmail: &envelopeGetManyFieldMetaEmail,
		Type:                          typ,
	}
}

func CreateEnvelopeGetManyFieldMetaUnionEnvelopeGetManyFieldMetaDate(envelopeGetManyFieldMetaDate EnvelopeGetManyFieldMetaDate) EnvelopeGetManyFieldMetaUnion {
	typ := EnvelopeGetManyFieldMetaUnionTypeEnvelopeGetManyFieldMetaDate

	return EnvelopeGetManyFieldMetaUnion{
		EnvelopeGetManyFieldMetaDate: &envelopeGetManyFieldMetaDate,
		Type:                         typ,
	}
}

func CreateEnvelopeGetManyFieldMetaUnionEnvelopeGetManyFieldMetaText(envelopeGetManyFieldMetaText EnvelopeGetManyFieldMetaText) EnvelopeGetManyFieldMetaUnion {
	typ := EnvelopeGetManyFieldMetaUnionTypeEnvelopeGetManyFieldMetaText

	return EnvelopeGetManyFieldMetaUnion{
		EnvelopeGetManyFieldMetaText: &envelopeGetManyFieldMetaText,
		Type:                         typ,
	}
}

func CreateEnvelopeGetManyFieldMetaUnionEnvelopeGetManyFieldMetaNumber(envelopeGetManyFieldMetaNumber EnvelopeGetManyFieldMetaNumber) EnvelopeGetManyFieldMetaUnion {
	typ := EnvelopeGetManyFieldMetaUnionTypeEnvelopeGetManyFieldMetaNumber

	return EnvelopeGetManyFieldMetaUnion{
		EnvelopeGetManyFieldMetaNumber: &envelopeGetManyFieldMetaNumber,
		Type:                           typ,
	}
}

func CreateEnvelopeGetManyFieldMetaUnionEnvelopeGetManyFieldMetaRadio(envelopeGetManyFieldMetaRadio EnvelopeGetManyFieldMetaRadio) EnvelopeGetManyFieldMetaUnion {
	typ := EnvelopeGetManyFieldMetaUnionTypeEnvelopeGetManyFieldMetaRadio

	return EnvelopeGetManyFieldMetaUnion{
		EnvelopeGetManyFieldMetaRadio: &envelopeGetManyFieldMetaRadio,
		Type:                          typ,
	}
}

func CreateEnvelopeGetManyFieldMetaUnionEnvelopeGetManyFieldMetaCheckbox(envelopeGetManyFieldMetaCheckbox EnvelopeGetManyFieldMetaCheckbox) EnvelopeGetManyFieldMetaUnion {
	typ := EnvelopeGetManyFieldMetaUnionTypeEnvelopeGetManyFieldMetaCheckbox

	return EnvelopeGetManyFieldMetaUnion{
		EnvelopeGetManyFieldMetaCheckbox: &envelopeGetManyFieldMetaCheckbox,
		Type:                             typ,
	}
}

func CreateEnvelopeGetManyFieldMetaUnionEnvelopeGetManyFieldMetaDropdown(envelopeGetManyFieldMetaDropdown EnvelopeGetManyFieldMetaDropdown) EnvelopeGetManyFieldMetaUnion {
	typ := EnvelopeGetManyFieldMetaUnionTypeEnvelopeGetManyFieldMetaDropdown

	return EnvelopeGetManyFieldMetaUnion{
		EnvelopeGetManyFieldMetaDropdown: &envelopeGetManyFieldMetaDropdown,
		Type:                             typ,
	}
}

func (u *EnvelopeGetManyFieldMetaUnion) UnmarshalJSON(data []byte) error {

	var envelopeGetManyFieldMetaSignature EnvelopeGetManyFieldMetaSignature = EnvelopeGetManyFieldMetaSignature{}
	if err := utils.UnmarshalJSON(data, &envelopeGetManyFieldMetaSignature, "", true, nil); err == nil {
		u.EnvelopeGetManyFieldMetaSignature = &envelopeGetManyFieldMetaSignature
		u.Type = EnvelopeGetManyFieldMetaUnionTypeEnvelopeGetManyFieldMetaSignature
		return nil
	}

	var envelopeGetManyFieldMetaInitials EnvelopeGetManyFieldMetaInitials = EnvelopeGetManyFieldMetaInitials{}
	if err := utils.UnmarshalJSON(data, &envelopeGetManyFieldMetaInitials, "", true, nil); err == nil {
		u.EnvelopeGetManyFieldMetaInitials = &envelopeGetManyFieldMetaInitials
		u.Type = EnvelopeGetManyFieldMetaUnionTypeEnvelopeGetManyFieldMetaInitials
		return nil
	}

	var envelopeGetManyFieldMetaName EnvelopeGetManyFieldMetaName = EnvelopeGetManyFieldMetaName{}
	if err := utils.UnmarshalJSON(data, &envelopeGetManyFieldMetaName, "", true, nil); err == nil {
		u.EnvelopeGetManyFieldMetaName = &envelopeGetManyFieldMetaName
		u.Type = EnvelopeGetManyFieldMetaUnionTypeEnvelopeGetManyFieldMetaName
		return nil
	}

	var envelopeGetManyFieldMetaEmail EnvelopeGetManyFieldMetaEmail = EnvelopeGetManyFieldMetaEmail{}
	if err := utils.UnmarshalJSON(data, &envelopeGetManyFieldMetaEmail, "", true, nil); err == nil {
		u.EnvelopeGetManyFieldMetaEmail = &envelopeGetManyFieldMetaEmail
		u.Type = EnvelopeGetManyFieldMetaUnionTypeEnvelopeGetManyFieldMetaEmail
		return nil
	}

	var envelopeGetManyFieldMetaDate EnvelopeGetManyFieldMetaDate = EnvelopeGetManyFieldMetaDate{}
	if err := utils.UnmarshalJSON(data, &envelopeGetManyFieldMetaDate, "", true, nil); err == nil {
		u.EnvelopeGetManyFieldMetaDate = &envelopeGetManyFieldMetaDate
		u.Type = EnvelopeGetManyFieldMetaUnionTypeEnvelopeGetManyFieldMetaDate
		return nil
	}

	var envelopeGetManyFieldMetaText EnvelopeGetManyFieldMetaText = EnvelopeGetManyFieldMetaText{}
	if err := utils.UnmarshalJSON(data, &envelopeGetManyFieldMetaText, "", true, nil); err == nil {
		u.EnvelopeGetManyFieldMetaText = &envelopeGetManyFieldMetaText
		u.Type = EnvelopeGetManyFieldMetaUnionTypeEnvelopeGetManyFieldMetaText
		return nil
	}

	var envelopeGetManyFieldMetaNumber EnvelopeGetManyFieldMetaNumber = EnvelopeGetManyFieldMetaNumber{}
	if err := utils.UnmarshalJSON(data, &envelopeGetManyFieldMetaNumber, "", true, nil); err == nil {
		u.EnvelopeGetManyFieldMetaNumber = &envelopeGetManyFieldMetaNumber
		u.Type = EnvelopeGetManyFieldMetaUnionTypeEnvelopeGetManyFieldMetaNumber
		return nil
	}

	var envelopeGetManyFieldMetaRadio EnvelopeGetManyFieldMetaRadio = EnvelopeGetManyFieldMetaRadio{}
	if err := utils.UnmarshalJSON(data, &envelopeGetManyFieldMetaRadio, "", true, nil); err == nil {
		u.EnvelopeGetManyFieldMetaRadio = &envelopeGetManyFieldMetaRadio
		u.Type = EnvelopeGetManyFieldMetaUnionTypeEnvelopeGetManyFieldMetaRadio
		return nil
	}

	var envelopeGetManyFieldMetaCheckbox EnvelopeGetManyFieldMetaCheckbox = EnvelopeGetManyFieldMetaCheckbox{}
	if err := utils.UnmarshalJSON(data, &envelopeGetManyFieldMetaCheckbox, "", true, nil); err == nil {
		u.EnvelopeGetManyFieldMetaCheckbox = &envelopeGetManyFieldMetaCheckbox
		u.Type = EnvelopeGetManyFieldMetaUnionTypeEnvelopeGetManyFieldMetaCheckbox
		return nil
	}

	var envelopeGetManyFieldMetaDropdown EnvelopeGetManyFieldMetaDropdown = EnvelopeGetManyFieldMetaDropdown{}
	if err := utils.UnmarshalJSON(data, &envelopeGetManyFieldMetaDropdown, "", true, nil); err == nil {
		u.EnvelopeGetManyFieldMetaDropdown = &envelopeGetManyFieldMetaDropdown
		u.Type = EnvelopeGetManyFieldMetaUnionTypeEnvelopeGetManyFieldMetaDropdown
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for EnvelopeGetManyFieldMetaUnion", string(data))
}

func (u EnvelopeGetManyFieldMetaUnion) MarshalJSON() ([]byte, error) {
	if u.EnvelopeGetManyFieldMetaSignature != nil {
		return utils.MarshalJSON(u.EnvelopeGetManyFieldMetaSignature, "", true)
	}

	if u.EnvelopeGetManyFieldMetaInitials != nil {
		return utils.MarshalJSON(u.EnvelopeGetManyFieldMetaInitials, "", true)
	}

	if u.EnvelopeGetManyFieldMetaName != nil {
		return utils.MarshalJSON(u.EnvelopeGetManyFieldMetaName, "", true)
	}

	if u.EnvelopeGetManyFieldMetaEmail != nil {
		return utils.MarshalJSON(u.EnvelopeGetManyFieldMetaEmail, "", true)
	}

	if u.EnvelopeGetManyFieldMetaDate != nil {
		return utils.MarshalJSON(u.EnvelopeGetManyFieldMetaDate, "", true)
	}

	if u.EnvelopeGetManyFieldMetaText != nil {
		return utils.MarshalJSON(u.EnvelopeGetManyFieldMetaText, "", true)
	}

	if u.EnvelopeGetManyFieldMetaNumber != nil {
		return utils.MarshalJSON(u.EnvelopeGetManyFieldMetaNumber, "", true)
	}

	if u.EnvelopeGetManyFieldMetaRadio != nil {
		return utils.MarshalJSON(u.EnvelopeGetManyFieldMetaRadio, "", true)
	}

	if u.EnvelopeGetManyFieldMetaCheckbox != nil {
		return utils.MarshalJSON(u.EnvelopeGetManyFieldMetaCheckbox, "", true)
	}

	if u.EnvelopeGetManyFieldMetaDropdown != nil {
		return utils.MarshalJSON(u.EnvelopeGetManyFieldMetaDropdown, "", true)
	}

	return nil, errors.New("could not marshal union type EnvelopeGetManyFieldMetaUnion: all fields are null")
}

type EnvelopeGetManyField struct {
	EnvelopeID     string                         `json:"envelopeId"`
	EnvelopeItemID string                         `json:"envelopeItemId"`
	Type           EnvelopeGetManyFieldType       `json:"type"`
	ID             float64                        `json:"id"`
	SecondaryID    string                         `json:"secondaryId"`
	RecipientID    float64                        `json:"recipientId"`
	Page           float64                        `json:"page"`
	PositionX      any                            `json:"positionX"`
	PositionY      any                            `json:"positionY"`
	Width          any                            `json:"width"`
	Height         any                            `json:"height"`
	CustomText     string                         `json:"customText"`
	Inserted       bool                           `json:"inserted"`
	FieldMeta      *EnvelopeGetManyFieldMetaUnion `json:"fieldMeta"`
}

func (e *EnvelopeGetManyField) GetEnvelopeID() string {
	if e == nil {
		return ""
	}
	return e.EnvelopeID
}

func (e *EnvelopeGetManyField) GetEnvelopeItemID() string {
	if e == nil {
		return ""
	}
	return e.EnvelopeItemID
}

func (e *EnvelopeGetManyField) GetType() EnvelopeGetManyFieldType {
	if e == nil {
		return EnvelopeGetManyFieldType("")
	}
	return e.Type
}

func (e *EnvelopeGetManyField) GetID() float64 {
	if e == nil {
		return 0.0
	}
	return e.ID
}

func (e *EnvelopeGetManyField) GetSecondaryID() string {
	if e == nil {
		return ""
	}
	return e.SecondaryID
}

func (e *EnvelopeGetManyField) GetRecipientID() float64 {
	if e == nil {
		return 0.0
	}
	return e.RecipientID
}

func (e *EnvelopeGetManyField) GetPage() float64 {
	if e == nil {
		return 0.0
	}
	return e.Page
}

func (e *EnvelopeGetManyField) GetPositionX() any {
	if e == nil {
		return nil
	}
	return e.PositionX
}

func (e *EnvelopeGetManyField) GetPositionY() any {
	if e == nil {
		return nil
	}
	return e.PositionY
}

func (e *EnvelopeGetManyField) GetWidth() any {
	if e == nil {
		return nil
	}
	return e.Width
}

func (e *EnvelopeGetManyField) GetHeight() any {
	if e == nil {
		return nil
	}
	return e.Height
}

func (e *EnvelopeGetManyField) GetCustomText() string {
	if e == nil {
		return ""
	}
	return e.CustomText
}

func (e *EnvelopeGetManyField) GetInserted() bool {
	if e == nil {
		return false
	}
	return e.Inserted
}

func (e *EnvelopeGetManyField) GetFieldMeta() *EnvelopeGetManyFieldMetaUnion {
	if e == nil {
		return nil
	}
	return e.FieldMeta
}

type EnvelopeGetManyEnvelopeItem struct {
	EnvelopeID string  `json:"envelopeId"`
	ID         string  `json:"id"`
	Title      string  `json:"title"`
	Order      float64 `json:"order"`
}

func (e *EnvelopeGetManyEnvelopeItem) GetEnvelopeID() string {
	if e == nil {
		return ""
	}
	return e.EnvelopeID
}

func (e *EnvelopeGetManyEnvelopeItem) GetID() string {
	if e == nil {
		return ""
	}
	return e.ID
}

func (e *EnvelopeGetManyEnvelopeItem) GetTitle() string {
	if e == nil {
		return ""
	}
	return e.Title
}

func (e *EnvelopeGetManyEnvelopeItem) GetOrder() float64 {
	if e == nil {
		return 0.0
	}
	return e.Order
}

type EnvelopeGetManyDirectLink struct {
	DirectTemplateRecipientID float64 `json:"directTemplateRecipientId"`
	Enabled                   bool    `json:"enabled"`
	ID                        string  `json:"id"`
	Token                     string  `json:"token"`
}

func (e *EnvelopeGetManyDirectLink) GetDirectTemplateRecipientID() float64 {
	if e == nil {
		return 0.0
	}
	return e.DirectTemplateRecipientID
}

func (e *EnvelopeGetManyDirectLink) GetEnabled() bool {
	if e == nil {
		return false
	}
	return e.Enabled
}

func (e *EnvelopeGetManyDirectLink) GetID() string {
	if e == nil {
		return ""
	}
	return e.ID
}

func (e *EnvelopeGetManyDirectLink) GetToken() string {
	if e == nil {
		return ""
	}
	return e.Token
}

type EnvelopeGetManyTeam struct {
	ID  float64 `json:"id"`
	URL string  `json:"url"`
}

func (e *EnvelopeGetManyTeam) GetID() float64 {
	if e == nil {
		return 0.0
	}
	return e.ID
}

func (e *EnvelopeGetManyTeam) GetURL() string {
	if e == nil {
		return ""
	}
	return e.URL
}

type EnvelopeGetManyUser struct {
	ID    float64 `json:"id"`
	Name  string  `json:"name"`
	Email string  `json:"email"`
}

func (e *EnvelopeGetManyUser) GetID() float64 {
	if e == nil {
		return 0.0
	}
	return e.ID
}

func (e *EnvelopeGetManyUser) GetName() string {
	if e == nil {
		return ""
	}
	return e.Name
}

func (e *EnvelopeGetManyUser) GetEmail() string {
	if e == nil {
		return ""
	}
	return e.Email
}

type EnvelopeGetManyData struct {
	InternalVersion   float64                              `json:"internalVersion"`
	Type              EnvelopeGetManyDataType              `json:"type"`
	Status            EnvelopeGetManyStatus                `json:"status"`
	Source            EnvelopeGetManySource                `json:"source"`
	Visibility        EnvelopeGetManyVisibility            `json:"visibility"`
	TemplateType      EnvelopeGetManyTemplateType          `json:"templateType"`
	ID                string                               `json:"id"`
	SecondaryID       string                               `json:"secondaryId"`
	ExternalID        *string                              `json:"externalId"`
	CreatedAt         string                               `json:"createdAt"`
	UpdatedAt         string                               `json:"updatedAt"`
	CompletedAt       *string                              `json:"completedAt"`
	DeletedAt         *string                              `json:"deletedAt"`
	Title             string                               `json:"title"`
	AuthOptions       *EnvelopeGetManyAuthOptions          `json:"authOptions"`
	FormValues        map[string]EnvelopeGetManyFormValues `json:"formValues"`
	PublicTitle       string                               `json:"publicTitle"`
	PublicDescription string                               `json:"publicDescription"`
	UserID            float64                              `json:"userId"`
	TeamID            float64                              `json:"teamId"`
	FolderID          *string                              `json:"folderId"`
	TemplateID        *float64                             `json:"templateId"`
	DocumentMeta      EnvelopeGetManyDocumentMeta          `json:"documentMeta"`
	Recipients        []EnvelopeGetManyRecipient           `json:"recipients"`
	Fields            []EnvelopeGetManyField               `json:"fields"`
	EnvelopeItems     []EnvelopeGetManyEnvelopeItem        `json:"envelopeItems"`
	DirectLink        *EnvelopeGetManyDirectLink           `json:"directLink"`
	Team              EnvelopeGetManyTeam                  `json:"team"`
	User              EnvelopeGetManyUser                  `json:"user"`
}

func (e *EnvelopeGetManyData) GetInternalVersion() float64 {
	if e == nil {
		return 0.0
	}
	return e.InternalVersion
}

func (e *EnvelopeGetManyData) GetType() EnvelopeGetManyDataType {
	if e == nil {
		return EnvelopeGetManyDataType("")
	}
	return e.Type
}

func (e *EnvelopeGetManyData) GetStatus() EnvelopeGetManyStatus {
	if e == nil {
		return EnvelopeGetManyStatus("")
	}
	return e.Status
}

func (e *EnvelopeGetManyData) GetSource() EnvelopeGetManySource {
	if e == nil {
		return EnvelopeGetManySource("")
	}
	return e.Source
}

func (e *EnvelopeGetManyData) GetVisibility() EnvelopeGetManyVisibility {
	if e == nil {
		return EnvelopeGetManyVisibility("")
	}
	return e.Visibility
}

func (e *EnvelopeGetManyData) GetTemplateType() EnvelopeGetManyTemplateType {
	if e == nil {
		return EnvelopeGetManyTemplateType("")
	}
	return e.TemplateType
}

func (e *EnvelopeGetManyData) GetID() string {
	if e == nil {
		return ""
	}
	return e.ID
}

func (e *EnvelopeGetManyData) GetSecondaryID() string {
	if e == nil {
		return ""
	}
	return e.SecondaryID
}

func (e *EnvelopeGetManyData) GetExternalID() *string {
	if e == nil {
		return nil
	}
	return e.ExternalID
}

func (e *EnvelopeGetManyData) GetCreatedAt() string {
	if e == nil {
		return ""
	}
	return e.CreatedAt
}

func (e *EnvelopeGetManyData) GetUpdatedAt() string {
	if e == nil {
		return ""
	}
	return e.UpdatedAt
}

func (e *EnvelopeGetManyData) GetCompletedAt() *string {
	if e == nil {
		return nil
	}
	return e.CompletedAt
}

func (e *EnvelopeGetManyData) GetDeletedAt() *string {
	if e == nil {
		return nil
	}
	return e.DeletedAt
}

func (e *EnvelopeGetManyData) GetTitle() string {
	if e == nil {
		return ""
	}
	return e.Title
}

func (e *EnvelopeGetManyData) GetAuthOptions() *EnvelopeGetManyAuthOptions {
	if e == nil {
		return nil
	}
	return e.AuthOptions
}

func (e *EnvelopeGetManyData) GetFormValues() map[string]EnvelopeGetManyFormValues {
	if e == nil {
		return nil
	}
	return e.FormValues
}

func (e *EnvelopeGetManyData) GetPublicTitle() string {
	if e == nil {
		return ""
	}
	return e.PublicTitle
}

func (e *EnvelopeGetManyData) GetPublicDescription() string {
	if e == nil {
		return ""
	}
	return e.PublicDescription
}

func (e *EnvelopeGetManyData) GetUserID() float64 {
	if e == nil {
		return 0.0
	}
	return e.UserID
}

func (e *EnvelopeGetManyData) GetTeamID() float64 {
	if e == nil {
		return 0.0
	}
	return e.TeamID
}

func (e *EnvelopeGetManyData) GetFolderID() *string {
	if e == nil {
		return nil
	}
	return e.FolderID
}

func (e *EnvelopeGetManyData) GetTemplateID() *float64 {
	if e == nil {
		return nil
	}
	return e.TemplateID
}

func (e *EnvelopeGetManyData) GetDocumentMeta() EnvelopeGetManyDocumentMeta {
	if e == nil {
		return EnvelopeGetManyDocumentMeta{}
	}
	return e.DocumentMeta
}

func (e *EnvelopeGetManyData) GetRecipients() []EnvelopeGetManyRecipient {
	if e == nil {
		return []EnvelopeGetManyRecipient{}
	}
	return e.Recipients
}

func (e *EnvelopeGetManyData) GetFields() []EnvelopeGetManyField {
	if e == nil {
		return []EnvelopeGetManyField{}
	}
	return e.Fields
}

func (e *EnvelopeGetManyData) GetEnvelopeItems() []EnvelopeGetManyEnvelopeItem {
	if e == nil {
		return []EnvelopeGetManyEnvelopeItem{}
	}
	return e.EnvelopeItems
}

func (e *EnvelopeGetManyData) GetDirectLink() *EnvelopeGetManyDirectLink {
	if e == nil {
		return nil
	}
	return e.DirectLink
}

func (e *EnvelopeGetManyData) GetTeam() EnvelopeGetManyTeam {
	if e == nil {
		return EnvelopeGetManyTeam{}
	}
	return e.Team
}

func (e *EnvelopeGetManyData) GetUser() EnvelopeGetManyUser {
	if e == nil {
		return EnvelopeGetManyUser{}
	}
	return e.User
}

// EnvelopeGetManyResponseBody - Successful response
type EnvelopeGetManyResponseBody struct {
	Data []EnvelopeGetManyData `json:"data"`
}

func (e *EnvelopeGetManyResponseBody) GetData() []EnvelopeGetManyData {
	if e == nil {
		return []EnvelopeGetManyData{}
	}
	return e.Data
}

type EnvelopeGetManyResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful response
	Object *EnvelopeGetManyResponseBody
}

func (e *EnvelopeGetManyResponse) GetHTTPMeta() components.HTTPMetadata {
	if e == nil {
		return components.HTTPMetadata{}
	}
	return e.HTTPMeta
}

func (e *EnvelopeGetManyResponse) GetObject() *EnvelopeGetManyResponseBody {
	if e == nil {
		return nil
	}
	return e.Object
}
