// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/documenso/sdk-go/models/components"
)

type EnvelopeRecipientDeleteRequest struct {
	RecipientID float64 `json:"recipientId"`
}

func (e *EnvelopeRecipientDeleteRequest) GetRecipientID() float64 {
	if e == nil {
		return 0.0
	}
	return e.RecipientID
}

// EnvelopeRecipientDeleteResponseBody - Successful response
type EnvelopeRecipientDeleteResponseBody struct {
	Success bool `json:"success"`
}

func (e *EnvelopeRecipientDeleteResponseBody) GetSuccess() bool {
	if e == nil {
		return false
	}
	return e.Success
}

type EnvelopeRecipientDeleteResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful response
	Object *EnvelopeRecipientDeleteResponseBody
}

func (e *EnvelopeRecipientDeleteResponse) GetHTTPMeta() components.HTTPMetadata {
	if e == nil {
		return components.HTTPMetadata{}
	}
	return e.HTTPMeta
}

func (e *EnvelopeRecipientDeleteResponse) GetObject() *EnvelopeRecipientDeleteResponseBody {
	if e == nil {
		return nil
	}
	return e.Object
}
