// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/documenso/sdk-go/models/components"
)

type EnvelopeAttachmentCreateData struct {
	Label string `json:"label"`
	Data  string `json:"data"`
}

func (e *EnvelopeAttachmentCreateData) GetLabel() string {
	if e == nil {
		return ""
	}
	return e.Label
}

func (e *EnvelopeAttachmentCreateData) GetData() string {
	if e == nil {
		return ""
	}
	return e.Data
}

type EnvelopeAttachmentCreateRequest struct {
	EnvelopeID string                       `json:"envelopeId"`
	Data       EnvelopeAttachmentCreateData `json:"data"`
}

func (e *EnvelopeAttachmentCreateRequest) GetEnvelopeID() string {
	if e == nil {
		return ""
	}
	return e.EnvelopeID
}

func (e *EnvelopeAttachmentCreateRequest) GetData() EnvelopeAttachmentCreateData {
	if e == nil {
		return EnvelopeAttachmentCreateData{}
	}
	return e.Data
}

// EnvelopeAttachmentCreateResponseBody - Successful response
type EnvelopeAttachmentCreateResponseBody struct {
	ID string `json:"id"`
}

func (e *EnvelopeAttachmentCreateResponseBody) GetID() string {
	if e == nil {
		return ""
	}
	return e.ID
}

type EnvelopeAttachmentCreateResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful response
	Object *EnvelopeAttachmentCreateResponseBody
}

func (e *EnvelopeAttachmentCreateResponse) GetHTTPMeta() components.HTTPMetadata {
	if e == nil {
		return components.HTTPMetadata{}
	}
	return e.HTTPMeta
}

func (e *EnvelopeAttachmentCreateResponse) GetObject() *EnvelopeAttachmentCreateResponseBody {
	if e == nil {
		return nil
	}
	return e.Object
}
