// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/documenso/sdk-go/internal/utils"
	"github.com/documenso/sdk-go/models/components"
)

type EnvelopeDistributeDateFormat string

const (
	EnvelopeDistributeDateFormatYyyyMMddHhMmA            EnvelopeDistributeDateFormat = "yyyy-MM-dd hh:mm a"
	EnvelopeDistributeDateFormatYyyyMMdd                 EnvelopeDistributeDateFormat = "yyyy-MM-dd"
	EnvelopeDistributeDateFormatDdMmSlashYyyy            EnvelopeDistributeDateFormat = "dd/MM/yyyy"
	EnvelopeDistributeDateFormatMmDdSlashYyyy            EnvelopeDistributeDateFormat = "MM/dd/yyyy"
	EnvelopeDistributeDateFormatYyMMdd                   EnvelopeDistributeDateFormat = "yy-MM-dd"
	EnvelopeDistributeDateFormatMmmmDdCommaYyyy          EnvelopeDistributeDateFormat = "MMMM dd, yyyy"
	EnvelopeDistributeDateFormatEeeeMmmmDdCommaYyyy      EnvelopeDistributeDateFormat = "EEEE, MMMM dd, yyyy"
	EnvelopeDistributeDateFormatDdMmSlashYyyyHhMmA       EnvelopeDistributeDateFormat = "dd/MM/yyyy hh:mm a"
	EnvelopeDistributeDateFormatDdMmSlashYyyyHHmm        EnvelopeDistributeDateFormat = "dd/MM/yyyy HH:mm"
	EnvelopeDistributeDateFormatMmDdSlashYyyyHhMmA       EnvelopeDistributeDateFormat = "MM/dd/yyyy hh:mm a"
	EnvelopeDistributeDateFormatMmDdSlashYyyyHHmm        EnvelopeDistributeDateFormat = "MM/dd/yyyy HH:mm"
	EnvelopeDistributeDateFormatDdDotMmDotYyyy           EnvelopeDistributeDateFormat = "dd.MM.yyyy"
	EnvelopeDistributeDateFormatDdDotMmDotYyyyHHmm       EnvelopeDistributeDateFormat = "dd.MM.yyyy HH:mm"
	EnvelopeDistributeDateFormatYyyyMMddHHmm             EnvelopeDistributeDateFormat = "yyyy-MM-dd HH:mm"
	EnvelopeDistributeDateFormatYyMMddHhMmA              EnvelopeDistributeDateFormat = "yy-MM-dd hh:mm a"
	EnvelopeDistributeDateFormatYyMMddHHmm               EnvelopeDistributeDateFormat = "yy-MM-dd HH:mm"
	EnvelopeDistributeDateFormatYyyyMMddHHmmss           EnvelopeDistributeDateFormat = "yyyy-MM-dd HH:mm:ss"
	EnvelopeDistributeDateFormatMmmmDdCommaYyyyHhMmA     EnvelopeDistributeDateFormat = "MMMM dd, yyyy hh:mm a"
	EnvelopeDistributeDateFormatMmmmDdCommaYyyyHHmm      EnvelopeDistributeDateFormat = "MMMM dd, yyyy HH:mm"
	EnvelopeDistributeDateFormatEeeeMmmmDdCommaYyyyHhMmA EnvelopeDistributeDateFormat = "EEEE, MMMM dd, yyyy hh:mm a"
	EnvelopeDistributeDateFormatEeeeMmmmDdCommaYyyyHHmm  EnvelopeDistributeDateFormat = "EEEE, MMMM dd, yyyy HH:mm"
	EnvelopeDistributeDateFormatIso8601Full              EnvelopeDistributeDateFormat = "yyyy-MM-dd'T'HH:mm:ss.SSSXXX"
)

func (e EnvelopeDistributeDateFormat) ToPointer() *EnvelopeDistributeDateFormat {
	return &e
}
func (e *EnvelopeDistributeDateFormat) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "yyyy-MM-dd hh:mm a":
		fallthrough
	case "yyyy-MM-dd":
		fallthrough
	case "dd/MM/yyyy":
		fallthrough
	case "MM/dd/yyyy":
		fallthrough
	case "yy-MM-dd":
		fallthrough
	case "MMMM dd, yyyy":
		fallthrough
	case "EEEE, MMMM dd, yyyy":
		fallthrough
	case "dd/MM/yyyy hh:mm a":
		fallthrough
	case "dd/MM/yyyy HH:mm":
		fallthrough
	case "MM/dd/yyyy hh:mm a":
		fallthrough
	case "MM/dd/yyyy HH:mm":
		fallthrough
	case "dd.MM.yyyy":
		fallthrough
	case "dd.MM.yyyy HH:mm":
		fallthrough
	case "yyyy-MM-dd HH:mm":
		fallthrough
	case "yy-MM-dd hh:mm a":
		fallthrough
	case "yy-MM-dd HH:mm":
		fallthrough
	case "yyyy-MM-dd HH:mm:ss":
		fallthrough
	case "MMMM dd, yyyy hh:mm a":
		fallthrough
	case "MMMM dd, yyyy HH:mm":
		fallthrough
	case "EEEE, MMMM dd, yyyy hh:mm a":
		fallthrough
	case "EEEE, MMMM dd, yyyy HH:mm":
		fallthrough
	case "yyyy-MM-dd'T'HH:mm:ss.SSSXXX":
		*e = EnvelopeDistributeDateFormat(v)
		return nil
	default:
		return fmt.Errorf("invalid value for EnvelopeDistributeDateFormat: %v", v)
	}
}

type EnvelopeDistributeDistributionMethod string

const (
	EnvelopeDistributeDistributionMethodEmail EnvelopeDistributeDistributionMethod = "EMAIL"
	EnvelopeDistributeDistributionMethodNone  EnvelopeDistributeDistributionMethod = "NONE"
)

func (e EnvelopeDistributeDistributionMethod) ToPointer() *EnvelopeDistributeDistributionMethod {
	return &e
}
func (e *EnvelopeDistributeDistributionMethod) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "EMAIL":
		fallthrough
	case "NONE":
		*e = EnvelopeDistributeDistributionMethod(v)
		return nil
	default:
		return fmt.Errorf("invalid value for EnvelopeDistributeDistributionMethod: %v", v)
	}
}

type EnvelopeDistributeLanguage string

const (
	EnvelopeDistributeLanguageDe   EnvelopeDistributeLanguage = "de"
	EnvelopeDistributeLanguageEn   EnvelopeDistributeLanguage = "en"
	EnvelopeDistributeLanguageFr   EnvelopeDistributeLanguage = "fr"
	EnvelopeDistributeLanguageEs   EnvelopeDistributeLanguage = "es"
	EnvelopeDistributeLanguageIt   EnvelopeDistributeLanguage = "it"
	EnvelopeDistributeLanguageNl   EnvelopeDistributeLanguage = "nl"
	EnvelopeDistributeLanguagePl   EnvelopeDistributeLanguage = "pl"
	EnvelopeDistributeLanguagePtBr EnvelopeDistributeLanguage = "pt-BR"
	EnvelopeDistributeLanguageJa   EnvelopeDistributeLanguage = "ja"
	EnvelopeDistributeLanguageKo   EnvelopeDistributeLanguage = "ko"
	EnvelopeDistributeLanguageZh   EnvelopeDistributeLanguage = "zh"
)

func (e EnvelopeDistributeLanguage) ToPointer() *EnvelopeDistributeLanguage {
	return &e
}
func (e *EnvelopeDistributeLanguage) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "de":
		fallthrough
	case "en":
		fallthrough
	case "fr":
		fallthrough
	case "es":
		fallthrough
	case "it":
		fallthrough
	case "nl":
		fallthrough
	case "pl":
		fallthrough
	case "pt-BR":
		fallthrough
	case "ja":
		fallthrough
	case "ko":
		fallthrough
	case "zh":
		*e = EnvelopeDistributeLanguage(v)
		return nil
	default:
		return fmt.Errorf("invalid value for EnvelopeDistributeLanguage: %v", v)
	}
}

type EnvelopeDistributeEmailSettings struct {
	RecipientSigningRequest *bool `default:"true" json:"recipientSigningRequest"`
	RecipientRemoved        *bool `default:"true" json:"recipientRemoved"`
	RecipientSigned         *bool `default:"true" json:"recipientSigned"`
	DocumentPending         *bool `default:"true" json:"documentPending"`
	DocumentCompleted       *bool `default:"true" json:"documentCompleted"`
	DocumentDeleted         *bool `default:"true" json:"documentDeleted"`
	OwnerDocumentCompleted  *bool `default:"true" json:"ownerDocumentCompleted"`
}

func (e EnvelopeDistributeEmailSettings) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *EnvelopeDistributeEmailSettings) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (e *EnvelopeDistributeEmailSettings) GetRecipientSigningRequest() *bool {
	if e == nil {
		return nil
	}
	return e.RecipientSigningRequest
}

func (e *EnvelopeDistributeEmailSettings) GetRecipientRemoved() *bool {
	if e == nil {
		return nil
	}
	return e.RecipientRemoved
}

func (e *EnvelopeDistributeEmailSettings) GetRecipientSigned() *bool {
	if e == nil {
		return nil
	}
	return e.RecipientSigned
}

func (e *EnvelopeDistributeEmailSettings) GetDocumentPending() *bool {
	if e == nil {
		return nil
	}
	return e.DocumentPending
}

func (e *EnvelopeDistributeEmailSettings) GetDocumentCompleted() *bool {
	if e == nil {
		return nil
	}
	return e.DocumentCompleted
}

func (e *EnvelopeDistributeEmailSettings) GetDocumentDeleted() *bool {
	if e == nil {
		return nil
	}
	return e.DocumentDeleted
}

func (e *EnvelopeDistributeEmailSettings) GetOwnerDocumentCompleted() *bool {
	if e == nil {
		return nil
	}
	return e.OwnerDocumentCompleted
}

type EnvelopeDistributeMeta struct {
	Subject            *string                               `json:"subject,omitempty"`
	Message            *string                               `json:"message,omitempty"`
	Timezone           *string                               `json:"timezone,omitempty"`
	DateFormat         *EnvelopeDistributeDateFormat         `json:"dateFormat,omitempty"`
	DistributionMethod *EnvelopeDistributeDistributionMethod `json:"distributionMethod,omitempty"`
	RedirectURL        *string                               `json:"redirectUrl,omitempty"`
	Language           *EnvelopeDistributeLanguage           `json:"language,omitempty"`
	EmailID            *string                               `json:"emailId,omitempty"`
	EmailReplyTo       *string                               `json:"emailReplyTo,omitempty"`
	EmailSettings      *EnvelopeDistributeEmailSettings      `json:"emailSettings,omitempty"`
}

func (e *EnvelopeDistributeMeta) GetSubject() *string {
	if e == nil {
		return nil
	}
	return e.Subject
}

func (e *EnvelopeDistributeMeta) GetMessage() *string {
	if e == nil {
		return nil
	}
	return e.Message
}

func (e *EnvelopeDistributeMeta) GetTimezone() *string {
	if e == nil {
		return nil
	}
	return e.Timezone
}

func (e *EnvelopeDistributeMeta) GetDateFormat() *EnvelopeDistributeDateFormat {
	if e == nil {
		return nil
	}
	return e.DateFormat
}

func (e *EnvelopeDistributeMeta) GetDistributionMethod() *EnvelopeDistributeDistributionMethod {
	if e == nil {
		return nil
	}
	return e.DistributionMethod
}

func (e *EnvelopeDistributeMeta) GetRedirectURL() *string {
	if e == nil {
		return nil
	}
	return e.RedirectURL
}

func (e *EnvelopeDistributeMeta) GetLanguage() *EnvelopeDistributeLanguage {
	if e == nil {
		return nil
	}
	return e.Language
}

func (e *EnvelopeDistributeMeta) GetEmailID() *string {
	if e == nil {
		return nil
	}
	return e.EmailID
}

func (e *EnvelopeDistributeMeta) GetEmailReplyTo() *string {
	if e == nil {
		return nil
	}
	return e.EmailReplyTo
}

func (e *EnvelopeDistributeMeta) GetEmailSettings() *EnvelopeDistributeEmailSettings {
	if e == nil {
		return nil
	}
	return e.EmailSettings
}

type EnvelopeDistributeRequest struct {
	EnvelopeID string                  `json:"envelopeId"`
	Meta       *EnvelopeDistributeMeta `json:"meta,omitempty"`
}

func (e *EnvelopeDistributeRequest) GetEnvelopeID() string {
	if e == nil {
		return ""
	}
	return e.EnvelopeID
}

func (e *EnvelopeDistributeRequest) GetMeta() *EnvelopeDistributeMeta {
	if e == nil {
		return nil
	}
	return e.Meta
}

type EnvelopeDistributeRole string

const (
	EnvelopeDistributeRoleCc        EnvelopeDistributeRole = "CC"
	EnvelopeDistributeRoleSigner    EnvelopeDistributeRole = "SIGNER"
	EnvelopeDistributeRoleViewer    EnvelopeDistributeRole = "VIEWER"
	EnvelopeDistributeRoleApprover  EnvelopeDistributeRole = "APPROVER"
	EnvelopeDistributeRoleAssistant EnvelopeDistributeRole = "ASSISTANT"
)

func (e EnvelopeDistributeRole) ToPointer() *EnvelopeDistributeRole {
	return &e
}
func (e *EnvelopeDistributeRole) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "CC":
		fallthrough
	case "SIGNER":
		fallthrough
	case "VIEWER":
		fallthrough
	case "APPROVER":
		fallthrough
	case "ASSISTANT":
		*e = EnvelopeDistributeRole(v)
		return nil
	default:
		return fmt.Errorf("invalid value for EnvelopeDistributeRole: %v", v)
	}
}

type EnvelopeDistributeRecipient struct {
	ID           float64                `json:"id"`
	Name         string                 `json:"name"`
	Email        string                 `json:"email"`
	Token        string                 `json:"token"`
	Role         EnvelopeDistributeRole `json:"role"`
	SigningOrder *float64               `json:"signingOrder"`
	SigningURL   string                 `json:"signingUrl"`
}

func (e *EnvelopeDistributeRecipient) GetID() float64 {
	if e == nil {
		return 0.0
	}
	return e.ID
}

func (e *EnvelopeDistributeRecipient) GetName() string {
	if e == nil {
		return ""
	}
	return e.Name
}

func (e *EnvelopeDistributeRecipient) GetEmail() string {
	if e == nil {
		return ""
	}
	return e.Email
}

func (e *EnvelopeDistributeRecipient) GetToken() string {
	if e == nil {
		return ""
	}
	return e.Token
}

func (e *EnvelopeDistributeRecipient) GetRole() EnvelopeDistributeRole {
	if e == nil {
		return EnvelopeDistributeRole("")
	}
	return e.Role
}

func (e *EnvelopeDistributeRecipient) GetSigningOrder() *float64 {
	if e == nil {
		return nil
	}
	return e.SigningOrder
}

func (e *EnvelopeDistributeRecipient) GetSigningURL() string {
	if e == nil {
		return ""
	}
	return e.SigningURL
}

// EnvelopeDistributeResponseBody - Successful response
type EnvelopeDistributeResponseBody struct {
	Success    bool                          `json:"success"`
	ID         string                        `json:"id"`
	Recipients []EnvelopeDistributeRecipient `json:"recipients"`
}

func (e *EnvelopeDistributeResponseBody) GetSuccess() bool {
	if e == nil {
		return false
	}
	return e.Success
}

func (e *EnvelopeDistributeResponseBody) GetID() string {
	if e == nil {
		return ""
	}
	return e.ID
}

func (e *EnvelopeDistributeResponseBody) GetRecipients() []EnvelopeDistributeRecipient {
	if e == nil {
		return []EnvelopeDistributeRecipient{}
	}
	return e.Recipients
}

type EnvelopeDistributeResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful response
	Object *EnvelopeDistributeResponseBody
}

func (e *EnvelopeDistributeResponse) GetHTTPMeta() components.HTTPMetadata {
	if e == nil {
		return components.HTTPMetadata{}
	}
	return e.HTTPMeta
}

func (e *EnvelopeDistributeResponse) GetObject() *EnvelopeDistributeResponseBody {
	if e == nil {
		return nil
	}
	return e.Object
}
