// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/documenso/sdk-go/models/components"
)

type FieldDeleteDocumentFieldRequest struct {
	FieldID float64 `json:"fieldId"`
}

func (f *FieldDeleteDocumentFieldRequest) GetFieldID() float64 {
	if f == nil {
		return 0.0
	}
	return f.FieldID
}

// FieldDeleteDocumentFieldResponseBody - Successful response
type FieldDeleteDocumentFieldResponseBody struct {
	Success bool `json:"success"`
}

func (f *FieldDeleteDocumentFieldResponseBody) GetSuccess() bool {
	if f == nil {
		return false
	}
	return f.Success
}

type FieldDeleteDocumentFieldResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful response
	Object *FieldDeleteDocumentFieldResponseBody
}

func (f *FieldDeleteDocumentFieldResponse) GetHTTPMeta() components.HTTPMetadata {
	if f == nil {
		return components.HTTPMetadata{}
	}
	return f.HTTPMeta
}

func (f *FieldDeleteDocumentFieldResponse) GetObject() *FieldDeleteDocumentFieldResponseBody {
	if f == nil {
		return nil
	}
	return f.Object
}
