// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/documenso/sdk-go/models/components"
)

type RecipientCreateTemplateRecipientRoleRequest string

const (
	RecipientCreateTemplateRecipientRoleRequestCc        RecipientCreateTemplateRecipientRoleRequest = "CC"
	RecipientCreateTemplateRecipientRoleRequestSigner    RecipientCreateTemplateRecipientRoleRequest = "SIGNER"
	RecipientCreateTemplateRecipientRoleRequestViewer    RecipientCreateTemplateRecipientRoleRequest = "VIEWER"
	RecipientCreateTemplateRecipientRoleRequestApprover  RecipientCreateTemplateRecipientRoleRequest = "APPROVER"
	RecipientCreateTemplateRecipientRoleRequestAssistant RecipientCreateTemplateRecipientRoleRequest = "ASSISTANT"
)

func (e RecipientCreateTemplateRecipientRoleRequest) ToPointer() *RecipientCreateTemplateRecipientRoleRequest {
	return &e
}
func (e *RecipientCreateTemplateRecipientRoleRequest) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "CC":
		fallthrough
	case "SIGNER":
		fallthrough
	case "VIEWER":
		fallthrough
	case "APPROVER":
		fallthrough
	case "ASSISTANT":
		*e = RecipientCreateTemplateRecipientRoleRequest(v)
		return nil
	default:
		return fmt.Errorf("invalid value for RecipientCreateTemplateRecipientRoleRequest: %v", v)
	}
}

// RecipientCreateTemplateRecipientAccessAuthRequest - The type of authentication required for the recipient to access the document.
type RecipientCreateTemplateRecipientAccessAuthRequest string

const (
	RecipientCreateTemplateRecipientAccessAuthRequestAccount RecipientCreateTemplateRecipientAccessAuthRequest = "ACCOUNT"
)

func (e RecipientCreateTemplateRecipientAccessAuthRequest) ToPointer() *RecipientCreateTemplateRecipientAccessAuthRequest {
	return &e
}
func (e *RecipientCreateTemplateRecipientAccessAuthRequest) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "ACCOUNT":
		*e = RecipientCreateTemplateRecipientAccessAuthRequest(v)
		return nil
	default:
		return fmt.Errorf("invalid value for RecipientCreateTemplateRecipientAccessAuthRequest: %v", v)
	}
}

// RecipientCreateTemplateRecipientActionAuthRequest - The type of authentication required for the recipient to sign the document.
type RecipientCreateTemplateRecipientActionAuthRequest string

const (
	RecipientCreateTemplateRecipientActionAuthRequestAccount       RecipientCreateTemplateRecipientActionAuthRequest = "ACCOUNT"
	RecipientCreateTemplateRecipientActionAuthRequestPasskey       RecipientCreateTemplateRecipientActionAuthRequest = "PASSKEY"
	RecipientCreateTemplateRecipientActionAuthRequestTwoFactorAuth RecipientCreateTemplateRecipientActionAuthRequest = "TWO_FACTOR_AUTH"
	RecipientCreateTemplateRecipientActionAuthRequestPassword      RecipientCreateTemplateRecipientActionAuthRequest = "PASSWORD"
	RecipientCreateTemplateRecipientActionAuthRequestExplicitNone  RecipientCreateTemplateRecipientActionAuthRequest = "EXPLICIT_NONE"
)

func (e RecipientCreateTemplateRecipientActionAuthRequest) ToPointer() *RecipientCreateTemplateRecipientActionAuthRequest {
	return &e
}
func (e *RecipientCreateTemplateRecipientActionAuthRequest) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "ACCOUNT":
		fallthrough
	case "PASSKEY":
		fallthrough
	case "TWO_FACTOR_AUTH":
		fallthrough
	case "PASSWORD":
		fallthrough
	case "EXPLICIT_NONE":
		*e = RecipientCreateTemplateRecipientActionAuthRequest(v)
		return nil
	default:
		return fmt.Errorf("invalid value for RecipientCreateTemplateRecipientActionAuthRequest: %v", v)
	}
}

type RecipientCreateTemplateRecipientRecipient struct {
	Email        string                                              `json:"email"`
	Name         string                                              `json:"name"`
	Role         RecipientCreateTemplateRecipientRoleRequest         `json:"role"`
	SigningOrder *float64                                            `json:"signingOrder,omitempty"`
	AccessAuth   []RecipientCreateTemplateRecipientAccessAuthRequest `json:"accessAuth,omitempty"`
	ActionAuth   []RecipientCreateTemplateRecipientActionAuthRequest `json:"actionAuth,omitempty"`
}

func (o *RecipientCreateTemplateRecipientRecipient) GetEmail() string {
	if o == nil {
		return ""
	}
	return o.Email
}

func (o *RecipientCreateTemplateRecipientRecipient) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *RecipientCreateTemplateRecipientRecipient) GetRole() RecipientCreateTemplateRecipientRoleRequest {
	if o == nil {
		return RecipientCreateTemplateRecipientRoleRequest("")
	}
	return o.Role
}

func (o *RecipientCreateTemplateRecipientRecipient) GetSigningOrder() *float64 {
	if o == nil {
		return nil
	}
	return o.SigningOrder
}

func (o *RecipientCreateTemplateRecipientRecipient) GetAccessAuth() []RecipientCreateTemplateRecipientAccessAuthRequest {
	if o == nil {
		return nil
	}
	return o.AccessAuth
}

func (o *RecipientCreateTemplateRecipientRecipient) GetActionAuth() []RecipientCreateTemplateRecipientActionAuthRequest {
	if o == nil {
		return nil
	}
	return o.ActionAuth
}

type RecipientCreateTemplateRecipientRequest struct {
	TemplateID float64                                   `json:"templateId"`
	Recipient  RecipientCreateTemplateRecipientRecipient `json:"recipient"`
}

func (o *RecipientCreateTemplateRecipientRequest) GetTemplateID() float64 {
	if o == nil {
		return 0.0
	}
	return o.TemplateID
}

func (o *RecipientCreateTemplateRecipientRequest) GetRecipient() RecipientCreateTemplateRecipientRecipient {
	if o == nil {
		return RecipientCreateTemplateRecipientRecipient{}
	}
	return o.Recipient
}

type RecipientCreateTemplateRecipientRoleResponse string

const (
	RecipientCreateTemplateRecipientRoleResponseCc        RecipientCreateTemplateRecipientRoleResponse = "CC"
	RecipientCreateTemplateRecipientRoleResponseSigner    RecipientCreateTemplateRecipientRoleResponse = "SIGNER"
	RecipientCreateTemplateRecipientRoleResponseViewer    RecipientCreateTemplateRecipientRoleResponse = "VIEWER"
	RecipientCreateTemplateRecipientRoleResponseApprover  RecipientCreateTemplateRecipientRoleResponse = "APPROVER"
	RecipientCreateTemplateRecipientRoleResponseAssistant RecipientCreateTemplateRecipientRoleResponse = "ASSISTANT"
)

func (e RecipientCreateTemplateRecipientRoleResponse) ToPointer() *RecipientCreateTemplateRecipientRoleResponse {
	return &e
}
func (e *RecipientCreateTemplateRecipientRoleResponse) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "CC":
		fallthrough
	case "SIGNER":
		fallthrough
	case "VIEWER":
		fallthrough
	case "APPROVER":
		fallthrough
	case "ASSISTANT":
		*e = RecipientCreateTemplateRecipientRoleResponse(v)
		return nil
	default:
		return fmt.Errorf("invalid value for RecipientCreateTemplateRecipientRoleResponse: %v", v)
	}
}

type RecipientCreateTemplateRecipientReadStatus string

const (
	RecipientCreateTemplateRecipientReadStatusNotOpened RecipientCreateTemplateRecipientReadStatus = "NOT_OPENED"
	RecipientCreateTemplateRecipientReadStatusOpened    RecipientCreateTemplateRecipientReadStatus = "OPENED"
)

func (e RecipientCreateTemplateRecipientReadStatus) ToPointer() *RecipientCreateTemplateRecipientReadStatus {
	return &e
}
func (e *RecipientCreateTemplateRecipientReadStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "NOT_OPENED":
		fallthrough
	case "OPENED":
		*e = RecipientCreateTemplateRecipientReadStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for RecipientCreateTemplateRecipientReadStatus: %v", v)
	}
}

type RecipientCreateTemplateRecipientSigningStatus string

const (
	RecipientCreateTemplateRecipientSigningStatusNotSigned RecipientCreateTemplateRecipientSigningStatus = "NOT_SIGNED"
	RecipientCreateTemplateRecipientSigningStatusSigned    RecipientCreateTemplateRecipientSigningStatus = "SIGNED"
	RecipientCreateTemplateRecipientSigningStatusRejected  RecipientCreateTemplateRecipientSigningStatus = "REJECTED"
)

func (e RecipientCreateTemplateRecipientSigningStatus) ToPointer() *RecipientCreateTemplateRecipientSigningStatus {
	return &e
}
func (e *RecipientCreateTemplateRecipientSigningStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "NOT_SIGNED":
		fallthrough
	case "SIGNED":
		fallthrough
	case "REJECTED":
		*e = RecipientCreateTemplateRecipientSigningStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for RecipientCreateTemplateRecipientSigningStatus: %v", v)
	}
}

type RecipientCreateTemplateRecipientSendStatus string

const (
	RecipientCreateTemplateRecipientSendStatusNotSent RecipientCreateTemplateRecipientSendStatus = "NOT_SENT"
	RecipientCreateTemplateRecipientSendStatusSent    RecipientCreateTemplateRecipientSendStatus = "SENT"
)

func (e RecipientCreateTemplateRecipientSendStatus) ToPointer() *RecipientCreateTemplateRecipientSendStatus {
	return &e
}
func (e *RecipientCreateTemplateRecipientSendStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "NOT_SENT":
		fallthrough
	case "SENT":
		*e = RecipientCreateTemplateRecipientSendStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for RecipientCreateTemplateRecipientSendStatus: %v", v)
	}
}

// RecipientCreateTemplateRecipientAccessAuthResponse - The type of authentication required for the recipient to access the document.
type RecipientCreateTemplateRecipientAccessAuthResponse string

const (
	RecipientCreateTemplateRecipientAccessAuthResponseAccount RecipientCreateTemplateRecipientAccessAuthResponse = "ACCOUNT"
)

func (e RecipientCreateTemplateRecipientAccessAuthResponse) ToPointer() *RecipientCreateTemplateRecipientAccessAuthResponse {
	return &e
}
func (e *RecipientCreateTemplateRecipientAccessAuthResponse) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "ACCOUNT":
		*e = RecipientCreateTemplateRecipientAccessAuthResponse(v)
		return nil
	default:
		return fmt.Errorf("invalid value for RecipientCreateTemplateRecipientAccessAuthResponse: %v", v)
	}
}

// RecipientCreateTemplateRecipientActionAuthResponse - The type of authentication required for the recipient to sign the document.
type RecipientCreateTemplateRecipientActionAuthResponse string

const (
	RecipientCreateTemplateRecipientActionAuthResponseAccount       RecipientCreateTemplateRecipientActionAuthResponse = "ACCOUNT"
	RecipientCreateTemplateRecipientActionAuthResponsePasskey       RecipientCreateTemplateRecipientActionAuthResponse = "PASSKEY"
	RecipientCreateTemplateRecipientActionAuthResponseTwoFactorAuth RecipientCreateTemplateRecipientActionAuthResponse = "TWO_FACTOR_AUTH"
	RecipientCreateTemplateRecipientActionAuthResponsePassword      RecipientCreateTemplateRecipientActionAuthResponse = "PASSWORD"
	RecipientCreateTemplateRecipientActionAuthResponseExplicitNone  RecipientCreateTemplateRecipientActionAuthResponse = "EXPLICIT_NONE"
)

func (e RecipientCreateTemplateRecipientActionAuthResponse) ToPointer() *RecipientCreateTemplateRecipientActionAuthResponse {
	return &e
}
func (e *RecipientCreateTemplateRecipientActionAuthResponse) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "ACCOUNT":
		fallthrough
	case "PASSKEY":
		fallthrough
	case "TWO_FACTOR_AUTH":
		fallthrough
	case "PASSWORD":
		fallthrough
	case "EXPLICIT_NONE":
		*e = RecipientCreateTemplateRecipientActionAuthResponse(v)
		return nil
	default:
		return fmt.Errorf("invalid value for RecipientCreateTemplateRecipientActionAuthResponse: %v", v)
	}
}

type RecipientCreateTemplateRecipientAuthOptions struct {
	AccessAuth []RecipientCreateTemplateRecipientAccessAuthResponse `json:"accessAuth"`
	ActionAuth []RecipientCreateTemplateRecipientActionAuthResponse `json:"actionAuth"`
}

func (o *RecipientCreateTemplateRecipientAuthOptions) GetAccessAuth() []RecipientCreateTemplateRecipientAccessAuthResponse {
	if o == nil {
		return []RecipientCreateTemplateRecipientAccessAuthResponse{}
	}
	return o.AccessAuth
}

func (o *RecipientCreateTemplateRecipientAuthOptions) GetActionAuth() []RecipientCreateTemplateRecipientActionAuthResponse {
	if o == nil {
		return []RecipientCreateTemplateRecipientActionAuthResponse{}
	}
	return o.ActionAuth
}

// RecipientCreateTemplateRecipientResponseBody - Successful response
type RecipientCreateTemplateRecipientResponseBody struct {
	Role              RecipientCreateTemplateRecipientRoleResponse  `json:"role"`
	ReadStatus        RecipientCreateTemplateRecipientReadStatus    `json:"readStatus"`
	SigningStatus     RecipientCreateTemplateRecipientSigningStatus `json:"signingStatus"`
	SendStatus        RecipientCreateTemplateRecipientSendStatus    `json:"sendStatus"`
	ID                float64                                       `json:"id"`
	DocumentID        *float64                                      `json:"documentId"`
	TemplateID        *float64                                      `json:"templateId"`
	Email             string                                        `json:"email"`
	Name              string                                        `json:"name"`
	Token             string                                        `json:"token"`
	DocumentDeletedAt *string                                       `json:"documentDeletedAt"`
	Expired           *string                                       `json:"expired"`
	SignedAt          *string                                       `json:"signedAt"`
	AuthOptions       *RecipientCreateTemplateRecipientAuthOptions  `json:"authOptions"`
	// The order in which the recipient should sign the document. Only works if the document is set to sequential signing.
	SigningOrder    *float64 `json:"signingOrder"`
	RejectionReason *string  `json:"rejectionReason"`
}

func (o *RecipientCreateTemplateRecipientResponseBody) GetRole() RecipientCreateTemplateRecipientRoleResponse {
	if o == nil {
		return RecipientCreateTemplateRecipientRoleResponse("")
	}
	return o.Role
}

func (o *RecipientCreateTemplateRecipientResponseBody) GetReadStatus() RecipientCreateTemplateRecipientReadStatus {
	if o == nil {
		return RecipientCreateTemplateRecipientReadStatus("")
	}
	return o.ReadStatus
}

func (o *RecipientCreateTemplateRecipientResponseBody) GetSigningStatus() RecipientCreateTemplateRecipientSigningStatus {
	if o == nil {
		return RecipientCreateTemplateRecipientSigningStatus("")
	}
	return o.SigningStatus
}

func (o *RecipientCreateTemplateRecipientResponseBody) GetSendStatus() RecipientCreateTemplateRecipientSendStatus {
	if o == nil {
		return RecipientCreateTemplateRecipientSendStatus("")
	}
	return o.SendStatus
}

func (o *RecipientCreateTemplateRecipientResponseBody) GetID() float64 {
	if o == nil {
		return 0.0
	}
	return o.ID
}

func (o *RecipientCreateTemplateRecipientResponseBody) GetDocumentID() *float64 {
	if o == nil {
		return nil
	}
	return o.DocumentID
}

func (o *RecipientCreateTemplateRecipientResponseBody) GetTemplateID() *float64 {
	if o == nil {
		return nil
	}
	return o.TemplateID
}

func (o *RecipientCreateTemplateRecipientResponseBody) GetEmail() string {
	if o == nil {
		return ""
	}
	return o.Email
}

func (o *RecipientCreateTemplateRecipientResponseBody) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *RecipientCreateTemplateRecipientResponseBody) GetToken() string {
	if o == nil {
		return ""
	}
	return o.Token
}

func (o *RecipientCreateTemplateRecipientResponseBody) GetDocumentDeletedAt() *string {
	if o == nil {
		return nil
	}
	return o.DocumentDeletedAt
}

func (o *RecipientCreateTemplateRecipientResponseBody) GetExpired() *string {
	if o == nil {
		return nil
	}
	return o.Expired
}

func (o *RecipientCreateTemplateRecipientResponseBody) GetSignedAt() *string {
	if o == nil {
		return nil
	}
	return o.SignedAt
}

func (o *RecipientCreateTemplateRecipientResponseBody) GetAuthOptions() *RecipientCreateTemplateRecipientAuthOptions {
	if o == nil {
		return nil
	}
	return o.AuthOptions
}

func (o *RecipientCreateTemplateRecipientResponseBody) GetSigningOrder() *float64 {
	if o == nil {
		return nil
	}
	return o.SigningOrder
}

func (o *RecipientCreateTemplateRecipientResponseBody) GetRejectionReason() *string {
	if o == nil {
		return nil
	}
	return o.RejectionReason
}

type RecipientCreateTemplateRecipientResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Successful response
	Object *RecipientCreateTemplateRecipientResponseBody
}

func (o *RecipientCreateTemplateRecipientResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *RecipientCreateTemplateRecipientResponse) GetObject() *RecipientCreateTemplateRecipientResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
