// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apierrors

import (
	"encoding/json"
	"github.com/documenso/sdk-go/models/components"
)

type DocumentCreateDocumentTemporaryInternalServerErrorIssue struct {
	Message string `json:"message"`
}

func (d *DocumentCreateDocumentTemporaryInternalServerErrorIssue) GetMessage() string {
	if d == nil {
		return ""
	}
	return d.Message
}

// DocumentCreateDocumentTemporaryInternalServerError - Internal server error
type DocumentCreateDocumentTemporaryInternalServerError struct {
	Message  string                                                    `json:"message"`
	Code     string                                                    `json:"code"`
	Issues   []DocumentCreateDocumentTemporaryInternalServerErrorIssue `json:"issues,omitempty"`
	HTTPMeta components.HTTPMetadata                                   `json:"-"`
}

var _ error = &DocumentCreateDocumentTemporaryInternalServerError{}

func (e *DocumentCreateDocumentTemporaryInternalServerError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

type DocumentCreateDocumentTemporaryForbiddenIssue struct {
	Message string `json:"message"`
}

func (d *DocumentCreateDocumentTemporaryForbiddenIssue) GetMessage() string {
	if d == nil {
		return ""
	}
	return d.Message
}

// DocumentCreateDocumentTemporaryForbiddenError - Insufficient access
type DocumentCreateDocumentTemporaryForbiddenError struct {
	Message  string                                          `json:"message"`
	Code     string                                          `json:"code"`
	Issues   []DocumentCreateDocumentTemporaryForbiddenIssue `json:"issues,omitempty"`
	HTTPMeta components.HTTPMetadata                         `json:"-"`
}

var _ error = &DocumentCreateDocumentTemporaryForbiddenError{}

func (e *DocumentCreateDocumentTemporaryForbiddenError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

type DocumentCreateDocumentTemporaryUnauthorizedIssue struct {
	Message string `json:"message"`
}

func (d *DocumentCreateDocumentTemporaryUnauthorizedIssue) GetMessage() string {
	if d == nil {
		return ""
	}
	return d.Message
}

// DocumentCreateDocumentTemporaryUnauthorizedError - Authorization not provided
type DocumentCreateDocumentTemporaryUnauthorizedError struct {
	Message  string                                             `json:"message"`
	Code     string                                             `json:"code"`
	Issues   []DocumentCreateDocumentTemporaryUnauthorizedIssue `json:"issues,omitempty"`
	HTTPMeta components.HTTPMetadata                            `json:"-"`
}

var _ error = &DocumentCreateDocumentTemporaryUnauthorizedError{}

func (e *DocumentCreateDocumentTemporaryUnauthorizedError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

type DocumentCreateDocumentTemporaryBadRequestIssue struct {
	Message string `json:"message"`
}

func (d *DocumentCreateDocumentTemporaryBadRequestIssue) GetMessage() string {
	if d == nil {
		return ""
	}
	return d.Message
}

// DocumentCreateDocumentTemporaryBadRequestError - Invalid input data
type DocumentCreateDocumentTemporaryBadRequestError struct {
	Message  string                                           `json:"message"`
	Code     string                                           `json:"code"`
	Issues   []DocumentCreateDocumentTemporaryBadRequestIssue `json:"issues,omitempty"`
	HTTPMeta components.HTTPMetadata                          `json:"-"`
}

var _ error = &DocumentCreateDocumentTemporaryBadRequestError{}

func (e *DocumentCreateDocumentTemporaryBadRequestError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
