// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apierrors

import (
	"encoding/json"
	"github.com/documenso/sdk-go/models/components"
)

type DocumentGetDocumentWithDetailsByIDInternalServerErrorIssue struct {
	Message string `json:"message"`
}

func (o *DocumentGetDocumentWithDetailsByIDInternalServerErrorIssue) GetMessage() string {
	if o == nil {
		return ""
	}
	return o.Message
}

// DocumentGetDocumentWithDetailsByIDInternalServerError - Internal server error
type DocumentGetDocumentWithDetailsByIDInternalServerError struct {
	Message  string                                                       `json:"message"`
	Code     string                                                       `json:"code"`
	Issues   []DocumentGetDocumentWithDetailsByIDInternalServerErrorIssue `json:"issues,omitempty"`
	HTTPMeta components.HTTPMetadata                                      `json:"-"`
}

var _ error = &DocumentGetDocumentWithDetailsByIDInternalServerError{}

func (e *DocumentGetDocumentWithDetailsByIDInternalServerError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

type DocumentGetDocumentWithDetailsByIDNotFoundIssue struct {
	Message string `json:"message"`
}

func (o *DocumentGetDocumentWithDetailsByIDNotFoundIssue) GetMessage() string {
	if o == nil {
		return ""
	}
	return o.Message
}

// DocumentGetDocumentWithDetailsByIDNotFoundError - Not found
type DocumentGetDocumentWithDetailsByIDNotFoundError struct {
	Message  string                                            `json:"message"`
	Code     string                                            `json:"code"`
	Issues   []DocumentGetDocumentWithDetailsByIDNotFoundIssue `json:"issues,omitempty"`
	HTTPMeta components.HTTPMetadata                           `json:"-"`
}

var _ error = &DocumentGetDocumentWithDetailsByIDNotFoundError{}

func (e *DocumentGetDocumentWithDetailsByIDNotFoundError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

type DocumentGetDocumentWithDetailsByIDBadRequestIssue struct {
	Message string `json:"message"`
}

func (o *DocumentGetDocumentWithDetailsByIDBadRequestIssue) GetMessage() string {
	if o == nil {
		return ""
	}
	return o.Message
}

// DocumentGetDocumentWithDetailsByIDBadRequestError - Invalid input data
type DocumentGetDocumentWithDetailsByIDBadRequestError struct {
	Message  string                                              `json:"message"`
	Code     string                                              `json:"code"`
	Issues   []DocumentGetDocumentWithDetailsByIDBadRequestIssue `json:"issues,omitempty"`
	HTTPMeta components.HTTPMetadata                             `json:"-"`
}

var _ error = &DocumentGetDocumentWithDetailsByIDBadRequestError{}

func (e *DocumentGetDocumentWithDetailsByIDBadRequestError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
