// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apierrors

import (
	"encoding/json"
	"github.com/documenso/sdk-go/models/components"
)

type DocumentMoveDocumentToTeamDocumentsIssues struct {
	Message string `json:"message"`
}

func (o *DocumentMoveDocumentToTeamDocumentsIssues) GetMessage() string {
	if o == nil {
		return ""
	}
	return o.Message
}

// DocumentMoveDocumentToTeamDocumentsResponseBody - Internal server error
type DocumentMoveDocumentToTeamDocumentsResponseBody struct {
	Message  string                                      `json:"message"`
	Code     string                                      `json:"code"`
	Issues   []DocumentMoveDocumentToTeamDocumentsIssues `json:"issues,omitempty"`
	HTTPMeta components.HTTPMetadata                     `json:"-"`
}

var _ error = &DocumentMoveDocumentToTeamDocumentsResponseBody{}

func (e *DocumentMoveDocumentToTeamDocumentsResponseBody) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

type DocumentMoveDocumentToTeamIssues struct {
	Message string `json:"message"`
}

func (o *DocumentMoveDocumentToTeamIssues) GetMessage() string {
	if o == nil {
		return ""
	}
	return o.Message
}

// DocumentMoveDocumentToTeamResponseBody - Invalid input data
type DocumentMoveDocumentToTeamResponseBody struct {
	Message  string                             `json:"message"`
	Code     string                             `json:"code"`
	Issues   []DocumentMoveDocumentToTeamIssues `json:"issues,omitempty"`
	HTTPMeta components.HTTPMetadata            `json:"-"`
}

var _ error = &DocumentMoveDocumentToTeamResponseBody{}

func (e *DocumentMoveDocumentToTeamResponseBody) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
