// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apierrors

import (
	"encoding/json"
	"github.com/documenso/sdk-go/models/components"
)

type DocumentSendDocumentDocumentsIssues struct {
	Message string `json:"message"`
}

func (o *DocumentSendDocumentDocumentsIssues) GetMessage() string {
	if o == nil {
		return ""
	}
	return o.Message
}

// DocumentSendDocumentDocumentsResponseBody - Internal server error
type DocumentSendDocumentDocumentsResponseBody struct {
	Message  string                                `json:"message"`
	Code     string                                `json:"code"`
	Issues   []DocumentSendDocumentDocumentsIssues `json:"issues,omitempty"`
	HTTPMeta components.HTTPMetadata               `json:"-"`
}

var _ error = &DocumentSendDocumentDocumentsResponseBody{}

func (e *DocumentSendDocumentDocumentsResponseBody) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

type DocumentSendDocumentIssues struct {
	Message string `json:"message"`
}

func (o *DocumentSendDocumentIssues) GetMessage() string {
	if o == nil {
		return ""
	}
	return o.Message
}

// DocumentSendDocumentResponseBody - Invalid input data
type DocumentSendDocumentResponseBody struct {
	Message  string                       `json:"message"`
	Code     string                       `json:"code"`
	Issues   []DocumentSendDocumentIssues `json:"issues,omitempty"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &DocumentSendDocumentResponseBody{}

func (e *DocumentSendDocumentResponseBody) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
