// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apierrors

import (
	"encoding/json"
	"github.com/documenso/sdk-go/models/components"
)

type DocumentCreateDocumentTemporaryInternalServerErrorIssue struct {
	Message string `json:"message"`
}

func (o *DocumentCreateDocumentTemporaryInternalServerErrorIssue) GetMessage() string {
	if o == nil {
		return ""
	}
	return o.Message
}

// DocumentCreateDocumentTemporaryInternalServerError - Internal server error
type DocumentCreateDocumentTemporaryInternalServerError struct {
	Message  string                                                    `json:"message"`
	Code     string                                                    `json:"code"`
	Issues   []DocumentCreateDocumentTemporaryInternalServerErrorIssue `json:"issues,omitempty"`
	HTTPMeta components.HTTPMetadata                                   `json:"-"`
}

var _ error = &DocumentCreateDocumentTemporaryInternalServerError{}

func (e *DocumentCreateDocumentTemporaryInternalServerError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

type DocumentCreateDocumentTemporaryBadRequestIssue struct {
	Message string `json:"message"`
}

func (o *DocumentCreateDocumentTemporaryBadRequestIssue) GetMessage() string {
	if o == nil {
		return ""
	}
	return o.Message
}

// DocumentCreateDocumentTemporaryBadRequestError - Invalid input data
type DocumentCreateDocumentTemporaryBadRequestError struct {
	Message  string                                           `json:"message"`
	Code     string                                           `json:"code"`
	Issues   []DocumentCreateDocumentTemporaryBadRequestIssue `json:"issues,omitempty"`
	HTTPMeta components.HTTPMetadata                          `json:"-"`
}

var _ error = &DocumentCreateDocumentTemporaryBadRequestError{}

func (e *DocumentCreateDocumentTemporaryBadRequestError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
