// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apierrors

import (
	"encoding/json"
	"github.com/documenso/sdk-go/models/components"
)

type DocumentMoveDocumentToTeamInternalServerErrorIssue struct {
	Message string `json:"message"`
}

func (o *DocumentMoveDocumentToTeamInternalServerErrorIssue) GetMessage() string {
	if o == nil {
		return ""
	}
	return o.Message
}

// DocumentMoveDocumentToTeamInternalServerError - Internal server error
type DocumentMoveDocumentToTeamInternalServerError struct {
	Message  string                                               `json:"message"`
	Code     string                                               `json:"code"`
	Issues   []DocumentMoveDocumentToTeamInternalServerErrorIssue `json:"issues,omitempty"`
	HTTPMeta components.HTTPMetadata                              `json:"-"`
}

var _ error = &DocumentMoveDocumentToTeamInternalServerError{}

func (e *DocumentMoveDocumentToTeamInternalServerError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

type DocumentMoveDocumentToTeamBadRequestIssue struct {
	Message string `json:"message"`
}

func (o *DocumentMoveDocumentToTeamBadRequestIssue) GetMessage() string {
	if o == nil {
		return ""
	}
	return o.Message
}

// DocumentMoveDocumentToTeamBadRequestError - Invalid input data
type DocumentMoveDocumentToTeamBadRequestError struct {
	Message  string                                      `json:"message"`
	Code     string                                      `json:"code"`
	Issues   []DocumentMoveDocumentToTeamBadRequestIssue `json:"issues,omitempty"`
	HTTPMeta components.HTTPMetadata                     `json:"-"`
}

var _ error = &DocumentMoveDocumentToTeamBadRequestError{}

func (e *DocumentMoveDocumentToTeamBadRequestError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
