// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apierrors

import (
	"encoding/json"
	"github.com/documenso/sdk-go/models/components"
)

type DocumentDistributeInternalServerErrorIssue struct {
	Message string `json:"message"`
}

func (d *DocumentDistributeInternalServerErrorIssue) GetMessage() string {
	if d == nil {
		return ""
	}
	return d.Message
}

// DocumentDistributeInternalServerError - Internal server error
type DocumentDistributeInternalServerError struct {
	Message  string                                       `json:"message"`
	Code     string                                       `json:"code"`
	Issues   []DocumentDistributeInternalServerErrorIssue `json:"issues,omitempty"`
	HTTPMeta components.HTTPMetadata                      `json:"-"`
}

var _ error = &DocumentDistributeInternalServerError{}

func (e *DocumentDistributeInternalServerError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

type DocumentDistributeForbiddenIssue struct {
	Message string `json:"message"`
}

func (d *DocumentDistributeForbiddenIssue) GetMessage() string {
	if d == nil {
		return ""
	}
	return d.Message
}

// DocumentDistributeForbiddenError - Insufficient access
type DocumentDistributeForbiddenError struct {
	Message  string                             `json:"message"`
	Code     string                             `json:"code"`
	Issues   []DocumentDistributeForbiddenIssue `json:"issues,omitempty"`
	HTTPMeta components.HTTPMetadata            `json:"-"`
}

var _ error = &DocumentDistributeForbiddenError{}

func (e *DocumentDistributeForbiddenError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

type DocumentDistributeUnauthorizedIssue struct {
	Message string `json:"message"`
}

func (d *DocumentDistributeUnauthorizedIssue) GetMessage() string {
	if d == nil {
		return ""
	}
	return d.Message
}

// DocumentDistributeUnauthorizedError - Authorization not provided
type DocumentDistributeUnauthorizedError struct {
	Message  string                                `json:"message"`
	Code     string                                `json:"code"`
	Issues   []DocumentDistributeUnauthorizedIssue `json:"issues,omitempty"`
	HTTPMeta components.HTTPMetadata               `json:"-"`
}

var _ error = &DocumentDistributeUnauthorizedError{}

func (e *DocumentDistributeUnauthorizedError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

type DocumentDistributeBadRequestIssue struct {
	Message string `json:"message"`
}

func (d *DocumentDistributeBadRequestIssue) GetMessage() string {
	if d == nil {
		return ""
	}
	return d.Message
}

// DocumentDistributeBadRequestError - Invalid input data
type DocumentDistributeBadRequestError struct {
	Message  string                              `json:"message"`
	Code     string                              `json:"code"`
	Issues   []DocumentDistributeBadRequestIssue `json:"issues,omitempty"`
	HTTPMeta components.HTTPMetadata             `json:"-"`
}

var _ error = &DocumentDistributeBadRequestError{}

func (e *DocumentDistributeBadRequestError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
