// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apierrors

import (
	"encoding/json"
	"github.com/documenso/sdk-go/models/components"
)

type EnvelopeUseInternalServerErrorIssue struct {
	Message string `json:"message"`
}

func (e *EnvelopeUseInternalServerErrorIssue) GetMessage() string {
	if e == nil {
		return ""
	}
	return e.Message
}

// EnvelopeUseInternalServerError - Internal server error
type EnvelopeUseInternalServerError struct {
	Message  string                                `json:"message"`
	Code     string                                `json:"code"`
	Issues   []EnvelopeUseInternalServerErrorIssue `json:"issues,omitempty"`
	HTTPMeta components.HTTPMetadata               `json:"-"`
}

var _ error = &EnvelopeUseInternalServerError{}

func (e *EnvelopeUseInternalServerError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

type EnvelopeUseForbiddenIssue struct {
	Message string `json:"message"`
}

func (e *EnvelopeUseForbiddenIssue) GetMessage() string {
	if e == nil {
		return ""
	}
	return e.Message
}

// EnvelopeUseForbiddenError - Insufficient access
type EnvelopeUseForbiddenError struct {
	Message  string                      `json:"message"`
	Code     string                      `json:"code"`
	Issues   []EnvelopeUseForbiddenIssue `json:"issues,omitempty"`
	HTTPMeta components.HTTPMetadata     `json:"-"`
}

var _ error = &EnvelopeUseForbiddenError{}

func (e *EnvelopeUseForbiddenError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

type EnvelopeUseUnauthorizedIssue struct {
	Message string `json:"message"`
}

func (e *EnvelopeUseUnauthorizedIssue) GetMessage() string {
	if e == nil {
		return ""
	}
	return e.Message
}

// EnvelopeUseUnauthorizedError - Authorization not provided
type EnvelopeUseUnauthorizedError struct {
	Message  string                         `json:"message"`
	Code     string                         `json:"code"`
	Issues   []EnvelopeUseUnauthorizedIssue `json:"issues,omitempty"`
	HTTPMeta components.HTTPMetadata        `json:"-"`
}

var _ error = &EnvelopeUseUnauthorizedError{}

func (e *EnvelopeUseUnauthorizedError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

type EnvelopeUseBadRequestIssue struct {
	Message string `json:"message"`
}

func (e *EnvelopeUseBadRequestIssue) GetMessage() string {
	if e == nil {
		return ""
	}
	return e.Message
}

// EnvelopeUseBadRequestError - Invalid input data
type EnvelopeUseBadRequestError struct {
	Message  string                       `json:"message"`
	Code     string                       `json:"code"`
	Issues   []EnvelopeUseBadRequestIssue `json:"issues,omitempty"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &EnvelopeUseBadRequestError{}

func (e *EnvelopeUseBadRequestError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
