// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apierrors

import (
	"encoding/json"
)

type ErrorNOTFOUNDIssues struct {
	Message string `json:"message"`
}

func (o *ErrorNOTFOUNDIssues) GetMessage() string {
	if o == nil {
		return ""
	}
	return o.Message
}

// ErrorNOTFOUND - The error information
type ErrorNOTFOUND struct {
	// The error message
	Message string `json:"message"`
	// The error code
	Code string `json:"code"`
	// An array of issues that were responsible for the error
	Issues []ErrorNOTFOUNDIssues `json:"issues,omitempty"`
}

var _ error = &ErrorNOTFOUND{}

func (e *ErrorNOTFOUND) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
