// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apierrors

import (
	"encoding/json"
	"github.com/documenso/sdk-go/models/components"
)

type FieldCreateDocumentFieldDocumentsFieldsIssues struct {
	Message string `json:"message"`
}

func (o *FieldCreateDocumentFieldDocumentsFieldsIssues) GetMessage() string {
	if o == nil {
		return ""
	}
	return o.Message
}

// FieldCreateDocumentFieldDocumentsFieldsResponseBody - Internal server error
type FieldCreateDocumentFieldDocumentsFieldsResponseBody struct {
	Message  string                                          `json:"message"`
	Code     string                                          `json:"code"`
	Issues   []FieldCreateDocumentFieldDocumentsFieldsIssues `json:"issues,omitempty"`
	HTTPMeta components.HTTPMetadata                         `json:"-"`
}

var _ error = &FieldCreateDocumentFieldDocumentsFieldsResponseBody{}

func (e *FieldCreateDocumentFieldDocumentsFieldsResponseBody) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

type FieldCreateDocumentFieldIssues struct {
	Message string `json:"message"`
}

func (o *FieldCreateDocumentFieldIssues) GetMessage() string {
	if o == nil {
		return ""
	}
	return o.Message
}

// FieldCreateDocumentFieldResponseBody - Invalid input data
type FieldCreateDocumentFieldResponseBody struct {
	Message  string                           `json:"message"`
	Code     string                           `json:"code"`
	Issues   []FieldCreateDocumentFieldIssues `json:"issues,omitempty"`
	HTTPMeta components.HTTPMetadata          `json:"-"`
}

var _ error = &FieldCreateDocumentFieldResponseBody{}

func (e *FieldCreateDocumentFieldResponseBody) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
