// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apierrors

import (
	"encoding/json"
	"github.com/documenso/sdk-go/models/components"
)

type FieldCreateTemplateFieldsInternalServerErrorIssue struct {
	Message string `json:"message"`
}

func (o *FieldCreateTemplateFieldsInternalServerErrorIssue) GetMessage() string {
	if o == nil {
		return ""
	}
	return o.Message
}

// FieldCreateTemplateFieldsInternalServerError - Internal server error
type FieldCreateTemplateFieldsInternalServerError struct {
	Message  string                                              `json:"message"`
	Code     string                                              `json:"code"`
	Issues   []FieldCreateTemplateFieldsInternalServerErrorIssue `json:"issues,omitempty"`
	HTTPMeta components.HTTPMetadata                             `json:"-"`
}

var _ error = &FieldCreateTemplateFieldsInternalServerError{}

func (e *FieldCreateTemplateFieldsInternalServerError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

type FieldCreateTemplateFieldsBadRequestIssue struct {
	Message string `json:"message"`
}

func (o *FieldCreateTemplateFieldsBadRequestIssue) GetMessage() string {
	if o == nil {
		return ""
	}
	return o.Message
}

// FieldCreateTemplateFieldsBadRequestError - Invalid input data
type FieldCreateTemplateFieldsBadRequestError struct {
	Message  string                                     `json:"message"`
	Code     string                                     `json:"code"`
	Issues   []FieldCreateTemplateFieldsBadRequestIssue `json:"issues,omitempty"`
	HTTPMeta components.HTTPMetadata                    `json:"-"`
}

var _ error = &FieldCreateTemplateFieldsBadRequestError{}

func (e *FieldCreateTemplateFieldsBadRequestError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
