// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apierrors

import (
	"encoding/json"
	"github.com/documenso/sdk-go/models/components"
)

type RecipientCreateTemplateRecipientsInternalServerErrorIssue struct {
	Message string `json:"message"`
}

func (r *RecipientCreateTemplateRecipientsInternalServerErrorIssue) GetMessage() string {
	if r == nil {
		return ""
	}
	return r.Message
}

// RecipientCreateTemplateRecipientsInternalServerError - Internal server error
type RecipientCreateTemplateRecipientsInternalServerError struct {
	Message  string                                                      `json:"message"`
	Code     string                                                      `json:"code"`
	Issues   []RecipientCreateTemplateRecipientsInternalServerErrorIssue `json:"issues,omitempty"`
	HTTPMeta components.HTTPMetadata                                     `json:"-"`
}

var _ error = &RecipientCreateTemplateRecipientsInternalServerError{}

func (e *RecipientCreateTemplateRecipientsInternalServerError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

type RecipientCreateTemplateRecipientsBadRequestIssue struct {
	Message string `json:"message"`
}

func (r *RecipientCreateTemplateRecipientsBadRequestIssue) GetMessage() string {
	if r == nil {
		return ""
	}
	return r.Message
}

// RecipientCreateTemplateRecipientsBadRequestError - Invalid input data
type RecipientCreateTemplateRecipientsBadRequestError struct {
	Message  string                                             `json:"message"`
	Code     string                                             `json:"code"`
	Issues   []RecipientCreateTemplateRecipientsBadRequestIssue `json:"issues,omitempty"`
	HTTPMeta components.HTTPMetadata                            `json:"-"`
}

var _ error = &RecipientCreateTemplateRecipientsBadRequestError{}

func (e *RecipientCreateTemplateRecipientsBadRequestError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
