// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apierrors

import (
	"encoding/json"
	"github.com/documenso/sdk-go/models/components"
)

type RecipientCreateTemplateRecipientTemplatesRecipientsIssues struct {
	Message string `json:"message"`
}

func (o *RecipientCreateTemplateRecipientTemplatesRecipientsIssues) GetMessage() string {
	if o == nil {
		return ""
	}
	return o.Message
}

// RecipientCreateTemplateRecipientTemplatesRecipientsResponseBody - Internal server error
type RecipientCreateTemplateRecipientTemplatesRecipientsResponseBody struct {
	Message  string                                                      `json:"message"`
	Code     string                                                      `json:"code"`
	Issues   []RecipientCreateTemplateRecipientTemplatesRecipientsIssues `json:"issues,omitempty"`
	HTTPMeta components.HTTPMetadata                                     `json:"-"`
}

var _ error = &RecipientCreateTemplateRecipientTemplatesRecipientsResponseBody{}

func (e *RecipientCreateTemplateRecipientTemplatesRecipientsResponseBody) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

type RecipientCreateTemplateRecipientIssues struct {
	Message string `json:"message"`
}

func (o *RecipientCreateTemplateRecipientIssues) GetMessage() string {
	if o == nil {
		return ""
	}
	return o.Message
}

// RecipientCreateTemplateRecipientResponseBody - Invalid input data
type RecipientCreateTemplateRecipientResponseBody struct {
	Message  string                                   `json:"message"`
	Code     string                                   `json:"code"`
	Issues   []RecipientCreateTemplateRecipientIssues `json:"issues,omitempty"`
	HTTPMeta components.HTTPMetadata                  `json:"-"`
}

var _ error = &RecipientCreateTemplateRecipientResponseBody{}

func (e *RecipientCreateTemplateRecipientResponseBody) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
