// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apierrors

import (
	"encoding/json"
	"github.com/documenso/sdk-go/models/components"
)

type RecipientCreateDocumentRecipientsInternalServerErrorIssue struct {
	Message string `json:"message"`
}

func (r *RecipientCreateDocumentRecipientsInternalServerErrorIssue) GetMessage() string {
	if r == nil {
		return ""
	}
	return r.Message
}

// RecipientCreateDocumentRecipientsInternalServerError - Internal server error
type RecipientCreateDocumentRecipientsInternalServerError struct {
	Message  string                                                      `json:"message"`
	Code     string                                                      `json:"code"`
	Issues   []RecipientCreateDocumentRecipientsInternalServerErrorIssue `json:"issues,omitempty"`
	HTTPMeta components.HTTPMetadata                                     `json:"-"`
}

var _ error = &RecipientCreateDocumentRecipientsInternalServerError{}

func (e *RecipientCreateDocumentRecipientsInternalServerError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

type RecipientCreateDocumentRecipientsBadRequestIssue struct {
	Message string `json:"message"`
}

func (r *RecipientCreateDocumentRecipientsBadRequestIssue) GetMessage() string {
	if r == nil {
		return ""
	}
	return r.Message
}

// RecipientCreateDocumentRecipientsBadRequestError - Invalid input data
type RecipientCreateDocumentRecipientsBadRequestError struct {
	Message  string                                             `json:"message"`
	Code     string                                             `json:"code"`
	Issues   []RecipientCreateDocumentRecipientsBadRequestIssue `json:"issues,omitempty"`
	HTTPMeta components.HTTPMetadata                            `json:"-"`
}

var _ error = &RecipientCreateDocumentRecipientsBadRequestError{}

func (e *RecipientCreateDocumentRecipientsBadRequestError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
