// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apierrors

import (
	"encoding/json"
	"github.com/documenso/sdk-go/models/components"
)

type TemplateGetTemplateByIDTemplatesResponseIssues struct {
	Message string `json:"message"`
}

func (o *TemplateGetTemplateByIDTemplatesResponseIssues) GetMessage() string {
	if o == nil {
		return ""
	}
	return o.Message
}

// TemplateGetTemplateByIDTemplatesResponseResponseBody - Internal server error
type TemplateGetTemplateByIDTemplatesResponseResponseBody struct {
	Message  string                                           `json:"message"`
	Code     string                                           `json:"code"`
	Issues   []TemplateGetTemplateByIDTemplatesResponseIssues `json:"issues,omitempty"`
	HTTPMeta components.HTTPMetadata                          `json:"-"`
}

var _ error = &TemplateGetTemplateByIDTemplatesResponseResponseBody{}

func (e *TemplateGetTemplateByIDTemplatesResponseResponseBody) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

type TemplateGetTemplateByIDTemplatesIssues struct {
	Message string `json:"message"`
}

func (o *TemplateGetTemplateByIDTemplatesIssues) GetMessage() string {
	if o == nil {
		return ""
	}
	return o.Message
}

// TemplateGetTemplateByIDTemplatesResponseBody - Not found
type TemplateGetTemplateByIDTemplatesResponseBody struct {
	Message  string                                   `json:"message"`
	Code     string                                   `json:"code"`
	Issues   []TemplateGetTemplateByIDTemplatesIssues `json:"issues,omitempty"`
	HTTPMeta components.HTTPMetadata                  `json:"-"`
}

var _ error = &TemplateGetTemplateByIDTemplatesResponseBody{}

func (e *TemplateGetTemplateByIDTemplatesResponseBody) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

type TemplateGetTemplateByIDIssues struct {
	Message string `json:"message"`
}

func (o *TemplateGetTemplateByIDIssues) GetMessage() string {
	if o == nil {
		return ""
	}
	return o.Message
}

// TemplateGetTemplateByIDResponseBody - Invalid input data
type TemplateGetTemplateByIDResponseBody struct {
	Message  string                          `json:"message"`
	Code     string                          `json:"code"`
	Issues   []TemplateGetTemplateByIDIssues `json:"issues,omitempty"`
	HTTPMeta components.HTTPMetadata         `json:"-"`
}

var _ error = &TemplateGetTemplateByIDResponseBody{}

func (e *TemplateGetTemplateByIDResponseBody) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
