// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apierrors

import (
	"encoding/json"
	"github.com/documenso/sdk-go/models/components"
)

type TemplateGetTemplateByIDInternalServerErrorIssue struct {
	Message string `json:"message"`
}

func (t *TemplateGetTemplateByIDInternalServerErrorIssue) GetMessage() string {
	if t == nil {
		return ""
	}
	return t.Message
}

// TemplateGetTemplateByIDInternalServerError - Internal server error
type TemplateGetTemplateByIDInternalServerError struct {
	Message  string                                            `json:"message"`
	Code     string                                            `json:"code"`
	Issues   []TemplateGetTemplateByIDInternalServerErrorIssue `json:"issues,omitempty"`
	HTTPMeta components.HTTPMetadata                           `json:"-"`
}

var _ error = &TemplateGetTemplateByIDInternalServerError{}

func (e *TemplateGetTemplateByIDInternalServerError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

type TemplateGetTemplateByIDNotFoundIssue struct {
	Message string `json:"message"`
}

func (t *TemplateGetTemplateByIDNotFoundIssue) GetMessage() string {
	if t == nil {
		return ""
	}
	return t.Message
}

// TemplateGetTemplateByIDNotFoundError - Not found
type TemplateGetTemplateByIDNotFoundError struct {
	Message  string                                 `json:"message"`
	Code     string                                 `json:"code"`
	Issues   []TemplateGetTemplateByIDNotFoundIssue `json:"issues,omitempty"`
	HTTPMeta components.HTTPMetadata                `json:"-"`
}

var _ error = &TemplateGetTemplateByIDNotFoundError{}

func (e *TemplateGetTemplateByIDNotFoundError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

type TemplateGetTemplateByIDForbiddenIssue struct {
	Message string `json:"message"`
}

func (t *TemplateGetTemplateByIDForbiddenIssue) GetMessage() string {
	if t == nil {
		return ""
	}
	return t.Message
}

// TemplateGetTemplateByIDForbiddenError - Insufficient access
type TemplateGetTemplateByIDForbiddenError struct {
	Message  string                                  `json:"message"`
	Code     string                                  `json:"code"`
	Issues   []TemplateGetTemplateByIDForbiddenIssue `json:"issues,omitempty"`
	HTTPMeta components.HTTPMetadata                 `json:"-"`
}

var _ error = &TemplateGetTemplateByIDForbiddenError{}

func (e *TemplateGetTemplateByIDForbiddenError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

type TemplateGetTemplateByIDUnauthorizedIssue struct {
	Message string `json:"message"`
}

func (t *TemplateGetTemplateByIDUnauthorizedIssue) GetMessage() string {
	if t == nil {
		return ""
	}
	return t.Message
}

// TemplateGetTemplateByIDUnauthorizedError - Authorization not provided
type TemplateGetTemplateByIDUnauthorizedError struct {
	Message  string                                     `json:"message"`
	Code     string                                     `json:"code"`
	Issues   []TemplateGetTemplateByIDUnauthorizedIssue `json:"issues,omitempty"`
	HTTPMeta components.HTTPMetadata                    `json:"-"`
}

var _ error = &TemplateGetTemplateByIDUnauthorizedError{}

func (e *TemplateGetTemplateByIDUnauthorizedError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

type TemplateGetTemplateByIDBadRequestIssue struct {
	Message string `json:"message"`
}

func (t *TemplateGetTemplateByIDBadRequestIssue) GetMessage() string {
	if t == nil {
		return ""
	}
	return t.Message
}

// TemplateGetTemplateByIDBadRequestError - Invalid input data
type TemplateGetTemplateByIDBadRequestError struct {
	Message  string                                   `json:"message"`
	Code     string                                   `json:"code"`
	Issues   []TemplateGetTemplateByIDBadRequestIssue `json:"issues,omitempty"`
	HTTPMeta components.HTTPMetadata                  `json:"-"`
}

var _ error = &TemplateGetTemplateByIDBadRequestError{}

func (e *TemplateGetTemplateByIDBadRequestError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
