// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apierrors

import (
	"encoding/json"
	"github.com/documenso/sdk-go/models/components"
)

type TemplateDeleteTemplateTemplatesIssues struct {
	Message string `json:"message"`
}

func (o *TemplateDeleteTemplateTemplatesIssues) GetMessage() string {
	if o == nil {
		return ""
	}
	return o.Message
}

// TemplateDeleteTemplateTemplatesResponseBody - Internal server error
type TemplateDeleteTemplateTemplatesResponseBody struct {
	Message  string                                  `json:"message"`
	Code     string                                  `json:"code"`
	Issues   []TemplateDeleteTemplateTemplatesIssues `json:"issues,omitempty"`
	HTTPMeta components.HTTPMetadata                 `json:"-"`
}

var _ error = &TemplateDeleteTemplateTemplatesResponseBody{}

func (e *TemplateDeleteTemplateTemplatesResponseBody) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

type TemplateDeleteTemplateIssues struct {
	Message string `json:"message"`
}

func (o *TemplateDeleteTemplateIssues) GetMessage() string {
	if o == nil {
		return ""
	}
	return o.Message
}

// TemplateDeleteTemplateResponseBody - Invalid input data
type TemplateDeleteTemplateResponseBody struct {
	Message  string                         `json:"message"`
	Code     string                         `json:"code"`
	Issues   []TemplateDeleteTemplateIssues `json:"issues,omitempty"`
	HTTPMeta components.HTTPMetadata        `json:"-"`
}

var _ error = &TemplateDeleteTemplateResponseBody{}

func (e *TemplateDeleteTemplateResponseBody) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
