// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package apierrors

import (
	"encoding/json"
	"github.com/documenso/sdk-go/models/components"
)

type TemplateCreateDocumentFromTemplateInternalServerErrorIssue struct {
	Message string `json:"message"`
}

func (t *TemplateCreateDocumentFromTemplateInternalServerErrorIssue) GetMessage() string {
	if t == nil {
		return ""
	}
	return t.Message
}

// TemplateCreateDocumentFromTemplateInternalServerError - Internal server error
type TemplateCreateDocumentFromTemplateInternalServerError struct {
	Message  string                                                       `json:"message"`
	Code     string                                                       `json:"code"`
	Issues   []TemplateCreateDocumentFromTemplateInternalServerErrorIssue `json:"issues,omitempty"`
	HTTPMeta components.HTTPMetadata                                      `json:"-"`
}

var _ error = &TemplateCreateDocumentFromTemplateInternalServerError{}

func (e *TemplateCreateDocumentFromTemplateInternalServerError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

type TemplateCreateDocumentFromTemplateForbiddenIssue struct {
	Message string `json:"message"`
}

func (t *TemplateCreateDocumentFromTemplateForbiddenIssue) GetMessage() string {
	if t == nil {
		return ""
	}
	return t.Message
}

// TemplateCreateDocumentFromTemplateForbiddenError - Insufficient access
type TemplateCreateDocumentFromTemplateForbiddenError struct {
	Message  string                                             `json:"message"`
	Code     string                                             `json:"code"`
	Issues   []TemplateCreateDocumentFromTemplateForbiddenIssue `json:"issues,omitempty"`
	HTTPMeta components.HTTPMetadata                            `json:"-"`
}

var _ error = &TemplateCreateDocumentFromTemplateForbiddenError{}

func (e *TemplateCreateDocumentFromTemplateForbiddenError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

type TemplateCreateDocumentFromTemplateUnauthorizedIssue struct {
	Message string `json:"message"`
}

func (t *TemplateCreateDocumentFromTemplateUnauthorizedIssue) GetMessage() string {
	if t == nil {
		return ""
	}
	return t.Message
}

// TemplateCreateDocumentFromTemplateUnauthorizedError - Authorization not provided
type TemplateCreateDocumentFromTemplateUnauthorizedError struct {
	Message  string                                                `json:"message"`
	Code     string                                                `json:"code"`
	Issues   []TemplateCreateDocumentFromTemplateUnauthorizedIssue `json:"issues,omitempty"`
	HTTPMeta components.HTTPMetadata                               `json:"-"`
}

var _ error = &TemplateCreateDocumentFromTemplateUnauthorizedError{}

func (e *TemplateCreateDocumentFromTemplateUnauthorizedError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

type TemplateCreateDocumentFromTemplateBadRequestIssue struct {
	Message string `json:"message"`
}

func (t *TemplateCreateDocumentFromTemplateBadRequestIssue) GetMessage() string {
	if t == nil {
		return ""
	}
	return t.Message
}

// TemplateCreateDocumentFromTemplateBadRequestError - Invalid input data
type TemplateCreateDocumentFromTemplateBadRequestError struct {
	Message  string                                              `json:"message"`
	Code     string                                              `json:"code"`
	Issues   []TemplateCreateDocumentFromTemplateBadRequestIssue `json:"issues,omitempty"`
	HTTPMeta components.HTTPMetadata                             `json:"-"`
}

var _ error = &TemplateCreateDocumentFromTemplateBadRequestError{}

func (e *TemplateCreateDocumentFromTemplateBadRequestError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
